-- 
-- Table structure for table x_person
-- 

CREATE OR REPLACE TYPE t_fvrt_food IS VARRAY(10) OF NUMBER(2);

CREATE TABLE x_person (
  person_id varchar2(8) NOT NULL,
  pers_type_id varchar2(6) NOT NULL,
  node_id number(4) NOT NULL,
  nat_ins_no varchar2(10) NOT NULL,
  first_name varchar2(20) NOT NULL,
  last_name varchar2(30) NOT NULL,
  initials varchar2(6),
  star_sign char(3) NOT NULL,
  email_addr varchar2(50),
  value1 number(5),
  value2 number(10,2),
  last_addr_no number(4),
  start_date date default '2000-01-01' NOT NULL,
  end_date date default '9999-12-31',
  picture varchar2(40),
  favourite_food t_fvrt_food,
  fckeditor_test clob,
  created_date timestamp NOT NULL,
  created_user varchar2(16) default 'UNKNOWN' NOT NULL,
  revised_date timestamp,
  revised_user varchar2(16),
  PRIMARY KEY  (person_id)
);
CREATE UNIQUE INDEX X_PERSON_IDX1 ON x_person (nat_ins_no);
CREATE INDEX  x_person_idx2 ON  x_person (pers_type_id);

REVOKE ALL ON x_person FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON x_person TO PUBLIC;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SET SCAN OFF;

ALTER SESSION SET CURRENT_SCHEMA = "XAMPLE";

-- 
-- Dumping data for table x_person
-- 

INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('AJM', 'GENFAC', 10, 'XX123456Y', 'Tony', 'Marston', '', 'CAP', 'tony@marston-home.demon.co.uk', 34, 12.34, 3, '1951-01-02', '2005-01-02', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('BB', 'ONE', 8, 'BB', 'Billy', 'Bunter', NULL, 'CAN', 'bb@fatman.com', NULL, NULL, 2, '2002-12-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2006-08-25 15:11:14', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('BG', 'EXEC', 21, 'BG', 'Bill', 'Gates', 'WG', 'CAN', NULL, NULL, NULL, 1, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('CC', 'BRICK', 9, 'CC', 'Charlie', 'Chan', NULL, 'CAN', NULL, NULL, NULL, 1, '1953-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2006-08-25 15:11:29', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('CJ', 'FUNNY', 7, 'CJ', 'Casper', 'Jarret', 'CJ', 'GEM', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('DD', 'ONE', 16, 'DD', 'Donald', 'Duck', NULL, 'SAG', NULL, NULL, NULL, 1, '1998-02-02', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2006-08-25 15:11:36', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('EE', 'FUNNY', 17, 'EE', 'Edna', 'Everage', 'EE', 'ARI', NULL, NULL, NULL, 1, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('FB', 'ANON', 7, 'FB', 'Fred', 'Bloggs', NULL, 'VIR', 'fred.bloggs@nowhere.com', 1, 2.20, 3, '2002-01-01', '9999-12-31', 'pictures/clown.jpg', t_fvrt_food('1','2','4','10'), 'this is a test', '2000-01-01 00:00:00', 'AJM', '2006-08-25 13:43:41', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('JI', 'FILM', 6, 'JI', 'Jeremy', 'Irons', 'JI', 'SAG', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('KB', 'DOLLY', 6, 'KB', 'Kim', 'Basinger', 'KB', 'SAG', 'kim.bassinger@hollywood.net', NULL, NULL, 1, '1990-01-01', '9999-12-31', 'pictures/female2.jpg', NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2005-10-29 23:12:47', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('KK', 'FILM', 8, 'KK', 'Kevin', 'Kline', 'KK', 'LEO', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('LH', 'DOLLY', 5, 'LH', 'Liz', 'Hurley', 'LH', 'VIR', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', 'pictures/female2.jpg', NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2005-03-10 21:56:30', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('LL', 'FAMOUS', 9, 'LL', 'Lord', 'Lucan', 'LL', 'GEM', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('LU', 'ACTOR', 10, 'LU', 'Liv', 'Ullman', 'LU', 'ARI', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('MM', 'CARTOO', 16, 'MM', 'Mickey', 'Mouse', NULL, 'LEO', NULL, NULL, NULL, 0, '2001-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('MP', 'DOLLY', 21, 'MP', 'Michelle', 'Pfeiffer', 'MP', 'CAP', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', 'pictures/female2.jpg', NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2005-03-10 21:56:37', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('MR', 'FILM', 6, 'MR', 'Mickey', 'Rooney', NULL, 'SCO', NULL, NULL, NULL, 1, '1940-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('NN', 'FILM', 17, 'NN', 'Nick', 'Nolte', 'NN', 'TAU', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('PA', 'DOLLY', 5, 'PA', 'Pamela', 'Anderson', 'PA', 'VIR', 'pam@hollywood.com', NULL, NULL, 2, '1980-07-01', '9999-12-31', 'pictures/female2.jpg', NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2005-10-29 23:12:36', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('PQ', 'ACTOR', 5, 'PQ', 'Pauline', 'Quirke', 'PQ', 'ARI', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('PV', 'HISTOR', 16, 'PV', 'Pancho', 'Villa', 'PV', 'LIB', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('RO', 'FAMOUS', 18, 'RO', 'Roy', 'Orbison', 'RO', 'SAG', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('RR', 'CARTOO', 7, 'RR', 'Road', 'Runner', NULL, 'VIR', 'roadrunner@cartoonland.com', NULL, NULL, 0, '1950-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('RW', 'DOLLY', 17, 'RW', 'Raquel', 'Welch', 'RW', 'VIR', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', 'pictures/female2.jpg', NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2005-03-10 21:56:50', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('SF', 'DOLLY', 18, 'SF', 'Sam', 'Fox', 'SF', 'VIR', NULL, NULL, NULL, 1, '1990-01-01', '9999-12-31', 'pictures/female2.jpg', NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2005-03-10 21:56:23', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('SS', 'DOLLY', 8, 'SS', 'Sharon', 'Stone', 'SS', 'VIR', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', 'pictures/female2.jpg', NULL, NULL, '2000-01-01 00:00:00', 'AJM', '2005-03-10 21:56:44', 'AJM');
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('TT', 'FUNNY', 9, 'TT', 'Terry', 'Thomas', 'TT', 'AQU', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('WC', 'CARTOO', 10, 'WC', 'Wiley', 'Coyote', NULL, 'SAG', 'wileycoyote@cartoonland.com', NULL, NULL, 1, '1950-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('WW', 'BORING', 18, 'WW', 'Willy', 'Wonka', '', 'GEM', 'willy@chocolatefactory.com', NULL, NULL, 1, '1999-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('XX', 'ANON', 21, 'XX', 'Xavier', 'Xtra', 'XX', 'LIB', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('YY', 'HISTOR', 5, 'YY', 'Yin', 'Yang', 'YY', 'SCO', NULL, NULL, NULL, 0, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);
INSERT INTO x_person (person_id, pers_type_id, node_id, nat_ins_no, first_name, last_name, initials, star_sign, email_addr, value1, value2, last_addr_no, start_date, end_date, picture, favourite_food, fckeditor_test, created_date, created_user, revised_date, revised_user) VALUES ('Z', 'CARTOO', 6, 'Z', 'Mr', 'Zebedee', 'Z', 'CAN', NULL, NULL, NULL, 1, '1990-01-01', '9999-12-31', NULL, NULL, NULL, '2000-01-01 00:00:00', 'AJM', NULL, NULL);


