
***** /product/inventory_item.list2.php 2006-07-05 20:37:26
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE product.product_id='PAP192'    LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='REAM'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PAP192'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-05 20:40:12
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE product.product_id='PAP192'    LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='REAM'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PAP192'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-05 20:40:17
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pr_inventory'   ORDER BY mnu_task.task_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='menu'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-06 16:28:47
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE product.product_id='PAP192'   ORDER BY product.product_id asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='REAM'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PAP192'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-06 16:28:50
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(search)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-06 16:29:05
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE product.product_id='PAP192'   ORDER BY product.product_id asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='REAM'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PAP192'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-06 16:29:07
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(search)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-08 18:19:12
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE product.product_id='PAP192'    LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='REAM'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PAP192'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-08 18:19:27
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /product/inventory_item.list2.php 2006-07-09 11:32:50
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE product.product_id='PEN202'    LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PEN202'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=0
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:32:53
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /product/inventory_item.list2.php 2006-07-09 11:33:01
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='BOX'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='DSK401'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=0
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:33:05
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 1 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='REAM'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PAP192'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:33:11
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='BOX'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='DSK401'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=0
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:33:16
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(add)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-09 11:33:45
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='BOX'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='DSK401'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:33:48
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 1 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='REAM'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PAP192'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:33:54
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='BOX'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='DSK401'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:33:56
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 1 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='REAM'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PAP192'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:33:59
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 2 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PEN202'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=0
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:34:03
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(add)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-09 11:34:20
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PAP192') OR (product.product_id='PEN202') OR (product.product_id='DSK401')    LIMIT 1 OFFSET 2 =>Count=3
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PEN202'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:34:28
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pr_inventory'   ORDER BY mnu_task.task_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='menu'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-09 11:41:26
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC100'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=0
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:41:29
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 1 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC101'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:41:38
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 1 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC101'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:41:40
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(enq)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-09 11:41:58
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 1 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC101'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:42:03
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC100'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=0
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:42:06
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(add)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-09 11:42:38
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC100'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:42:44
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 1 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC101'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:42:47
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC100'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:48:40
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC100'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:48:42
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /product/inventory_item.list2.php 2006-07-09 11:48:56
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC100'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:49:00
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 1 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC101'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:49:03
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC100'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:49:07
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(upd)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-09 11:49:43
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC100'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:49:46
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 1 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC101'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:49:50
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(upd)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list2.php 2006-07-09 11:50:06
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS product.*, unit_of_measure.uom_desc, unit_of_measure.uom_abbrev FROM product LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id) WHERE (product.product_id='PC101') OR (product.product_id='PC100')    LIMIT 1 OFFSET 1 =>Count=2
SELECT SQL_CALC_FOUND_ROWS identity_type_id, identity_type_desc FROM good_identity_type    ORDER BY identity_type_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS unit_of_measure.uom_desc, unit_of_measure.uom_abbrev, uom_category.uom_cat_desc FROM unit_of_measure LEFT JOIN uom_category ON (uom_category.uom_cat_id=unit_of_measure.uom_cat_id) WHERE unit_of_measure.uom_id='EACH'     =>Count=1
SELECT SQL_CALC_FOUND_ROWS *, inventory_item.qty_on_hand - inventory_item.total_qty AS variance_qty , container.container_desc, facility.facility_desc, lot.lot_id AS lot_desc, product.product_name FROM inventory_item LEFT JOIN container ON (container.facility_id=inventory_item.facility_id AND container.container_id=inventory_item.container_id) LEFT JOIN facility ON (facility.facility_id=inventory_item.facility_id) LEFT JOIN lot ON (lot.lot_id=inventory_item.lot_id) LEFT JOIN product ON (product.product_id=inventory_item.product_id) WHERE inventory_item.product_id='PC101'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list2.php 2006-07-09 11:50:08
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
