
***** /product/inventory_item.list3.php 2006-07-05 20:40:24
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-05 20:40:27
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 1 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='2'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=0
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-05 20:40:30
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-05 20:40:47
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /product/inventory_item.list3.php 2006-07-06 16:15:58
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:16:09
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(search)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-06 16:17:28
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:17:31
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:17:32
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(enq)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-06 16:19:34
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:19:36
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(search)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-06 16:21:09
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:21:22
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(search)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-06 16:27:13
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:27:16
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(search)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-06 16:27:21
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.inv_item_status_id LIKE '1' AND inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:27:29
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.inv_item_status_id LIKE '1' AND inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:27:29
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(enq)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-06 16:28:07
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.inv_item_status_id LIKE '1' AND inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-06 16:28:10
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(add)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-08 18:09:19
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE facility.facility_id='1'   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-08 18:18:08
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE facility.facility_id='1'   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-08 18:18:11
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(enq)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-08 18:18:54
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE facility.facility_id='1'   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-08 18:19:05
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='product'   ORDER BY mnu_task.task_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='menu'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-09 11:29:16
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE (facility.facility_id='1') OR (facility.facility_id='2')   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev , qty_on_hand - total_qty AS variance_qty  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='1'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-09 11:29:32
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /product/inventory_item.list3.php 2006-07-09 11:34:35
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE facility.facility_id='1'   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev , qty_on_hand - total_qty AS variance_qty  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=4
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='2'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-09 11:34:54
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(enq)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-09 11:35:26
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE facility.facility_id='1'   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev , qty_on_hand - total_qty AS variance_qty  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=4
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='2'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-09 11:38:07
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE facility.facility_id='1'   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev , qty_on_hand - total_qty AS variance_qty  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=4
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='2'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-09 11:38:09
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='pro_inv_item(enq)'   ORDER BY mnu_task.task_id asc  =>Count=1

***** /product/inventory_item.list3.php 2006-07-09 11:38:23
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS facility.*, facility_type.facility_type_desc FROM facility LEFT JOIN facility_type ON (facility_type.facility_type_id=facility.facility_type_id) WHERE facility.facility_id='1'   ORDER BY facility.facility_desc asc LIMIT 1 OFFSET 0 =>Count=1
SELECT SQL_CALC_FOUND_ROWS facility_type_id, facility_type_desc FROM facility_type    ORDER BY facility_type_desc asc  =>Count=2
SELECT SQL_CALC_FOUND_ROWS inventory_item.*, product.product_name, unit_of_measure.uom_abbrev , qty_on_hand - total_qty AS variance_qty  FROM inventory_item LEFT JOIN product ON (product.product_id=inventory_item.product_id) LEFT JOIN unit_of_measure ON (unit_of_measure.uom_id=product.uom_id)  WHERE inventory_item.facility_id='1'   ORDER BY inventory_item.product_id, inventory_item.inventory_item_id asc LIMIT 10 OFFSET 0 =>Count=4
SELECT SQL_CALC_FOUND_ROWS inv_item_status_id, inv_item_status_desc FROM inventory_item_status    ORDER BY inv_item_status_desc asc  =>Count=5
SELECT SQL_CALC_FOUND_ROWS container.container_desc, container_type.container_type_desc, facility.facility_desc FROM container LEFT JOIN container_type ON (container_type.container_type_id=container.container_type_id) LEFT JOIN facility ON (facility.facility_id=container.facility_id) WHERE container.facility_id='1' AND container.container_id='2'   ORDER BY container.facility_id, container.container_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_role.role_id,mnu_role.global_access, mnu_task.task_desc AS start_task_desc FROM mnu_role LEFT JOIN mnu_task ON (mnu_task.task_id=mnu_role.start_task_id) WHERE mnu_role.role_id='GLOBAL'   ORDER BY mnu_role.role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='pro_inv_item(list)3' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=6

***** /product/inventory_item.list3.php 2006-07-09 11:40:50
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
