-- file created on January 23, 2006, 6:41 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', NULL, 'PRODUCT', '2005-03-27 15:45:39', 'AJM', '2005-03-27 15:47:29', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'good_identification', 'good_identification', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'good_identification', 'identity_type_id', 'identity_type_id', '1', 'Y', '2', '2005-04-10 20:57:45', 'AJM', NULL, NULL),
('product', 'good_identification', 'identity_type_id', 'id_value', '2', 'Y', '3', '2005-04-10 20:57:45', 'AJM', NULL, NULL),
('product', 'good_identification', 'PRIMARY', 'product_id', '1', 'Y', '0', '2005-04-10 20:57:45', 'AJM', NULL, NULL),
('product', 'good_identification', 'PRIMARY', 'identity_type_id', '2', 'Y', '1', '2005-04-10 20:57:45', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'good_identification', 'product_id', '1', 'product_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:44', 'AJM', '2005-10-11 20:16:51', 'AJM'),
('product', 'good_identification', 'identity_type_id', '2', 'identity_type_id', NULL, 'varchar', NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'identity_type_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:44', 'AJM', '2005-10-11 20:16:51', 'AJM'),
('product', 'good_identification', 'id_value', '3', 'id_value', NULL, 'varchar', NULL, '32', '32', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:44', 'AJM', '2005-10-11 20:16:51', 'AJM'),
('product', 'good_identification', 'created_date', '4', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:44', 'AJM', '2005-10-11 20:16:51', 'AJM'),
('product', 'good_identification', 'created_user', '5', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:44', 'AJM', '2005-10-11 20:16:51', 'AJM'),
('product', 'good_identification', 'revised_date', '6', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:44', 'AJM', '2005-10-11 20:16:51', 'AJM'),
('product', 'good_identification', 'revised_user', '7', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:44', 'AJM', '2005-10-11 20:16:51', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'good_identity_type', 'good_identity_type', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'good_identity_type', 'PRIMARY', 'identity_type_id', '1', 'Y', '0', '2005-04-10 20:57:51', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'good_identity_type', 'identity_type_id', '1', 'identity_type_id', NULL, 'varchar', NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:50', 'AJM', '2005-10-11 20:16:57', 'AJM'),
('product', 'good_identity_type', 'identity_type_desc', '2', 'identity_type_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:50', 'AJM', '2005-10-11 20:16:57', 'AJM'),
('product', 'good_identity_type', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:50', 'AJM', '2005-10-11 20:16:57', 'AJM'),
('product', 'good_identity_type', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:50', 'AJM', '2005-10-11 20:16:57', 'AJM'),
('product', 'good_identity_type', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:51', 'AJM', '2005-10-11 20:16:57', 'AJM'),
('product', 'good_identity_type', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:51', 'AJM', '2005-10-11 20:16:57', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'good_identity_type', 'product', 'good_identification', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'identity_type_desc', NULL, '2005-04-10 23:21:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'good_identity_type', 'identity_type_id', 'product', 'good_identification', '0', 'identity_type_id', '2', '2005-04-10 23:21:52', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'price_component', 'price_component', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'price_component', 'PRIMARY', 'price_component_id', '1', 'Y', '0', '2005-04-10 20:57:57', 'AJM', NULL, NULL),
('product', 'price_component', 'product_id', 'product_id', '1', 'N', '1', '2005-04-10 20:57:57', 'AJM', NULL, NULL),
('product', 'price_component', 'prod_cat_id', 'prod_cat_id', '1', 'N', '3', '2005-04-10 20:57:57', 'AJM', NULL, NULL),
('product', 'price_component', 'prod_feature_id', 'prod_feature_id', '1', 'N', '2', '2005-04-10 20:57:57', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'price_component', 'price_component_id', '1', 'price_component_id', NULL, 'int', NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:55', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'start_date', '2', 'start_date', NULL, 'date', NULL, '12', '12', 'N', 'Y', NULL, '0000-00-00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:55', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'end_date', '3', 'end_date', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'price', '4', 'price', NULL, 'decimal', NULL, '13', '13', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, '11', '2', '0', '999999999.99', '0', '999999999.99', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'percent', '5', 'percent', NULL, 'decimal', NULL, '8', '8', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, '6', '3', '0', '999.999', '0', '100', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'price_type', '6', 'price_type', NULL, 'char', NULL, '1', '1', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'price_type', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'price_frequency', '7', 'price_frequency', NULL, 'char', NULL, '1', '1', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'price_frequency', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'uom_id', '8', 'uom_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_uom(popup)', 'uom_desc', NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'quantity', '9', 'quantity', NULL, 'smallint', NULL, '6', '6', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'product_id', '10', 'product_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_product(popup)', 'product_name', NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:05', 'AJM'),
('product', 'price_component', 'prod_feature_id', '11', 'prod_feature_id', NULL, 'mediumint', NULL, '8', '8', 'Y', 'N', 'MUL', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '16777215', '0', '16777215', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_prod_feature(popup)', 'prod_feature_desc', NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:06', 'AJM'),
('product', 'price_component', 'prod_cat_id', '12', 'prod_cat_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'prod_cat_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:06', 'AJM'),
('product', 'price_component', 'created_date', '13', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:06', 'AJM'),
('product', 'price_component', 'created_user', '14', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:56', 'AJM', '2005-10-11 20:17:06', 'AJM'),
('product', 'price_component', 'revised_date', '15', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:57', 'AJM', '2005-10-11 20:17:06', 'AJM'),
('product', 'price_component', 'revised_user', '16', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:57:57', 'AJM', '2005-10-11 20:17:06', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'PRIMARY', 'product_id', '1', 'Y', '0', '2005-04-10 20:58:05', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product_id', '1', 'product_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:04', 'AJM', '2005-10-11 20:17:16', 'AJM'),
('product', 'product', 'product_name', '2', 'product_name', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:04', 'AJM', '2005-10-11 20:17:16', 'AJM'),
('product', 'product', 'date_intro', '3', 'date_intro', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:04', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'end_date_sales', '4', 'end_date_sales', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:04', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'end_date_support', '5', 'end_date_support', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:04', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'comment', '6', 'comment', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:58:04', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'product_subtype', '7', 'product_subtype', NULL, 'char', NULL, '1', '1', 'N', 'Y', NULL, 'G', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'product_subtype', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:04', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'uom_id', '8', 'uom_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_uom(popup)', 'uom_desc', NULL, NULL, NULL, '2005-04-10 20:58:05', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'created_date', '9', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:05', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'created_user', '10', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:05', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'revised_date', '11', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:05', 'AJM', '2005-10-11 20:17:17', 'AJM'),
('product', 'product', 'revised_user', '12', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:05', 'AJM', '2005-10-11 20:17:17', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product', 'good_identification', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'product_name', NULL, '2005-04-10 23:24:03', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product_id', 'product', 'good_identification', '0', 'product_id', '2', '2005-04-10 23:24:03', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product', 'price_component', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'product_name', NULL, '2005-04-10 23:25:26', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product_id', 'product', 'price_component', '0', 'product_id', '2', '2005-04-10 23:25:27', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product', 'prod_cat_class', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'product_name', NULL, '2005-04-10 23:23:41', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product_id', 'product', 'prod_cat_class', '0', 'product_id', '2', '2005-04-10 23:23:41', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product', 'prod_feature_applicability', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'product_name', NULL, '2005-04-10 23:25:01', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product_id', 'product', 'prod_feature_applicability', '0', 'product_id', '2', '2005-04-10 23:25:01', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product', 'prod_feature_interaction', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'product_name', NULL, '2005-04-10 23:24:32', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product', 'product_id', 'product', 'prod_feature_interaction', '0', 'product_id', '2', '2005-04-10 23:24:32', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'product_category', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'PRIMARY', 'prod_cat_id', '1', 'Y', '0', '2005-04-10 20:58:11', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'prod_cat_id', '1', 'prod_cat_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM'),
('product', 'product_category', 'prod_cat_desc', '2', 'prod_cat_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM'),
('product', 'product_category', 'product_usage', '3', 'product_usage', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM'),
('product', 'product_category', 'product_industry', '4', 'product_industry', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM'),
('product', 'product_category', 'product_materials', '5', 'product_materials', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM'),
('product', 'product_category', 'created_date', '6', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM'),
('product', 'product_category', 'created_user', '7', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM'),
('product', 'product_category', 'revised_date', '8', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM'),
('product', 'product_category', 'revised_user', '9', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:11', 'AJM', '2005-10-11 20:17:27', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'product', 'price_component', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'prod_cat_desc', NULL, '2005-04-24 17:06:16', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'prod_cat_id', 'product', 'price_component', '0', 'prod_cat_id', '2', '2005-04-24 17:06:16', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'product', 'prod_cat_class', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'prod_cat_desc', NULL, '2005-04-10 23:27:39', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'prod_cat_id', 'product', 'prod_cat_class', '0', 'prod_cat_id', '2', '2005-04-10 23:27:39', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'product', 'prod_cat_rollup', '0', NULL, NULL, NULL, NULL, 'RES', NULL, '#calc#', 'prod_cat_desc as prod_cat_desc_snr', '2005-04-10 23:26:40', 'AJM', '2005-04-11 17:27:07', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'prod_cat_id', 'product', 'prod_cat_rollup', '0', 'prod_cat_id_snr', '2', '2005-04-10 23:26:40', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'product', 'prod_cat_rollup', '1', NULL, NULL, NULL, NULL, 'RES', NULL, '#calc#', 'prod_cat_desc as prod_cat_desc_jnr', '2005-04-10 23:27:14', 'AJM', '2005-04-11 17:27:16', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_category', 'prod_cat_id', 'product', 'prod_cat_rollup', '1', 'prod_cat_id_jnr', '2', '2005-04-10 23:27:14', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'product_feature', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'PRIMARY', 'prod_feature_id', '1', 'Y', '0', '2005-04-10 20:58:17', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'prod_feature_id', '1', 'prod_feature_id', NULL, 'mediumint', NULL, '9', '9', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '16777215', '0', '16777215', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM'),
('product', 'product_feature', 'prod_feature_desc', '2', 'prod_feature_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM'),
('product', 'product_feature', 'prod_feature_cat_id', '3', 'prod_feature_cat_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'prod_feature_cat_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM'),
('product', 'product_feature', 'uom_id', '4', 'uom_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'uom_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM'),
('product', 'product_feature', 'measurement', '5', 'measurement', NULL, 'float', NULL, '0', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM'),
('product', 'product_feature', 'created_date', '6', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM'),
('product', 'product_feature', 'created_user', '7', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM'),
('product', 'product_feature', 'revised_date', '8', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM'),
('product', 'product_feature', 'revised_user', '9', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:17', 'AJM', '2005-10-11 20:17:36', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'product', 'price_component', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'prod_feature_desc', NULL, '2005-04-24 17:04:59', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'prod_feature_id', 'product', 'price_component', '0', 'prod_feature_id', '2', '2005-04-24 17:04:59', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'product', 'prod_feature_applicability', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'prod_feature_desc', NULL, '2005-04-10 23:29:17', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'prod_feature_id', 'product', 'prod_feature_applicability', '0', 'prod_feature_id', '2', '2005-04-10 23:29:17', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'product', 'prod_feature_interaction', '0', NULL, NULL, NULL, NULL, 'RES', NULL, '#calc#', 'prod_feature_desc as prod_feature_desc_snr', '2005-04-10 23:28:15', 'AJM', '2005-04-11 17:28:32', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'prod_feature_id', 'product', 'prod_feature_interaction', '0', 'prod_feature_id_snr', '2', '2005-04-10 23:28:15', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'product', 'prod_feature_interaction', '1', NULL, NULL, NULL, NULL, 'RES', NULL, '#calc#', 'prod_feature_desc as prod_feature_desc_jnr', '2005-04-10 23:28:52', 'AJM', '2005-04-11 17:28:40', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature', 'prod_feature_id', 'product', 'prod_feature_interaction', '1', 'prod_feature_id_jnr', '2', '2005-04-10 23:28:52', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature_category', 'product_feature_category', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature_category', 'PRIMARY', 'prod_feature_cat_id', '1', 'Y', '0', '2005-04-10 20:58:23', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature_category', 'prod_feature_cat_id', '1', 'prod_feature_cat_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:23', 'AJM', '2005-10-11 20:17:44', 'AJM'),
('product', 'product_feature_category', 'prod_feature_cat_desc', '2', 'prod_feature_cat_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:23', 'AJM', '2005-10-11 20:17:44', 'AJM'),
('product', 'product_feature_category', 'measurement_reqd', '3', 'measurement_reqd', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:23', 'AJM', '2005-10-11 20:17:44', 'AJM'),
('product', 'product_feature_category', 'created_date', '4', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:23', 'AJM', '2005-10-11 20:17:44', 'AJM'),
('product', 'product_feature_category', 'created_user', '5', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:23', 'AJM', '2005-10-11 20:17:44', 'AJM'),
('product', 'product_feature_category', 'revised_date', '6', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:23', 'AJM', '2005-10-11 20:17:44', 'AJM'),
('product', 'product_feature_category', 'revised_user', '7', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:23', 'AJM', '2005-10-11 20:17:44', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature_category', 'product', 'product_feature', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'prod_feature_cat_desc', NULL, '2005-04-10 23:30:01', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'product_feature_category', 'prod_feature_cat_id', 'product', 'product_feature', '0', 'prod_feature_cat_id', '2', '2005-04-10 23:30:01', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_cat_class', 'prod_cat_class', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_cat_class', 'PRIMARY', 'product_id', '1', 'Y', '0', '2005-04-10 20:58:29', 'AJM', NULL, NULL),
('product', 'prod_cat_class', 'PRIMARY', 'prod_cat_id', '2', 'Y', '1', '2005-04-10 20:58:30', 'AJM', NULL, NULL),
('product', 'prod_cat_class', 'PRIMARY', 'seq_no', '3', 'Y', '2', '2005-04-10 20:58:30', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_cat_class', 'product_id', '1', 'product_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'prod_cat_id', '2', 'prod_cat_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_prod_cat(popup)', 'prod_cat_desc', NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'seq_no', '3', 'seq_no', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'primary_flag', '4', 'primary_flag', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'comment', '5', 'comment', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'start_date', '6', 'start_date', NULL, 'date', NULL, '12', '12', 'N', 'Y', NULL, '0000-00-00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'end_date', '7', 'end_date', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'created_date', '8', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'created_user', '9', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'revised_date', '10', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:52', 'AJM'),
('product', 'prod_cat_class', 'revised_user', '11', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:29', 'AJM', '2005-10-11 20:17:53', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_cat_rollup', 'prod_cat_rollup', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_cat_rollup', 'PRIMARY', 'prod_cat_id_snr', '1', 'Y', '0', '2005-04-10 20:58:35', 'AJM', NULL, NULL),
('product', 'prod_cat_rollup', 'PRIMARY', 'prod_cat_id_jnr', '2', 'Y', '1', '2005-04-10 20:58:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_cat_rollup', 'prod_cat_id_snr', '1', 'prod_cat_id_snr', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:35', 'AJM', '2005-10-11 20:18:00', 'AJM'),
('product', 'prod_cat_rollup', 'prod_cat_id_jnr', '2', 'prod_cat_id_jnr', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:35', 'AJM', '2005-10-11 20:18:00', 'AJM'),
('product', 'prod_cat_rollup', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:35', 'AJM', '2005-10-11 20:18:00', 'AJM'),
('product', 'prod_cat_rollup', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:35', 'AJM', '2005-10-11 20:18:00', 'AJM'),
('product', 'prod_cat_rollup', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:35', 'AJM', '2005-10-11 20:18:00', 'AJM'),
('product', 'prod_cat_rollup', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:35', 'AJM', '2005-10-11 20:18:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_feature_applicability', 'prod_feature_applicability', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_feature_applicability', 'PRIMARY', 'product_id', '1', 'Y', '0', '2005-04-10 20:58:41', 'AJM', NULL, NULL),
('product', 'prod_feature_applicability', 'PRIMARY', 'prod_feature_id', '2', 'Y', '1', '2005-04-10 20:58:41', 'AJM', NULL, NULL),
('product', 'prod_feature_applicability', 'PRIMARY', 'seq_no', '3', 'Y', '2', '2005-04-10 20:58:41', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_feature_applicability', 'product_id', '1', 'product_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:40', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'prod_feature_id', '2', 'prod_feature_id', NULL, 'mediumint', NULL, '9', '9', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '16777215', '0', '16777215', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_prod_feature(popup)', 'prod_feature_desc', NULL, NULL, NULL, '2005-04-10 20:58:40', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'seq_no', '3', 'seq_no', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', 'PRI', '1', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:40', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'feature_type', '4', 'feature_type', NULL, 'char', NULL, '1', '1', 'N', 'Y', NULL, 'O', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'feature_type', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:41', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'start_date', '5', 'start_date', NULL, 'date', NULL, '12', '12', 'N', 'Y', NULL, '0000-00-00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:41', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'end_date', '6', 'end_date', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:41', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'created_date', '7', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:41', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'created_user', '8', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:41', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'revised_date', '9', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:41', 'AJM', '2005-10-11 20:18:08', 'AJM'),
('product', 'prod_feature_applicability', 'revised_user', '10', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:41', 'AJM', '2005-10-11 20:18:08', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_feature_interaction', 'prod_feature_interaction', NULL, 'Y', NULL, '2005-04-10 20:57:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_feature_interaction', 'PRIMARY', 'product_id', '1', 'Y', '0', '2005-04-10 20:58:47', 'AJM', NULL, NULL),
('product', 'prod_feature_interaction', 'PRIMARY', 'prod_feature_id_snr', '2', 'Y', '1', '2005-04-10 20:58:47', 'AJM', NULL, NULL),
('product', 'prod_feature_interaction', 'PRIMARY', 'prod_feature_id_jnr', '3', 'Y', '2', '2005-04-10 20:58:47', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'prod_feature_interaction', 'product_id', '1', 'product_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:46', 'AJM', '2005-10-11 20:18:16', 'AJM'),
('product', 'prod_feature_interaction', 'prod_feature_id_snr', '2', 'prod_feature_id_snr', NULL, 'mediumint', NULL, '9', '9', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '16777215', '0', '16777215', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_prod_feature(popup)snr', 'prod_feature_desc_snr', NULL, NULL, NULL, '2005-04-10 20:58:46', 'AJM', '2005-10-11 20:18:16', 'AJM'),
('product', 'prod_feature_interaction', 'prod_feature_id_jnr', '3', 'prod_feature_id_jnr', NULL, 'mediumint', NULL, '9', '9', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '16777215', '0', '16777215', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_prod_feature(popup)jnr', 'prod_feature_desc_jnr', NULL, NULL, NULL, '2005-04-10 20:58:46', 'AJM', '2005-10-11 20:18:16', 'AJM'),
('product', 'prod_feature_interaction', 'feature_interaction', '4', 'feature_interaction', NULL, 'char', NULL, '1', '1', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'feature_interaction', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:47', 'AJM', '2005-10-11 20:18:16', 'AJM'),
('product', 'prod_feature_interaction', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:47', 'AJM', '2005-10-11 20:18:16', 'AJM'),
('product', 'prod_feature_interaction', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:47', 'AJM', '2005-10-11 20:18:16', 'AJM'),
('product', 'prod_feature_interaction', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:47', 'AJM', '2005-10-11 20:18:16', 'AJM'),
('product', 'prod_feature_interaction', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:47', 'AJM', '2005-10-11 20:18:17', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'unit_of_measure', NULL, 'Y', NULL, '2005-04-10 20:57:37', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'PRIMARY', 'uom_id', '1', 'Y', '0', '2005-04-10 20:58:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'uom_id', '1', 'uom_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:52', 'AJM', '2005-10-11 20:18:25', 'AJM'),
('product', 'unit_of_measure', 'uom_cat_id', '2', 'uom_cat_id', NULL, 'varchar', NULL, '4', '4', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'uom_cat_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:52', 'AJM', '2005-10-11 20:18:25', 'AJM'),
('product', 'unit_of_measure', 'uom_abbrev', '3', 'uom_abbrev', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:52', 'AJM', '2005-10-11 20:18:25', 'AJM'),
('product', 'unit_of_measure', 'uom_desc', '4', 'uom_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:52', 'AJM', '2005-10-11 20:18:25', 'AJM'),
('product', 'unit_of_measure', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:52', 'AJM', '2005-10-11 20:18:25', 'AJM'),
('product', 'unit_of_measure', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:52', 'AJM', '2005-10-11 20:18:25', 'AJM'),
('product', 'unit_of_measure', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:52', 'AJM', '2005-10-11 20:18:25', 'AJM'),
('product', 'unit_of_measure', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:52', 'AJM', '2005-10-11 20:18:25', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'product', 'price_component', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'uom_desc', NULL, '2005-04-10 23:32:22', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'uom_id', 'product', 'price_component', '0', 'uom_id', '2', '2005-04-10 23:32:22', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'product', 'product', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'uom_desc', NULL, '2005-04-10 23:31:32', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'uom_id', 'product', 'product', '0', 'uom_id', '2', '2005-04-10 23:31:32', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'product', 'product_feature', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'uom_desc', NULL, '2005-04-10 23:31:57', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'uom_id', 'product', 'product_feature', '0', 'uom_id', '2', '2005-04-10 23:31:57', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'product', 'uom_conversion', '0', 'unit_of_measure_from', NULL, NULL, NULL, 'RES', NULL, '#calc#', 'uom_desc as uom_desc_from', '2005-04-10 23:30:43', 'AJM', '2006-01-23 18:39:39', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'uom_id', 'product', 'uom_conversion', '0', 'uom_id_from', '2', '2005-04-10 23:30:43', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'product', 'uom_conversion', '1', 'unit_of_measure_to', NULL, NULL, NULL, 'RES', NULL, '#calc#', 'uom_desc as uom_desc_to', '2005-04-10 23:31:07', 'AJM', '2006-01-23 18:39:51', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'unit_of_measure', 'uom_id', 'product', 'uom_conversion', '1', 'uom_id_to', '2', '2005-04-10 23:31:07', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'uom_category', 'uom_category', NULL, 'Y', NULL, '2005-04-10 20:57:37', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'uom_category', 'PRIMARY', 'uom_cat_id', '1', 'Y', '0', '2005-04-10 20:58:58', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'uom_category', 'uom_cat_id', '1', 'uom_cat_id', NULL, 'varchar', NULL, '4', '4', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:57', 'AJM', '2005-10-11 20:18:33', 'AJM'),
('product', 'uom_category', 'uom_cat_desc', '2', 'uom_cat_desc', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:57', 'AJM', '2005-10-11 20:18:33', 'AJM'),
('product', 'uom_category', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:57', 'AJM', '2005-10-11 20:18:33', 'AJM'),
('product', 'uom_category', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:57', 'AJM', '2005-10-11 20:18:34', 'AJM'),
('product', 'uom_category', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:58', 'AJM', '2005-10-11 20:18:34', 'AJM'),
('product', 'uom_category', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:58:58', 'AJM', '2005-10-11 20:18:34', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'uom_category', 'product', 'unit_of_measure', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'uom_cat_desc', NULL, '2005-04-10 23:32:56', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'uom_category', 'uom_cat_id', 'product', 'unit_of_measure', '0', 'uom_cat_id', '2', '2005-04-10 23:32:56', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'uom_conversion', 'uom_conversion', NULL, 'Y', NULL, '2005-04-10 20:57:37', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'uom_conversion', 'PRIMARY', 'uom_id_from', '1', 'Y', '0', '2005-04-10 20:59:03', 'AJM', NULL, NULL),
('product', 'uom_conversion', 'PRIMARY', 'uom_id_to', '2', 'Y', '1', '2005-04-10 20:59:03', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('product', 'uom_conversion', 'uom_id_from', '1', 'uom_id_from', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:59:02', 'AJM', '2005-10-11 20:18:41', 'AJM'),
('product', 'uom_conversion', 'uom_id_to', '2', 'uom_id_to', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'pro_uom(popup)', 'uom_desc', NULL, NULL, NULL, '2005-04-10 20:59:03', 'AJM', '2005-10-11 20:18:41', 'AJM'),
('product', 'uom_conversion', 'conversion_factor', '3', 'conversion_factor', NULL, 'double', NULL, '0', '20', 'N', 'Y', NULL, '0', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:59:03', 'AJM', '2005-10-11 20:18:41', 'AJM'),
('product', 'uom_conversion', 'created_date', '4', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:59:03', 'AJM', '2005-10-11 20:18:41', 'AJM'),
('product', 'uom_conversion', 'created_user', '5', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:59:03', 'AJM', '2005-10-11 20:18:41', 'AJM'),
('product', 'uom_conversion', 'revised_date', '6', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:59:03', 'AJM', '2005-10-11 20:18:41', 'AJM'),
('product', 'uom_conversion', 'revised_user', '7', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:59:03', 'AJM', '2005-10-11 20:18:41', 'AJM');

-- finished
