<?php
// ****************************************************************************
// list of IP addresses which are allowed to use this service.
// NOTE: an empty array signifies ALL addresses are valid
// ****************************************************************************
$array = array();

$array[] = '127.0.0.1';
$array[] = '::1';
$array[] = '127.0.1.1';
$array[] = '80.177.120.119';	// Tony
$array[] = '74.204.188.125';	// korvus.kodega.com
$array[] = '85.233.162.91';		// xavier.agreeablenotion.com
$array[] = '87.230.79.251';		// magneto.kodega.de
$array[] = '83.169.47.84';		// magneto (new)
$array[] = '90.194.248.54'; 	// Rob
$array[] = '85.233.162.247'; 	// KODEGA.se
$array[] = '85.233.162.243'; 	// KODEGA.co.uk

return $array;

?>