-- file created on January 10, 2006, 6:37 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'workflow', NULL, 'WORKFLOW', '2005-03-27 15:45:42', 'AJM', '2005-03-27 15:47:37', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_arc', 'wf_arc', NULL, 'Y', 'wf_arc.created_date', '2005-04-09 18:21:52', 'AJM', '2005-10-29 23:52:48', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_arc', 'place_id', 'workflow_id', '1', 'N', '4', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'place_id', 'place_id', '2', 'N', '5', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'place_id', 'direction', '3', 'N', '6', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'PRIMARY', 'workflow_id', '1', 'Y', '0', '2005-04-09 18:22:01', 'AJM', NULL, NULL),
('workflow', 'wf_arc', 'PRIMARY', 'transition_id', '2', 'Y', '1', '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'PRIMARY', 'place_id', '3', 'Y', '2', '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'PRIMARY', 'direction', '4', 'Y', '3', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'transition_id', 'workflow_id', '1', 'N', '7', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'transition_id', 'transition_id', '2', 'N', '8', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'transition_id', 'direction', '3', 'N', '9', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_arc', 'workflow_id', '1', 'workflow_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'transition_id', '2', 'transition_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'transition_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'place_id', '3', 'place_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'place_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'direction', '4', 'direction', NULL, 'char', NULL, '3', '3', 'N', 'Y', 'PRI', 'IN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'direction', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'arc_type', '5', 'arc_type', NULL, 'varchar', NULL, '10', '10', 'N', 'Y', NULL, 'NORMAL', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'arc_type', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'pre_condition', '6', 'pre_condition', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'created_date', '7', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-30 12:22:21', 'AJM'),
('workflow', 'wf_arc', 'created_user', '8', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-30 12:22:21', 'AJM'),
('workflow', 'wf_arc', 'revised_date', '9', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'revised_user', '10', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'wf_case', NULL, 'Y', NULL, '2005-04-09 18:21:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'PRIMARY', 'case_id', '1', 'Y', '0', '2005-04-09 18:22:14', 'AJM', NULL, NULL),
('workflow', 'wf_case', 'workflow_id', 'workflow_id', '1', 'N', '1', '2005-04-09 18:22:14', 'AJM', '2005-10-11 20:23:10', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'case_id', '1', 'case_id', NULL, 'int', NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:13', 'AJM', '2005-10-11 20:23:09', 'AJM'),
('workflow', 'wf_case', 'workflow_id', '2', 'workflow_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'MUL', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'workflow_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:13', 'AJM', '2005-10-11 20:23:09', 'AJM'),
('workflow', 'wf_case', 'context', '3', 'context', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-09 18:22:13', 'AJM', '2005-10-11 20:23:09', 'AJM'),
('workflow', 'wf_case', 'case_status', '4', 'case_status', NULL, 'char', NULL, '2', '2', 'N', 'Y', NULL, 'OP', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'case_status', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2005-10-11 20:23:09', 'AJM'),
('workflow', 'wf_case', 'start_date', '5', 'start_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2005-10-30 12:22:32', 'AJM'),
('workflow', 'wf_case', 'end_date', '6', 'end_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2005-10-11 20:23:09', 'AJM'),
('workflow', 'wf_case', 'created_date', '7', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2005-10-30 12:22:32', 'AJM'),
('workflow', 'wf_case', 'created_user', '8', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2005-10-30 12:22:32', 'AJM'),
('workflow', 'wf_case', 'revised_date', '9', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2005-10-11 20:23:10', 'AJM'),
('workflow', 'wf_case', 'revised_user', '10', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2005-10-11 20:23:10', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'workflow', 'wf_token', '0', NULL, NULL, NULL, NULL, 'RES', NULL, NULL, NULL, '2005-04-09 18:31:56', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'case_id', 'workflow', 'wf_token', '0', 'case_id', '2', '2005-04-09 18:31:56', 'AJM', '2005-12-14 17:55:01', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'workflow', 'wf_workitem', '0', NULL, NULL, NULL, NULL, 'RES', NULL, NULL, NULL, '2005-04-09 18:32:20', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'case_id', 'workflow', 'wf_workitem', '0', 'case_id', '2', '2005-04-09 18:32:20', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'wf_place', NULL, 'Y', 'wf_place.place_type', '2005-04-09 18:21:52', 'AJM', '2005-10-29 23:53:03', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'PRIMARY', 'workflow_id', '1', 'Y', '0', '2005-04-09 18:22:21', 'AJM', NULL, NULL),
('workflow', 'wf_place', 'PRIMARY', 'place_id', '2', 'Y', '1', '2005-04-09 18:22:21', 'AJM', '2005-10-11 20:23:41', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'workflow_id', '1', 'workflow_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:20', 'AJM', '2005-10-11 20:23:40', 'AJM'),
('workflow', 'wf_place', 'place_id', '2', 'place_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2005-10-11 20:23:40', 'AJM'),
('workflow', 'wf_place', 'place_type', '3', 'place_type', NULL, 'char', NULL, '1', '1', 'N', 'Y', NULL, '5', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2005-10-11 20:23:40', 'AJM'),
('workflow', 'wf_place', 'place_name', '4', 'place_name', NULL, 'varchar', NULL, '80', '80', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2005-10-11 20:23:40', 'AJM'),
('workflow', 'wf_place', 'place_desc', '5', 'place_desc', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-09 18:22:21', 'AJM', '2005-10-11 20:23:41', 'AJM'),
('workflow', 'wf_place', 'created_date', '6', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2005-10-30 12:22:40', 'AJM'),
('workflow', 'wf_place', 'created_user', '7', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2005-10-30 12:22:40', 'AJM'),
('workflow', 'wf_place', 'revised_date', '8', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2005-10-11 20:23:41', 'AJM'),
('workflow', 'wf_place', 'revised_user', '9', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2005-10-11 20:23:41', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'workflow', 'wf_arc', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'place_name', NULL, '2005-04-09 18:29:04', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'place_id', 'workflow', 'wf_arc', '0', 'place_id', '2', '2005-04-09 18:29:05', 'AJM', '2005-12-14 17:55:02', 'AJM'),
('workflow', 'wf_place', 'workflow_id', 'workflow', 'wf_arc', '0', 'workflow_id', '2', '2005-04-09 18:29:05', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'workflow', 'wf_token', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'place_name', NULL, '2005-04-09 18:29:44', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'place_id', 'workflow', 'wf_token', '0', 'place_id', '2', '2005-04-09 18:29:44', 'AJM', '2005-12-14 17:55:02', 'AJM'),
('workflow', 'wf_place', 'workflow_id', 'workflow', 'wf_token', '0', 'workflow_id', '2', '2005-04-09 18:29:44', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_token', 'wf_token', NULL, 'Y', NULL, '2005-04-09 18:21:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_token', 'place_id', 'workflow_id', '1', 'N', '2', '2005-04-09 18:22:27', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'place_id', 'place_id', '2', 'N', '3', '2005-04-09 18:22:27', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'PRIMARY', 'case_id', '1', 'Y', '0', '2005-04-09 18:22:27', 'AJM', NULL, NULL),
('workflow', 'wf_token', 'PRIMARY', 'token_id', '2', 'Y', '1', '2005-04-09 18:22:27', 'AJM', '2005-10-11 20:23:50', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_token', 'case_id', '1', 'case_id', NULL, 'int', NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'token_id', '2', 'token_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'workflow_id', '3', 'workflow_id', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', 'MUL', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'workflow_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'place_id', '4', 'place_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'place_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'context', '5', 'context', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-09 18:22:26', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'token_status', '6', 'token_status', NULL, 'varchar', NULL, '4', '4', 'N', 'Y', NULL, 'FREE', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'token_status', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'enabled_date', '7', 'enabled_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2005-10-30 12:22:47', 'AJM'),
('workflow', 'wf_token', 'cancelled_date', '8', 'cancelled_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'consumed_date', '9', 'consumed_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2005-10-11 20:23:49', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'wf_transition', NULL, 'Y', NULL, '2005-04-09 18:21:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'PRIMARY', 'workflow_id', '1', 'Y', '0', '2005-04-09 18:22:33', 'AJM', NULL, NULL),
('workflow', 'wf_transition', 'PRIMARY', 'transition_id', '2', 'Y', '1', '2005-04-09 18:22:33', 'AJM', '2005-10-11 20:23:58', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'workflow_id', '1', 'workflow_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'transition_id', '2', 'transition_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'transition_name', '3', 'transition_name', NULL, 'varchar', NULL, '80', '80', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'transition_desc', '4', 'transition_desc', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-09 18:22:32', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'transition_trigger', '5', 'transition_trigger', NULL, 'varchar', NULL, '4', '4', 'N', 'Y', NULL, 'USER', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'transition_trigger', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'time_limit', '6', 'time_limit', NULL, 'int', NULL, '10', '10', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'task_id', '7', 'task_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'mnu_task(popup)a', 'task_desc', NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'role_id', '8', 'role_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'role_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'created_date', '9', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2005-10-30 12:22:55', 'AJM'),
('workflow', 'wf_transition', 'created_user', '10', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:33', 'AJM', '2005-10-30 12:22:55', 'AJM'),
('workflow', 'wf_transition', 'revised_date', '11', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:33', 'AJM', '2005-10-11 20:23:58', 'AJM'),
('workflow', 'wf_transition', 'revised_user', '12', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:33', 'AJM', '2005-10-11 20:23:58', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'workflow', 'wf_arc', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'transition_name', NULL, '2005-04-09 18:31:04', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'transition_id', 'workflow', 'wf_arc', '0', 'transition_id', '2', '2005-04-09 18:31:04', 'AJM', '2005-12-14 17:55:01', 'AJM'),
('workflow', 'wf_transition', 'workflow_id', 'workflow', 'wf_arc', '0', 'workflow_id', '2', '2005-04-09 18:31:04', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'workflow', 'wf_workitem', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'transition_name', NULL, '2005-04-09 18:30:32', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'transition_id', 'workflow', 'wf_workitem', '0', 'transition_id', '2', '2005-04-09 18:30:32', 'AJM', '2005-12-14 17:55:02', 'AJM'),
('workflow', 'wf_transition', 'workflow_id', 'workflow', 'wf_workitem', '0', 'workflow_id', '2', '2005-04-09 18:30:32', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'wf_workflow', NULL, 'Y', NULL, '2005-04-09 18:21:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'PRIMARY', 'workflow_id', '1', 'Y', '0', '2005-04-09 18:22:41', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', '1', 'workflow_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:40', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'workflow_name', '2', 'workflow_name', NULL, 'varchar', NULL, '80', '80', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'workflow_desc', '3', 'workflow_desc', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'start_task_id', '4', 'start_task_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'mnu_task(popup)a', 'task_desc', NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'is_valid', '5', 'is_valid', NULL, 'char', NULL, '0', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'workflow_errors', '6', 'workflow_errors', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'start_date', '7', 'start_date', NULL, 'date', NULL, '12', '12', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'end_date', '8', 'end_date', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'created_date', '9', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-30 12:23:05', 'AJM'),
('workflow', 'wf_workflow', 'created_user', '10', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-30 12:23:05', 'AJM'),
('workflow', 'wf_workflow', 'revised_date', '11', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:25', 'AJM'),
('workflow', 'wf_workflow', 'revised_user', '12', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2005-10-11 20:24:26', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_arc', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-09 18:25:06', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_arc', '0', 'workflow_id', '2', '2005-04-09 18:25:07', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_case', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-09 18:25:59', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_case', '0', 'workflow_id', '2', '2005-04-09 18:25:59', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_place', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, 'workflow_name', NULL, '2005-04-09 18:23:54', 'AJM', '2005-04-10 11:51:31', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_place', '0', 'workflow_id', '2', '2005-04-09 18:23:54', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_token', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-24 17:55:11', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_token', '0', 'workflow_id', '2', '2005-04-24 17:55:12', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_transition', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-09 18:25:35', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_transition', '0', 'workflow_id', '2', '2005-04-09 18:25:35', 'AJM', '2005-12-14 17:55:01', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_workitem', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-24 17:57:26', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_workitem', '0', 'workflow_id', '2', '2005-04-24 17:57:26', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workitem', 'wf_workitem', NULL, 'Y', NULL, '2005-04-09 18:21:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workitem', 'PRIMARY', 'case_id', '1', 'Y', '0', '2005-04-09 18:22:48', 'AJM', NULL, NULL),
('workflow', 'wf_workitem', 'PRIMARY', 'workitem_id', '2', 'Y', '1', '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'transition_id', 'workflow_id', '1', 'N', '2', '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'transition_id', 'transition_id', '2', 'N', '3', '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workitem', 'case_id', '1', 'case_id', NULL, 'int', NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2005-10-11 20:24:35', 'AJM'),
('workflow', 'wf_workitem', 'workitem_id', '2', 'workitem_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2005-10-11 20:24:35', 'AJM'),
('workflow', 'wf_workitem', 'workflow_id', '3', 'workflow_id', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', 'MUL', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'workflow_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'transition_id', '4', 'transition_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'transition_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'transition_trigger', '5', 'transition_trigger', NULL, 'varchar', NULL, '4', '4', 'N', 'Y', NULL, 'USER', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'transition_trigger', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'task_id', '6', 'task_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'mnu_task(popup)a', 'task_desc', NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'context', '7', 'context', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-09 18:22:47', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'workitem_status', '8', 'workitem_status', NULL, 'char', NULL, '2', '2', 'N', 'Y', NULL, 'EN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'workitem_status', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'enabled_date', '9', 'enabled_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'cancelled_date', '10', 'cancelled_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'finished_date', '11', 'finished_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'deadline', '12', 'deadline', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'role_id', '13', 'role_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'role_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'user_id', '14', 'user_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'user_id', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM');

-- finished
