-- file created on January 4, 2007, 2:07 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `db_comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'workflow', 'Author: A J Marston
Date: September, 2004

This is the database for the Activity-based Workflow system.', 'WORKFLOW', '2005-03-27 15:45:42', 'AJM', '2006-07-24 16:00:53', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_arc', 'wf_arc', 'This joins a PLACE with a TRANSITION.', 'Y', 'workflow_id, transition_id, place_id, direction', '2005-04-09 18:21:52', 'AJM', '2006-07-26 18:45:44', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_arc', 'place_id', 'workflow_id', '1', 'N', '4', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'place_id', 'place_id', '2', 'N', '5', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'place_id', 'direction', '3', 'N', '6', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'PRIMARY', 'workflow_id', '1', 'Y', '0', '2005-04-09 18:22:01', 'AJM', NULL, NULL),
('workflow', 'wf_arc', 'PRIMARY', 'transition_id', '2', 'Y', '1', '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'PRIMARY', 'place_id', '3', 'Y', '2', '2005-04-09 18:22:01', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'PRIMARY', 'direction', '4', 'Y', '3', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'transition_id', 'workflow_id', '1', 'N', '7', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'transition_id', 'transition_id', '2', 'N', '8', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM'),
('workflow', 'wf_arc', 'transition_id', 'direction', '3', 'N', '9', '2005-04-09 18:22:02', 'AJM', '2005-10-11 20:22:00', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_arc', 'workflow_id', '1', 'Workflow Id', 'This points to an entry on the WF_WORKFLOW table.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:17', 'batch'),
('workflow', 'wf_arc', 'transition_id', '2', 'Transition Id', 'This points to an entry on the WF_TRANSITION table.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'transition_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:17', 'batch'),
('workflow', 'wf_arc', 'place_id', '3', 'Place Id', 'This points to an entry on the WF_PLACE table.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'place_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:17', 'batch'),
('workflow', 'wf_arc', 'direction', '4', 'Direction', 'Possible options are:
IN - from a PLACE to a TRANSITION
OUT - from a TRANSITION to a PLACE', 'char', 'char', NULL, NULL, '3', '3', 'N', 'Y', 'PRI', 'IN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'direction', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:18', 'batch'),
('workflow', 'wf_arc', 'arc_type', '5', 'Arc Type', 'This identfies whether the arc is a standard sequence, a split or a join.', 'varchar', 'varchar', NULL, NULL, '10', '10', 'N', 'Y', NULL, 'SEQ', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'arc_type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:18', 'batch'),
('workflow', 'wf_arc', 'pre_condition', '6', 'Pre Condition', 'Only relevant if the arc_type is set to \"Explicit OR split\". This will contain the expression known as the GUARD which can only evaluate to TRUE or FALSE.', 'text', 'text', NULL, NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '70', '5', NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:18', 'batch'),
('workflow', 'wf_arc', 'created_date', '7', 'Created Date', 'The date and time on which this record was created.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:18', 'batch'),
('workflow', 'wf_arc', 'created_user', '8', 'Created User', 'The identity of the user who created this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:19', 'batch'),
('workflow', 'wf_arc', 'revised_date', '9', 'Revised Date', 'The date and time on which this record was amended.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:19', 'batch'),
('workflow', 'wf_arc', 'revised_user', '10', 'Revised User', 'The identity of the user who amended this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:01', 'AJM', '2006-10-06 19:12:19', 'batch');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'wf_case', 'This is an instance of a workflow, and is created whenever the start task is processed.', 'Y', 'workflow_id, case_id', '2005-04-09 18:21:52', 'AJM', '2006-07-26 18:47:01', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'PRIMARY', 'case_id', '1', 'Y', '0', '2005-04-09 18:22:14', 'AJM', NULL, NULL),
('workflow', 'wf_case', 'workflow_id', 'workflow_id', '1', 'N', '1', '2005-04-09 18:22:14', 'AJM', '2005-10-11 20:23:10', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'case_id', '1', 'Case Id', 'This is a unique identity generated by the system.', 'int', 'int', NULL, NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:13', 'AJM', '2006-10-06 19:12:19', 'batch'),
('workflow', 'wf_case', 'workflow_id', '2', 'Workflow Id', 'This points to an entry on the WF_WORKFLOW table.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'MUL', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'workflow_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:13', 'AJM', '2006-10-06 19:12:19', 'batch'),
('workflow', 'wf_case', 'context', '3', 'Context', 'This is the primary key of the database entry to which this case refers in the format of the WHERE clause of an SQL query. it is produced by the application task identified in START_TASK_ID on the WORKFLOW table, and may be amended by subsequent tasks (transitions).', 'varchar', 'varchar', NULL, NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '70', '5', NULL, '2005-04-09 18:22:13', 'AJM', '2006-10-06 19:12:20', 'batch'),
('workflow', 'wf_case', 'case_status', '4', 'Case Status', 'Possible options are: 
OP - Open 
CL - Closed 
SU - Suspended 
CA - Cancelled', 'char', 'char', NULL, NULL, '2', '2', 'N', 'Y', NULL, 'OP', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'case_status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2006-10-06 19:12:20', 'batch'),
('workflow', 'wf_case', 'start_date', '5', 'Start Date', 'This is set by the system when this case is opened.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2006-10-06 19:12:20', 'batch'),
('workflow', 'wf_case', 'end_date', '6', 'End Date', 'This is set by the system when this case is closed, which occurs when a token appears on the end place.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2006-10-06 19:12:20', 'batch'),
('workflow', 'wf_case', 'created_date', '7', 'Created Date', 'The date and time on which this record was created.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2006-10-06 19:12:20', 'batch'),
('workflow', 'wf_case', 'created_user', '8', 'Created User', 'The identity of the user who created this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2006-10-06 19:12:21', 'batch'),
('workflow', 'wf_case', 'revised_date', '9', 'Revised Date', 'The date and time on which this record was amended.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2006-10-06 19:12:21', 'batch'),
('workflow', 'wf_case', 'revised_user', '10', 'Revised User', 'The identity of the user who amended this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:14', 'AJM', '2006-10-06 19:12:21', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'workflow', 'wf_token', '0', NULL, NULL, 'Links WF_CASE to WF_TOKEN', NULL, 'RES', NULL, NULL, NULL, '2005-04-09 18:31:56', 'AJM', '2006-07-26 21:06:16', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'case_id', 'workflow', 'wf_token', '0', 'case_id', '1', '2005-04-09 18:31:56', 'AJM', '2006-08-22 16:04:48', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'workflow', 'wf_workitem', '0', NULL, NULL, 'Links WF_CASE to WF_WORKITEM', NULL, 'RES', NULL, NULL, NULL, '2005-04-09 18:32:20', 'AJM', '2006-07-26 21:06:32', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_case', 'case_id', 'workflow', 'wf_workitem', '0', 'case_id', '1', '2005-04-09 18:32:20', 'AJM', '2006-08-22 16:04:51', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'wf_place', 'A PLACE is equivalent to an in-box for a TRANSITION. Each workflow has one start place, one end place, and any number of intermediate places.', 'Y', 'workflow_id, place_type', '2005-04-09 18:21:52', 'AJM', '2006-07-26 18:50:27', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'PRIMARY', 'workflow_id', '1', 'Y', '0', '2005-04-09 18:22:21', 'AJM', NULL, NULL),
('workflow', 'wf_place', 'PRIMARY', 'place_id', '2', 'Y', '1', '2005-04-09 18:22:21', 'AJM', '2005-10-11 20:23:41', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'workflow_id', '1', 'Workflow Id', 'This points to an entry on the WF_WORKFLOW table.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:20', 'AJM', '2006-10-06 19:12:21', 'batch'),
('workflow', 'wf_place', 'place_id', '2', 'Place Id', 'This is a unique identity which is generated by the system', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2006-10-06 19:12:22', 'batch'),
('workflow', 'wf_place', 'place_type', '3', 'Place Type', 'Possible options are: 
1 = start place (there can be only one). 
5 = intermediate place (there can be any number). 
9 = end place (there can be only one).', 'char', 'char', NULL, NULL, '1', '1', 'N', 'Y', NULL, '5', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2006-10-06 19:12:22', 'batch'),
('workflow', 'wf_place', 'place_name', '4', 'Place Name', 'This is a short name for the entry.', 'varchar', 'varchar', NULL, NULL, '80', '80', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2006-10-06 19:12:22', 'batch'),
('workflow', 'wf_place', 'place_desc', '5', 'Place Desc', 'This is a long description for the entry.', 'text', 'text', NULL, NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '70', '5', NULL, '2005-04-09 18:22:21', 'AJM', '2006-10-06 19:12:22', 'batch'),
('workflow', 'wf_place', 'created_date', '6', 'Created Date', 'The date and time on which this record was created.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2006-10-06 19:12:22', 'batch'),
('workflow', 'wf_place', 'created_user', '7', 'Created User', 'The identity of the user who created this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2006-10-06 19:12:23', 'batch'),
('workflow', 'wf_place', 'revised_date', '8', 'Revised Date', 'The date and time on which this record was amended.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2006-10-06 19:12:23', 'batch'),
('workflow', 'wf_place', 'revised_user', '9', 'Revised User', 'The identity of the user who amended this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:21', 'AJM', '2006-10-06 19:12:23', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'workflow', 'wf_arc', '0', NULL, NULL, 'Links WF_PLACE to WF_ARC', NULL, 'RES', NULL, 'place_name', NULL, '2005-04-09 18:29:04', 'AJM', '2006-11-03 11:32:20', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'place_id', 'workflow', 'wf_arc', '0', 'place_id', '2', '2005-04-09 18:29:05', 'AJM', '2005-12-14 17:55:02', 'AJM'),
('workflow', 'wf_place', 'workflow_id', 'workflow', 'wf_arc', '0', 'workflow_id', '1', '2005-04-09 18:29:05', 'AJM', '2006-08-22 16:04:53', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'workflow', 'wf_token', '0', NULL, NULL, 'Links WF_PLACE to WF_TOKEN', NULL, 'RES', NULL, 'place_name', NULL, '2005-04-09 18:29:44', 'AJM', '2006-11-03 11:32:30', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_place', 'place_id', 'workflow', 'wf_token', '0', 'place_id', '2', '2005-04-09 18:29:44', 'AJM', '2005-12-14 17:55:02', 'AJM'),
('workflow', 'wf_place', 'workflow_id', 'workflow', 'wf_token', '0', 'workflow_id', '1', '2005-04-09 18:29:44', 'AJM', '2006-08-22 16:04:56', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_token', 'wf_token', 'A TOKEN represents the current state of a workflow process (CASE). Each PLACE can hold zero or more TOKENS at any one time. When a TRANSITION is fired it moves all tokens from its input places to its output places.', 'Y', 'workflow_id, case_id, token_id', '2005-04-09 18:21:52', 'AJM', '2006-07-26 18:53:46', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_token', 'place_id', 'workflow_id', '1', 'N', '2', '2005-04-09 18:22:27', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'place_id', 'place_id', '2', 'N', '3', '2005-04-09 18:22:27', 'AJM', '2005-10-11 20:23:49', 'AJM'),
('workflow', 'wf_token', 'PRIMARY', 'case_id', '1', 'Y', '0', '2005-04-09 18:22:27', 'AJM', NULL, NULL),
('workflow', 'wf_token', 'PRIMARY', 'token_id', '2', 'Y', '1', '2005-04-09 18:22:27', 'AJM', '2005-10-11 20:23:50', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_token', 'case_id', '1', 'Case Id', 'This points to an entry on the WF_CASE table.', 'int', 'int', NULL, NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:23', 'batch'),
('workflow', 'wf_token', 'token_id', '2', 'Token Id', 'This is a unique identity which is generated by the system.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:24', 'batch'),
('workflow', 'wf_token', 'workflow_id', '3', 'Workflow Id', 'This points to an entry on the WF_WORKFLOW table.', 'smallint', 'smallint', NULL, NULL, '6', '6', 'N', 'Y', 'MUL', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'workflow_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:24', 'batch'),
('workflow', 'wf_token', 'place_id', '4', 'Place Id', 'This points to an entry on the WF_PLACE table.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'place_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:24', 'batch'),
('workflow', 'wf_token', 'context', '5', 'Context', 'This is the primary key of the database entry as passed down by the previous transition.', 'varchar', 'varchar', NULL, NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '70', '5', NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:24', 'batch'),
('workflow', 'wf_token', 'token_status', '6', 'Token Status', 'Possible options are: 
FREE - Free 
LOCK - Locked 
CONS - Consumed 
CANC - Cancelled', 'varchar', 'varchar', NULL, NULL, '4', '4', 'N', 'Y', NULL, 'FREE', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'token_status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:24', 'batch'),
('workflow', 'wf_token', 'enabled_date', '7', 'Enabled Date', 'The date and time on which this token appeared in this place.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:25', 'batch'),
('workflow', 'wf_token', 'cancelled_date', '8', 'Cancelled Date', 'The date and time on which this token was cancelled.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:25', 'batch'),
('workflow', 'wf_token', 'consumed_date', '9', 'Consumed Date', 'The date and time on which this token was consumed by a transition being fired.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:26', 'AJM', '2006-10-06 19:12:25', 'batch');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'wf_transition', 'These represent tasks to be performed, and thus reference an entry on the MNU_TASK table. When a TRANSITION\'s input PLACE has enough TOKENS then the task is activated and the TOKENS are moved to the output PLACE.', 'Y', 'workflow_id, transition_id', '2005-04-09 18:21:52', 'AJM', '2006-07-26 18:58:27', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'PRIMARY', 'workflow_id', '1', 'Y', '0', '2005-04-09 18:22:33', 'AJM', NULL, NULL),
('workflow', 'wf_transition', 'PRIMARY', 'transition_id', '2', 'Y', '1', '2005-04-09 18:22:33', 'AJM', '2005-10-11 20:23:58', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'workflow_id', '1', 'Workflow Id', 'This points to an entry on the WF_WORKFLOW table.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:25', 'batch'),
('workflow', 'wf_transition', 'transition_id', '2', 'Transition Id', 'This is a unique identity which is generated by the system.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:26', 'batch'),
('workflow', 'wf_transition', 'transition_name', '3', 'Transition Name', 'This is a short name for the entry.', 'varchar', 'varchar', NULL, NULL, '80', '80', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:26', 'batch'),
('workflow', 'wf_transition', 'transition_desc', '4', 'Transition Desc', 'This is a long description for the entry.', 'text', 'text', NULL, NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '70', '5', NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:26', 'batch'),
('workflow', 'wf_transition', 'transition_trigger', '5', 'Transition Trigger', 'This identifies how this transition will be triggered. Possible options are: 
USER - manually by a user. 
AUTO - automatically by the system. 
MSG - by an external event. 
TIME - after a time limit has expired.', 'varchar', 'varchar', NULL, NULL, '4', '4', 'N', 'Y', NULL, 'USER', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'transition_trigger', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:26', 'batch'),
('workflow', 'wf_transition', 'time_limit', '6', 'Time Limit', 'This is a value in hours. It is only valid if transition_trigger=TIME.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '999', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:26', 'batch'),
('workflow', 'wf_transition', 'task_id', '7', 'Task Id', 'This points to an entry on the MNU_TASK table of the MENU database. It identifies the the task that will be activated when the transition is fired.', 'varchar', 'varchar', NULL, NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, NULL, 'mnu_task(popup)a', 'task_desc', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:27', 'batch'),
('workflow', 'wf_transition', 'role_id', '8', 'Role Id', 'This points to an entry on the MNU_ROLE table of the MENU database. Only users with this role will be able to process this transition.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'role_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:27', 'batch'),
('workflow', 'wf_transition', 'created_date', '9', 'Created Date', 'The date and time on which this record was created.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:32', 'AJM', '2006-10-06 19:12:27', 'batch'),
('workflow', 'wf_transition', 'created_user', '10', 'Created User', 'The identity of the user who created this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:33', 'AJM', '2006-10-06 19:12:27', 'batch'),
('workflow', 'wf_transition', 'revised_date', '11', 'Revised Date', 'The date and time on which this record was amended.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:33', 'AJM', '2006-10-06 19:12:28', 'batch'),
('workflow', 'wf_transition', 'revised_user', '12', 'Revised User', 'The identity of the user who amended this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:33', 'AJM', '2006-10-06 19:12:28', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'workflow', 'wf_arc', '0', NULL, NULL, 'Links WF_TRANSITION to WF_ARC', NULL, 'RES', NULL, 'transition_name', NULL, '2005-04-09 18:31:04', 'AJM', '2006-11-03 11:32:44', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'transition_id', 'workflow', 'wf_arc', '0', 'transition_id', '2', '2005-04-09 18:31:04', 'AJM', '2005-12-14 17:55:01', 'AJM'),
('workflow', 'wf_transition', 'workflow_id', 'workflow', 'wf_arc', '0', 'workflow_id', '1', '2005-04-09 18:31:04', 'AJM', '2006-08-22 16:04:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'workflow', 'wf_workitem', '0', NULL, NULL, 'Links WF_TRANSITION to WF_WORKITEM', NULL, 'RES', NULL, 'transition_name', NULL, '2005-04-09 18:30:32', 'AJM', '2006-11-03 11:32:52', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_transition', 'transition_id', 'workflow', 'wf_workitem', '0', 'transition_id', '2', '2005-04-09 18:30:32', 'AJM', '2005-12-14 17:55:02', 'AJM'),
('workflow', 'wf_transition', 'workflow_id', 'workflow', 'wf_workitem', '0', 'workflow_id', '1', '2005-04-09 18:30:32', 'AJM', '2006-08-22 16:05:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'wf_workflow', 'This is the definition of a workflow process. It identifies all the PLACES, ARCS and TRANSITIONS for that process.', 'Y', 'workflow_id', '2005-04-09 18:21:52', 'AJM', '2006-07-26 18:59:45', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'PRIMARY', 'workflow_id', '1', 'Y', '0', '2005-04-09 18:22:41', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', '1', 'Workflow Id', 'This is a unique identity which is generated by the system.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:40', 'AJM', '2006-10-06 19:12:28', 'batch'),
('workflow', 'wf_workflow', 'workflow_name', '2', 'Workflow Name', 'This is a short name for the entry.', 'varchar', 'varchar', NULL, NULL, '80', '80', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:28', 'batch'),
('workflow', 'wf_workflow', 'workflow_desc', '3', 'Workflow Desc', 'This is a long description for the entry.', 'text', 'text', NULL, NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '70', '5', NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:28', 'batch'),
('workflow', 'wf_workflow', 'start_task_id', '4', 'Start Task Id', 'This points to an entry on the MNU_TASK tabe of the MENU database. It identifies the task which, when processed, will cause a new case for this workflow to be created.', 'varchar', 'varchar', NULL, NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, NULL, 'mnu_task(popup)a', 'start_task_desc', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:29', 'batch'),
('workflow', 'wf_workflow', 'is_valid', '5', 'Is Valid', 'This is NO until the worflow has been validated, which is after all the places, transitions and arcs have been defined. A workflow cannot generate cases unless it is valid.', 'char', 'char', NULL, NULL, '0', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:29', 'batch'),
('workflow', 'wf_workflow', 'workflow_errors', '6', 'Workflow Errors', 'This contains all the reasons why the last validaton process failed.', 'text', 'text', NULL, NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '70', '5', NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:29', 'batch'),
('workflow', 'wf_workflow', 'start_date', '7', 'Start Date', 'This identifies the date on which this workflow process, if valid, comes into existence. It cannot be used to create cases before this date.', 'date', 'date', NULL, NULL, '12', '12', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:29', 'batch'),
('workflow', 'wf_workflow', 'end_date', '8', 'End Date', 'This identifies the date on which this workflow process ceases to be valid. It cannot be used to create cases after this date.', 'date', 'date', NULL, NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:30', 'batch'),
('workflow', 'wf_workflow', 'created_date', '9', 'Created Date', 'The date and time on which this record was created.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:30', 'batch'),
('workflow', 'wf_workflow', 'created_user', '10', 'Created User', 'The identity of the user who created this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:30', 'batch'),
('workflow', 'wf_workflow', 'revised_date', '11', 'Revised Date', 'The date and time on which this record was amended.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:30', 'batch'),
('workflow', 'wf_workflow', 'revised_user', '12', 'Revised User', 'The identity of the user who amended this record.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:41', 'AJM', '2006-10-06 19:12:30', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_arc', '0', NULL, NULL, 'Links WF_WORKFLOW to WF_ARC', NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-09 18:25:06', 'AJM', '2006-11-03 11:33:26', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_arc', '0', 'workflow_id', '1', '2005-04-09 18:25:07', 'AJM', '2006-08-22 16:05:05', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_case', '0', NULL, NULL, 'Links WF_WORKFLOW to WF_CASE', NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-09 18:25:59', 'AJM', '2006-11-03 11:33:34', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_case', '0', 'workflow_id', '1', '2005-04-09 18:25:59', 'AJM', '2006-08-22 16:05:07', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_place', '0', NULL, NULL, 'Links WF_WORKFLOW to WF_PLACE', NULL, 'DEL', NULL, 'workflow_name', NULL, '2005-04-09 18:23:54', 'AJM', '2006-11-03 11:33:41', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_place', '0', 'workflow_id', '1', '2005-04-09 18:23:54', 'AJM', '2006-08-22 16:05:10', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_token', '0', NULL, NULL, 'Links WF_WORKFLOW to WF_TOKEN', NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-24 17:55:11', 'AJM', '2006-11-03 11:33:49', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_token', '0', 'workflow_id', '1', '2005-04-24 17:55:12', 'AJM', '2006-08-22 16:05:13', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_transition', '0', NULL, NULL, 'Links WF_WORKFLOW to WF_TRANSITION', NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-09 18:25:35', 'AJM', '2006-11-03 11:33:57', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_transition', '0', 'workflow_id', '1', '2005-04-09 18:25:35', 'AJM', '2006-08-22 16:05:17', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow', 'wf_workitem', '0', NULL, NULL, 'Links WF_WORKFLOW to WF_WORKITEM', NULL, 'RES', NULL, 'workflow_name', NULL, '2005-04-24 17:57:26', 'AJM', '2006-11-03 11:34:04', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workflow', 'workflow_id', 'workflow', 'wf_workitem', '0', 'workflow_id', '1', '2005-04-24 17:57:26', 'AJM', '2006-08-22 16:05:20', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workitem', 'wf_workitem', 'This identifies when a TRANSITION is enabled or able to fire.', 'Y', 'workflow_id, case_id, workitem_id', '2005-04-09 18:21:52', 'AJM', '2006-07-26 19:02:05', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workitem', 'PRIMARY', 'case_id', '1', 'Y', '0', '2005-04-09 18:22:48', 'AJM', NULL, NULL),
('workflow', 'wf_workitem', 'PRIMARY', 'workitem_id', '2', 'Y', '1', '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'transition_id', 'workflow_id', '1', 'N', '2', '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM'),
('workflow', 'wf_workitem', 'transition_id', 'transition_id', '2', 'N', '3', '2005-04-09 18:22:48', 'AJM', '2005-10-11 20:24:36', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('workflow', 'wf_workitem', 'case_id', '1', 'Case Id', 'This points to an entry on the WF_CASE table.', 'int', 'int', NULL, NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2006-10-06 19:12:31', 'batch'),
('workflow', 'wf_workitem', 'workitem_id', '2', 'Workitem Id', 'This is a unique identity which is generated by the system.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2006-10-06 19:12:31', 'batch'),
('workflow', 'wf_workitem', 'workflow_id', '3', 'Workflow Id', 'This points to an entry on the WF_WORKFLOW table.', 'smallint', 'smallint', NULL, NULL, '6', '6', 'N', 'Y', 'MUL', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'workflow_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2006-10-06 19:12:31', 'batch'),
('workflow', 'wf_workitem', 'transition_id', '4', 'Transition Id', 'This points to an entry on the WF_TRANSITION table.', 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'transition_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2006-10-06 19:12:31', 'batch'),
('workflow', 'wf_workitem', 'transition_trigger', '5', 'Transition Trigger', 'This shows how this transition was fired. Possible options are: 
USER - manually by a user. 
AUTO - automatically by the system. 
MSG - by an external event. 
TIME - after a time limit expired.', 'varchar', 'varchar', NULL, NULL, '4', '4', 'N', 'Y', NULL, 'USER', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'transition_trigger', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2006-10-06 19:12:32', 'batch'),
('workflow', 'wf_workitem', 'task_id', '6', 'Task Id', 'his points to an entry on the MNU_TASK table of the MENU database, and identifies the task that will be activated when this workitem is processed.', 'varchar', 'varchar', NULL, NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, NULL, 'mnu_task(popup)a', 'task_desc', NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2006-10-06 19:12:32', 'batch'),
('workflow', 'wf_workitem', 'context', '7', 'Context', 'The primary key of a database entry that will be passed to the application task when this workitem is processed.', 'varchar', 'varchar', NULL, NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '70', '5', NULL, '2005-04-09 18:22:47', 'AJM', '2006-10-06 19:12:32', 'batch'),
('workflow', 'wf_workitem', 'workitem_status', '8', 'Workitem Status', 'Possible options are: 
EN - Enabled 
IP - In Progress 
CA - Cancelled 
FI - Finished', 'char', 'char', NULL, NULL, '2', '2', 'N', 'Y', NULL, 'EN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'workitem_status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:47', 'AJM', '2006-10-06 19:12:32', 'batch'),
('workflow', 'wf_workitem', 'enabled_date', '9', 'Enabled Date', 'The data and time on which this workitem was enabled.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2006-10-06 19:12:32', 'batch'),
('workflow', 'wf_workitem', 'cancelled_date', '10', 'Cancelled Date', 'The data and time on which this workitem was cancelled.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2006-10-06 19:12:33', 'batch'),
('workflow', 'wf_workitem', 'finished_date', '11', 'Finished Date', 'The data and time on which this workitem was finished.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2006-10-06 19:12:33', 'batch'),
('workflow', 'wf_workitem', 'deadline', '12', 'Deadline', 'If the transition_trigger=TIME this is the date and time on which the deadline expires.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2006-10-06 19:12:33', 'batch'),
('workflow', 'wf_workitem', 'role_id', '13', 'Role Id', 'This points to an entry in the MNU_ROLE table of the MENU database. Only users with this role will be able to process this transition.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'role_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2006-10-06 19:12:33', 'batch'),
('workflow', 'wf_workitem', 'user_id', '14', 'User Id', 'This points to an entry in the MNU_USER table of the MENU database. Only this user will be able to process this transition.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'user_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:22:48', 'AJM', '2006-10-06 19:12:34', 'batch');

-- finished
