
***** /audit/audit_dtl_list2.php 2006-10-14 18:17:38
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY task_id asc LIMIT 1 OFFSET 149 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='36' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:19:58
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /audit/audit_dtl_list2.php 2006-10-14 18:20:01
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='audit_dtl(search)'   ORDER BY task_id asc  =>Count=1

***** /audit/audit_dtl_list2.php 2006-10-14 18:20:07
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /audit/audit_dtl_list2.php 2006-10-14 18:20:50
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='audit_dtl(search)'   ORDER BY task_id asc  =>Count=1

***** /audit/audit_dtl_list2.php 2006-10-14 18:21:27
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, tran_seq_no, table_seq_no asc LIMIT 1 OFFSET 0 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='1' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:24:08
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /audit/audit_dtl_list2.php 2006-10-14 18:24:34
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='audit_dtl(search)'   ORDER BY task_id asc  =>Count=1

***** /audit/audit_dtl_list2.php 2006-10-14 18:25:00
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, tran_seq_no, table_seq_no asc LIMIT 1 OFFSET 0 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='1' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:25:41
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10

***** /audit/audit_dtl_list2.php 2006-10-14 18:27:13
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='audit_dtl(search)'   ORDER BY task_id asc  =>Count=1

***** /audit/audit_dtl_list2.php 2006-10-14 18:27:32
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='audit_dtl(search)'   ORDER BY task_id asc  =>Count=1

***** /audit/audit_dtl_list2.php 2006-10-14 18:27:35
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 0 =>Count=157
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='1' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:27:41
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 156 =>Count=157
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2471' AND audit_fld.tran_seq_no='1' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:27:49
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 155 =>Count=157
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='36' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:27:52
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 156 =>Count=157
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2471' AND audit_fld.tran_seq_no='1' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=2
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:27:54
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='audit_dtl(del)'   ORDER BY task_id asc  =>Count=1

***** /audit/audit_dtl_list2.php 2006-10-14 18:27:57
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 155 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='36' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:03
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 154 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='35' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:04
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 153 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='34' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=9
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:06
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 152 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='33' AND audit_fld.table_seq_no='6'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=9
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:08
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 151 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='33' AND audit_fld.table_seq_no='5'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=9
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:25
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 150 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='33' AND audit_fld.table_seq_no='4'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=9
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:26
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 149 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='33' AND audit_fld.table_seq_no='3'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=9
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:28
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 148 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='33' AND audit_fld.table_seq_no='2'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=9
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:29
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 147 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='33' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=9
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:31
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 146 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='32' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=21
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:34
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 0 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='1' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:37
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 155 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='36' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:40
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 154 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='35' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=3
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:42
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS audit_tbl.*, audit_trn.date, audit_trn.time, task_id, user_id  FROM audit_tbl LEFT JOIN audit_trn ON (audit_trn.session_id=audit_tbl.session_id AND audit_trn.tran_seq_no=audit_tbl.tran_seq_no) LEFT JOIN audit_ssn ON (audit_ssn.session_id=audit_trn.session_id)  WHERE audit_ssn.user_id LIKE 'AJM' AND audit_trn.date>='2006-10-14'   ORDER BY date, time, audit_tbl.tran_seq_no, audit_tbl.table_seq_no asc LIMIT 1 OFFSET 153 =>Count=156
SELECT SQL_CALC_FOUND_ROWS audit_fld.* FROM audit_fld WHERE audit_fld.session_id='2470' AND audit_fld.tran_seq_no='34' AND audit_fld.table_seq_no='1'   ORDER BY audit_fld.session_id, audit_fld.tran_seq_no, audit_fld.table_seq_no, audit_fld.field_id asc LIMIT 10 OFFSET 0 =>Count=9
SELECT SQL_CALC_FOUND_ROWS role_id,global_access FROM mnu_role WHERE role_id='GLOBAL'   ORDER BY role_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS x.task_id, x.script_id, mnu_nav_button.button_text, mnu_nav_button.context_preselect FROM mnu_nav_button LEFT JOIN mnu_task ON (mnu_task.task_id = mnu_nav_button.task_id_snr) LEFT JOIN mnu_task AS x ON (x.task_id = mnu_nav_button.task_id_jnr)  WHERE mnu_task.task_id='audit_dtl(list)2' AND (x.is_disabled='N')   ORDER BY mnu_nav_button.sort_seq asc  =>Count=2

***** /audit/audit_dtl_list2.php 2006-10-14 18:28:49
SELECT SQL_CALC_FOUND_ROWS * FROM mnu_control WHERE record_id='SYSTEM' and field_id LIKE 'SHUTDOWN%'   ORDER BY record_id, field_id asc  =>Count=10
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='test'   ORDER BY task_id asc  =>Count=1
SELECT SQL_CALC_FOUND_ROWS mnu_task.task_id, task_desc, button_text, task_type, pattern_id, script_id, subsys_dir, initial_passthru, selection_fixed, selection_temp, settings, order_by, is_disabled, global_access, keep_data, log_sql_query, screen_refresh, use_https, CASE WHEN mnu_role_task.role_id IS NOT NULL THEN 1 ELSE 0 END AS access_allowed FROM mnu_task LEFT JOIN mnu_subsystem ON (mnu_subsystem.subsys_id=mnu_task.subsys_id) LEFT JOIN mnu_role_task ON (mnu_role_task.task_id=mnu_task.task_id AND mnu_role_task.role_id='GLOBAL') LEFT JOIN mnu_role ON (mnu_role.role_id='GLOBAL') WHERE mnu_task.task_id='menu'   ORDER BY task_id asc  =>Count=1
