-- file created on January 10, 2006, 6:37 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit', NULL, 'AUDIT', '2005-03-27 15:45:30', 'AJM', '2005-03-27 15:47:01', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_fld', 'audit_fld (field)', 'This records each field (column) which has been updated durng a user\'s session.', 'N', 'session_id,tran_seq_no,table_seq_no,field_id', '2005-12-30 09:54:51', 'AJM', '2005-12-30 10:01:39', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_fld', 'PRIMARY', 'session_id', '1', 'Y', '0', '2005-12-30 11:44:10', 'AJM', NULL, NULL),
('audit', 'audit_fld', 'PRIMARY', 'tran_seq_no', '2', 'Y', '1', '2005-12-30 11:44:10', 'AJM', NULL, NULL),
('audit', 'audit_fld', 'PRIMARY', 'table_seq_no', '3', 'Y', '2', '2005-12-30 11:44:10', 'AJM', NULL, NULL),
('audit', 'audit_fld', 'PRIMARY', 'field_id', '4', 'Y', '3', '2005-12-30 11:44:10', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_fld', 'session_id', '1', 'session_id', NULL, 'bigint', NULL, '20', '20', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '1.844674407371e+019', '0', '9.2233720368548e+018', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2005-12-30 12:54:26', 'AJM'),
('audit', 'audit_fld', 'tran_seq_no', '2', 'tran_seq_no', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '32767', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2005-12-30 12:31:22', 'AJM'),
('audit', 'audit_fld', 'table_seq_no', '3', 'table_seq_no', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '32767', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2005-12-30 12:31:22', 'AJM'),
('audit', 'audit_fld', 'field_id', '4', 'field_id', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2005-12-30 12:19:59', 'AJM'),
('audit', 'audit_fld', 'old_value', '5', 'old_value', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2005-12-30 12:20:06', 'AJM'),
('audit', 'audit_fld', 'new_value', '6', 'new_value', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2005-12-30 12:20:17', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_ssn', 'audit_ssn (session)', 'This records the start of each user session for logging purposes.', 'N', 'date,time', '2005-12-30 09:54:51', 'AJM', '2005-12-30 09:57:15', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_ssn', 'PRIMARY', 'session_id', '1', 'Y', '0', '2005-12-30 11:44:22', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_ssn', 'session_id', '1', 'session_id', NULL, 'bigint', NULL, '20', '20', 'N', 'Y', 'PRI', NULL, 'Y', 'Y', NULL, NULL, NULL, '0', '1.844674407371e+019', '0', '9.2233720368548e+018', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:21', 'AJM', '2005-12-30 12:34:51', 'AJM'),
('audit', 'audit_ssn', 'user_id', '2', 'user_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:21', 'AJM', '2005-12-30 15:20:41', 'AJM'),
('audit', 'audit_ssn', 'date', '3', 'date', NULL, 'date', NULL, '12', '12', 'N', 'Y', NULL, '2000-01-01', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:21', 'AJM', '2005-12-30 15:31:42', 'AJM'),
('audit', 'audit_ssn', 'time', '4', 'time', NULL, 'time', NULL, '8', '8', 'N', 'Y', NULL, '00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:21', 'AJM', '2005-12-30 15:38:42', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_ssn', 'audit', 'audit_trn', '0', NULL, NULL, NULL, NULL, 'RES', NULL, NULL, NULL, '2005-12-30 12:23:21', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_ssn', 'session_id', 'audit', 'audit_trn', '0', 'session_id', '1', '2005-12-30 12:23:21', 'AJM', '2005-12-30 12:23:30', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_tbl', 'audit_tbl (table)', 'This records each database table which is updated within a transaction within a user\'s session.', 'N', 'session_id,tran_seq_no,table_seq_no', '2005-12-30 09:54:51', 'AJM', '2005-12-30 10:00:00', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_tbl', 'pkey', 'pkey', '1', 'N', '3', '2005-12-30 11:44:30', 'AJM', NULL, NULL),
('audit', 'audit_tbl', 'PRIMARY', 'session_id', '1', 'Y', '0', '2005-12-30 11:44:30', 'AJM', NULL, NULL),
('audit', 'audit_tbl', 'PRIMARY', 'tran_seq_no', '2', 'Y', '1', '2005-12-30 11:44:30', 'AJM', NULL, NULL),
('audit', 'audit_tbl', 'PRIMARY', 'table_seq_no', '3', 'Y', '2', '2005-12-30 11:44:30', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_tbl', 'session_id', '1', 'session_id', NULL, 'bigint', NULL, '20', '20', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '1.844674407371e+019', '0', '9.2233720368548e+018', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:29', 'AJM', '2005-12-30 12:31:35', 'AJM'),
('audit', 'audit_tbl', 'tran_seq_no', '2', 'tran_seq_no', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '32767', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:29', 'AJM', '2005-12-30 12:31:35', 'AJM'),
('audit', 'audit_tbl', 'table_seq_no', '3', 'table_seq_no', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '32767', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:29', 'AJM', '2005-12-30 12:31:35', 'AJM'),
('audit', 'audit_tbl', 'base_name', '4', 'base_name', NULL, 'varchar', NULL, '32', '32', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:30', 'AJM', '2005-12-30 12:21:44', 'AJM'),
('audit', 'audit_tbl', 'table_name', '5', 'table_name', NULL, 'varchar', NULL, '32', '32', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:30', 'AJM', '2005-12-30 12:21:52', 'AJM'),
('audit', 'audit_tbl', 'pkey', '6', 'pkey', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:30', 'AJM', '2005-12-30 12:22:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_tbl', 'audit', 'audit_fld', '0', NULL, NULL, NULL, NULL, 'RES', NULL, NULL, NULL, '2005-12-30 12:24:29', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_tbl', 'session_id', 'audit', 'audit_fld', '0', 'session_id', '1', '2005-12-30 12:24:29', 'AJM', '2005-12-30 12:24:40', 'AJM'),
('audit', 'audit_tbl', 'table_seq_no', 'audit', 'audit_fld', '0', 'table_seq_no', '3', '2005-12-30 12:24:29', 'AJM', '2005-12-30 12:24:40', 'AJM'),
('audit', 'audit_tbl', 'tran_seq_no', 'audit', 'audit_fld', '0', 'tran_seq_no', '2', '2005-12-30 12:24:29', 'AJM', '2005-12-30 12:24:40', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_trn', 'audit_trn (transaction)', 'This records each database transaction within a user\'s session.', 'N', 'session_id, tran_seq_no', '2005-12-30 09:54:51', 'AJM', '2005-12-30 09:58:30', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_trn', 'PRIMARY', 'session_id', '1', 'Y', '0', '2005-12-30 11:44:38', 'AJM', NULL, NULL),
('audit', 'audit_trn', 'PRIMARY', 'tran_seq_no', '2', 'Y', '1', '2005-12-30 11:44:38', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_trn', 'session_id', '1', 'session_id', NULL, 'bigint', NULL, '20', '20', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '1.844674407371e+019', '0', '9.2233720368548e+018', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:37', 'AJM', '2005-12-30 12:31:43', 'AJM'),
('audit', 'audit_trn', 'tran_seq_no', '2', 'tran_seq_no', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '32767', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:37', 'AJM', '2005-12-30 12:31:43', 'AJM'),
('audit', 'audit_trn', 'date', '3', 'date', NULL, 'date', NULL, '12', '12', 'N', 'Y', NULL, '2000-01-01', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:37', 'AJM', '2005-12-30 15:42:07', 'AJM'),
('audit', 'audit_trn', 'time', '4', 'time', NULL, 'time', NULL, '8', '8', 'N', 'Y', NULL, '00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:37', 'AJM', '2005-12-30 15:42:14', 'AJM'),
('audit', 'audit_trn', 'task_id', '5', 'task_id', NULL, 'varchar', NULL, '32', '32', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:38', 'AJM', '2005-12-30 12:22:51', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_trn', 'audit', 'audit_tbl', '0', NULL, NULL, NULL, NULL, 'RES', NULL, NULL, NULL, '2005-12-30 12:23:54', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'audit_trn', 'session_id', 'audit', 'audit_tbl', '0', 'session_id', '1', '2005-12-30 12:23:54', 'AJM', '2005-12-30 12:24:04', 'AJM'),
('audit', 'audit_trn', 'tran_seq_no', 'audit', 'audit_tbl', '0', 'tran_seq_no', '2', '2005-12-30 12:23:54', 'AJM', '2005-12-30 12:24:05', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'php_session', 'php_session', NULL, 'N', NULL, '2005-04-09 16:08:14', 'AJM', '2005-04-17 11:06:55', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'php_session', 'last_updated', 'last_updated', '1', 'N', '1', '2005-04-09 16:08:54', 'AJM', '2005-04-10 17:38:56', 'AJM'),
('audit', 'php_session', 'PRIMARY', 'session_id', '1', 'Y', NULL, '2005-04-09 16:08:54', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('audit', 'php_session', 'session_id', '1', 'session_id', NULL, 'varchar', NULL, '32', '32', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:53', 'AJM', '2005-10-11 18:12:37', 'AJM'),
('audit', 'php_session', 'user_id', '2', 'user_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:53', 'AJM', '2005-10-11 18:12:37', 'AJM'),
('audit', 'php_session', 'date_created', '3', 'date_created', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:54', 'AJM', '2005-10-30 11:40:03', 'AJM'),
('audit', 'php_session', 'last_updated', '4', 'last_updated', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', 'MUL', '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:54', 'AJM', '2005-10-30 11:40:03', 'AJM'),
('audit', 'php_session', 'session_data', '5', 'session_data', NULL, 'longtext', NULL, '4294967295', '4294967295', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:10:58', 'AJM', '2005-10-30 11:45:02', 'AJM');

-- finished
