ALTER SESSION SET CURRENT_SCHEMA = "DICT";

ALTER TABLE DICT.DICT_RELATIONSHIP ADD (KEY_NAME VARCHAR2(64) DEFAULT 'PRIMARY' NOT NULL);

ALTER TABLE DICT.DICT_RELATIONSHIP MODIFY (REL_TYPE DEFAULT 'RES' );
