ALTER SESSION SET CURRENT_SCHEMA = "DICT";

ALTER TABLE "DICT_COLUMN" rename column "COLUMN_DESC" to "COLUMN_NAME";
ALTER TABLE "DICT_COLUMN" MODIFY ( column_name VARCHAR2(80 BYTE) );
ALTER TABLE "DICT_COLUMN" rename column "COL_COMMENT" to "COLUMN_DESC";

ALTER TABLE "DICT_DATABASE" rename column "DATABASE_DESC" to "DATABASE_NAME";
ALTER TABLE "DICT_DATABASE" MODIFY ( DATABASE_NAME VARCHAR2(80 BYTE) );
ALTER TABLE "DICT_DATABASE" rename column "DB_COMMENT" to "DATABASE_DESC";

ALTER TABLE "DICT_RELATIONSHIP" rename column "RELATION_DESC" to "RELATION_NAME";
ALTER TABLE "DICT_RELATIONSHIP" MODIFY ( RELATION_NAME VARCHAR2(80 BYTE) );
ALTER TABLE "DICT_RELATIONSHIP" rename column "REL_COMMENT" to "RELATION_DESC";
ALTER TABLE "DICT_RELATIONSHIP" rename column "REL_TYPE" to "RELATION_TYPE";

ALTER TABLE "DICT_TABLE" rename column "TABLE_DESC" to "TABLE_NAME";
ALTER TABLE "DICT_TABLE" MODIFY ( TABLE_NAME VARCHAR2(80 BYTE) );
ALTER TABLE "DICT_TABLE" rename column "TBL_COMMENT" to "TABLE_DESC";

-- finish