ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SET SCAN OFF;

ALTER SESSION SET CURRENT_SCHEMA = "DICT";

TRUNCATE TABLE dict_column;
TRUNCATE TABLE dict_database;
TRUNCATE TABLE dict_related_column;
TRUNCATE TABLE dict_relationship;
TRUNCATE TABLE dict_table;
TRUNCATE TABLE dict_table_key;
