<?php

// Each entry must be an array of values

$array['star_sign'] = array('ARI' => 'Aries',
                            'AQU' => 'Aquarius',
                            'CAN' => 'Cancer',
                            'CAP' => 'Capricorn',
                            'GEM' => 'Gemini',
                            'LEO' => 'Leo',
                            'LIB' => 'Libra',
                            'PIS' => 'Pisces',
                            'SAG' => 'Sagittarius',
                            'SCO' => 'Scorpio',
                            'TAU' => 'Taurus',
                            'VIR' => 'Virgo');

//$array['star_sign'] = array('ARI' => array('value' => 'Aries',
//                                           'onkeypress' => "alert('Aries');",
//                                           'show' => 'relationONE'),
//                            'AQU' => array('value' => 'Aquarius',
//                                           'onkeypress' => "alert('Aquarius');",
//                                           'show' => 'relationTWO'),
//                            'CAN' => array('value' => 'Cancer',
//                                           'onkeypress' => "alert('Cancer');",
//                                           'show' => 'relationTHREE'),
//                            'CAP' => array('value' => 'Capricorn',
//                                           'onkeypress' => "alert('Capricorn');"),
//                            'GEM' => array('value' => 'Gemini',
//                                           'onkeypress' => "alert('Gemini');"),
//                            'LEO' => array('value' => 'Leo',
//                                           'onkeypress' => "alert('Leo');"),
//                            'LIB' => array('value' => 'Libra',
//                                           'onkeypress' => "alert('Libra');"),
//                            'PIS' => array('value' => 'Pisces',
//                                           'onkeypress' => "alert('Pisces');"),
//                            'SAG' => array('value' => 'Sagittarius',
//                                           'onkeypress' => "alert('Sagittarius');"),
//                            'SCO' => array('value' => 'Scorpio',
//                                           'onkeypress' => "alert('Scorpio');"),
//                            'TAU' => array('value' => 'Taurus',
//                                           'onkeypress' => "alert('Taurus');"),
//                            'VIR' => array('value' => 'Virgo',
//                                           'onkeypress' => "alert('Virgo');"));

$array['favourite_food'] = array('1' => 'Eggs',
                                 '2' => 'Bacon',
                                 '3' => 'Chips',
                                 '4' => 'Beans',
                                 '5' => 'Sausages',
                                 '6' => 'Mushrooms',
                                 '7' => 'Tomatoes',
                                 '8' => 'Hash Browns',
                                 '9' => 'Toast',
                                 '10' => 'Fried Bread');

 return $array;

?>