-- file created on January 20, 2006, 8:14 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'xample', NULL, 'XAMPLE', '2005-03-27 15:45:42', 'AJM', '2005-03-27 15:47:43', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'test_autoincrement', 'test_autoincrement', NULL, 'N', NULL, '2005-10-01 16:39:56', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'test_autoincrement', 'PRIMARY', 'id', '1', 'Y', '0', '2005-10-01 18:01:13', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'test_autoincrement', 'id', '1', 'id', NULL, 'int', NULL, '10', '10', 'N', 'Y', 'PRI', NULL, 'Y', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:13', 'AJM', NULL, NULL),
('xample', 'test_autoincrement', 'field1', '2', 'field1', NULL, 'varchar', NULL, '40', '40', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:13', 'AJM', NULL, NULL),
('xample', 'test_autoincrement', 'field2', '3', 'field2', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:13', 'AJM', NULL, NULL);

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'x_option', NULL, 'Y', 'option_id', '2005-10-01 16:39:56', 'AJM', '2005-10-29 22:15:47', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'PRIMARY', 'option_id', '1', 'Y', '0', '2005-10-01 18:01:45', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'option_id', '1', 'option_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2005-10-30 16:28:50', 'AJM'),
('xample', 'x_option', 'option_desc', '2', 'option_desc', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', NULL, NULL),
('xample', 'x_option', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2005-10-30 12:30:50', 'AJM'),
('xample', 'x_option', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2005-10-30 12:31:06', 'AJM'),
('xample', 'x_option', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2005-10-30 12:31:18', 'AJM'),
('xample', 'x_option', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2005-10-30 12:31:29', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'xample', 'x_pers_opt_xref', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'option_desc', NULL, '2005-10-29 20:09:50', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'option_id', 'xample', 'x_pers_opt_xref', '0', 'option_id', '2', '2005-10-29 20:09:50', 'AJM', '2005-12-14 17:55:03', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'x_person', NULL, 'Y', 'person_id', '2005-10-01 18:03:28', 'AJM', '2005-10-30 16:46:16', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'nat_ins_no', 'nat_ins_no', '1', 'Y', '1', '2005-10-02 16:02:22', 'AJM', NULL, NULL),
('xample', 'x_person', 'pers_type_id', 'pers_type_id', '1', 'N', '2', '2005-10-02 16:02:22', 'AJM', NULL, NULL),
('xample', 'x_person', 'PRIMARY', 'person_id', '1', 'Y', '0', '2005-10-02 16:02:22', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'person_id', '1', 'person_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:35', 'AJM', '2005-10-29 23:55:45', 'AJM'),
('xample', 'x_person', 'pers_type_id', '2', 'pers_type_id', NULL, 'varchar', NULL, '6', '6', 'Y', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'pers_type_id', NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:35', 'AJM', '2005-10-30 11:30:58', 'AJM'),
('xample', 'x_person', 'node_id', '3', 'node_id', NULL, 'smallint', NULL, '4', '4', 'Y', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'x_tree_structure(popup)', 'node_desc', NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-30 11:30:58', 'AJM'),
('xample', 'x_person', 'nat_ins_no', '4', 'nat_ins_no', NULL, 'varchar', NULL, '10', '10', 'N', 'Y', 'UNI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:44:47', 'AJM'),
('xample', 'x_person', 'first_name', '5', 'first_name', NULL, 'varchar', NULL, '20', '20', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:44:47', 'AJM'),
('xample', 'x_person', 'last_name', '6', 'last_name', NULL, 'varchar', NULL, '30', '30', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:44:47', 'AJM'),
('xample', 'x_person', 'initials', '7', 'initials', NULL, 'varchar', NULL, '6', '6', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-30 16:31:40', 'AJM'),
('xample', 'x_person', 'star_sign', '8', 'star_sign', NULL, 'char', NULL, '3', '3', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'star_sign', NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:44:47', 'AJM'),
('xample', 'x_person', 'email_addr', '9', 'email_addr', NULL, 'varchar', NULL, '50', '50', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'email', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:05:40', 'AJM'),
('xample', 'x_person', 'value1', '10', 'value1', NULL, 'smallint', NULL, '6', '6', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '32767', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-30 11:30:58', 'AJM'),
('xample', 'x_person', 'value2', '11', 'value2', NULL, 'decimal', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'Y', 'BWZ', '10', '2', '0', '99999999.99', '0', '99999999.99', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-30 11:30:58', 'AJM'),
('xample', 'x_person', 'last_addr_no', '12', 'last_addr_no', NULL, 'smallint', NULL, '4', '4', 'Y', 'N', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:07:21', 'AJM'),
('xample', 'x_person', 'start_date', '13', 'start_date', NULL, 'date', NULL, '12', '12', 'N', 'Y', NULL, '2000-01-01', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', NULL, NULL),
('xample', 'x_person', 'end_date', '14', 'end_date', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, '9999-12-31', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:38:34', 'AJM'),
('xample', 'x_person', 'picture', '15', 'picture', NULL, 'varchar', NULL, '40', '40', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'image', '75', '95', 'N', NULL, NULL, 'filepicker', NULL, 'x_person(filepicker)', NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:09:08', 'AJM'),
('xample', 'x_person', 'created_date', '16', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-30 11:30:58', 'AJM'),
('xample', 'x_person', 'created_user', '17', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-30 11:30:58', 'AJM'),
('xample', 'x_person', 'revised_date', '18', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:10:27', 'AJM'),
('xample', 'x_person', 'revised_user', '19', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2005-10-29 23:10:39', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'xample', 'x_person_addr', '0', NULL, NULL, NULL, NULL, 'DEL', 'address_no desc', '#calc#', 'CONCAT(first_name, \\\' \\\', last_name) AS person_name', '2005-10-29 17:02:46', 'AJM', '2005-10-29 20:15:07', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'person_id', 'xample', 'x_person_addr', '0', 'person_id', '2', '2005-10-29 17:02:46', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'xample', 'x_pers_opt_xref', '0', NULL, NULL, NULL, NULL, 'RES', NULL, '#calc#', 'CONCAT(first_name, \' \', last_name) AS person_name', '2005-10-29 19:56:26', 'AJM', '2005-10-30 00:02:18', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'person_id', 'xample', 'x_pers_opt_xref', '0', 'person_id', '2', '2005-10-29 19:56:26', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person_addr', 'x_person_addr', NULL, 'Y', 'person_id, address_no', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:22', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person_addr', 'PRIMARY', 'person_id', '1', 'Y', '0', '2005-10-02 15:32:32', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'PRIMARY', 'address_no', '2', 'Y', '1', '2005-10-02 15:32:32', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person_addr', 'person_id', '1', 'person_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:47', 'AJM', '2005-10-30 16:35:19', 'AJM'),
('xample', 'x_person_addr', 'address_no', '2', 'address_no', NULL, 'smallint', NULL, '4', '4', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:47', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'telephone_no', '3', 'telephone_no', NULL, 'varchar', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:47', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'fax_no', '4', 'fax_no', NULL, 'varchar', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:47', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'addr_line_1', '5', 'addr_line_1', NULL, 'varchar', NULL, '30', '30', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:47', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'addr_line_2', '6', 'addr_line_2', NULL, 'varchar', NULL, '30', '30', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'addr_line_3', '7', 'addr_line_3', NULL, 'varchar', NULL, '30', '30', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'town', '8', 'town', NULL, 'varchar', NULL, '30', '30', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2005-10-30 16:36:09', 'AJM'),
('xample', 'x_person_addr', 'county', '9', 'county', NULL, 'varchar', NULL, '30', '30', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'postcode', '10', 'postcode', NULL, 'varchar', NULL, '10', '10', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2005-10-30 16:36:29', 'AJM'),
('xample', 'x_person_addr', 'start_date', '11', 'start_date', NULL, 'date', NULL, '12', '12', 'N', 'Y', NULL, '2000-01-01', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'end_date', '12', 'end_date', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, '9999-12-31', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2005-10-30 16:37:14', 'AJM'),
('xample', 'x_person_addr', 'created_date', '13', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2005-10-30 12:35:54', 'AJM'),
('xample', 'x_person_addr', 'created_user', '14', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2005-10-30 12:34:41', 'AJM'),
('xample', 'x_person_addr', 'revised_date', '15', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2005-10-30 12:35:16', 'AJM'),
('xample', 'x_person_addr', 'revised_user', '16', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2005-10-30 12:34:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_opt_xref', 'x_pers_opt_xref', NULL, 'Y', 'option_id', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:28', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_opt_xref', 'option_id', 'option_id', '1', 'N', '2', '2005-10-01 18:01:00', 'AJM', NULL, NULL),
('xample', 'x_pers_opt_xref', 'PRIMARY', 'person_id', '1', 'Y', '0', '2005-10-01 18:01:00', 'AJM', NULL, NULL),
('xample', 'x_pers_opt_xref', 'PRIMARY', 'option_id', '2', 'Y', '1', '2005-10-01 18:01:00', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_opt_xref', 'person_id', '1', 'person_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:59', 'AJM', '2005-10-30 16:42:34', 'AJM'),
('xample', 'x_pers_opt_xref', 'option_id', '2', 'option_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:59', 'AJM', '2005-10-30 16:42:42', 'AJM'),
('xample', 'x_pers_opt_xref', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:59', 'AJM', '2005-10-30 12:38:12', 'AJM'),
('xample', 'x_pers_opt_xref', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:59', 'AJM', '2005-10-30 12:38:26', 'AJM'),
('xample', 'x_pers_opt_xref', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:00', 'AJM', '2005-10-30 12:38:35', 'AJM'),
('xample', 'x_pers_opt_xref', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:00', 'AJM', '2005-10-30 12:38:45', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'x_pers_type', NULL, 'Y', 'pers_type_id', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:34', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'PRIMARY', 'pers_type_id', '1', 'Y', '0', '2005-10-01 18:01:06', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'pers_type_id', '1', 'pers_type_id', NULL, 'varchar', NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:05', 'AJM', '2005-10-30 12:39:16', 'AJM'),
('xample', 'x_pers_type', 'pers_type_desc', '2', 'pers_type_desc', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', NULL, NULL),
('xample', 'x_pers_type', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2005-10-30 12:39:32', 'AJM'),
('xample', 'x_pers_type', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2005-10-30 12:39:45', 'AJM'),
('xample', 'x_pers_type', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2005-10-30 12:39:56', 'AJM'),
('xample', 'x_pers_type', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2005-10-30 12:40:06', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'xample', 'x_person', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'pers_type_desc', NULL, '2005-10-29 20:02:28', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'pers_type_id', 'xample', 'x_person', '0', 'pers_type_id', '2', '2005-10-29 20:02:28', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'x_tree_level', NULL, 'Y', 'x_tree_level.tree_level_seq', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:40', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'PRIMARY', 'tree_type_id', '1', 'Y', '0', '2005-10-01 18:01:23', 'AJM', NULL, NULL),
('xample', 'x_tree_level', 'PRIMARY', 'tree_level_id', '2', 'Y', '1', '2005-10-01 18:01:23', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'tree_type_id', '1', 'tree_type_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2005-10-30 12:40:34', 'AJM'),
('xample', 'x_tree_level', 'tree_level_id', '2', 'tree_level_id', NULL, 'tinyint', NULL, '3', '3', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', NULL, NULL),
('xample', 'x_tree_level', 'tree_level_seq', '3', 'tree_level_seq', NULL, 'tinyint', NULL, '3', '3', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2006-01-15 14:46:54', 'AJM'),
('xample', 'x_tree_level', 'tree_level_desc', '4', 'tree_level_desc', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', NULL, NULL),
('xample', 'x_tree_level', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2005-10-30 12:41:07', 'AJM'),
('xample', 'x_tree_level', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2005-10-30 12:41:18', 'AJM'),
('xample', 'x_tree_level', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2005-10-30 12:41:34', 'AJM'),
('xample', 'x_tree_level', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:23', 'AJM', '2005-10-30 12:41:44', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'xample', 'x_tree_node', '0', NULL, NULL, NULL, NULL, 'RES', NULL, '#calc#', 'tree_level_seq, tree_level_desc', '2005-10-29 20:06:29', 'AJM', '2006-01-15 11:33:49', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'tree_level_id', 'xample', 'x_tree_node', '0', 'tree_level_id', '2', '2005-10-29 20:06:29', 'AJM', '2005-12-14 17:55:02', 'AJM'),
('xample', 'x_tree_level', 'tree_type_id', 'xample', 'x_tree_node', '0', 'tree_type_id', '2', '2005-10-29 20:06:29', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'x_tree_node', NULL, 'Y', 'tree_level_id, node_id', '2005-10-01 16:39:56', 'AJM', '2005-10-30 18:49:34', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'node_id_snr', 'node_id_snr', '1', 'N', '3', '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'PRIMARY', 'node_id', '1', 'Y', '0', '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'tree_type_id', 'tree_type_id', '1', 'N', '1', '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'tree_type_id', 'tree_level_id', '2', 'N', '2', '2005-10-01 18:01:29', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'node_id', '1', 'node_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:28', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'tree_type_id', '2', 'tree_type_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:28', 'AJM', '2005-10-30 16:25:58', 'AJM'),
('xample', 'x_tree_node', 'tree_level_id', '3', 'tree_level_id', NULL, 'tinyint', NULL, '3', '3', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'node_desc', '4', 'node_desc', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'node_id_snr', '5', 'node_id_snr', NULL, 'smallint', NULL, '5', '5', 'Y', 'N', 'MUL', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2005-10-30 18:53:47', 'AJM'),
('xample', 'x_tree_node', 'external_code', '6', 'external_code', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'created_date', '7', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2005-10-30 16:26:36', 'AJM'),
('xample', 'x_tree_node', 'created_user', '8', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2005-10-30 16:26:47', 'AJM'),
('xample', 'x_tree_node', 'revised_date', '9', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2005-10-30 16:26:57', 'AJM'),
('xample', 'x_tree_node', 'revised_user', '10', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2005-10-30 16:27:10', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'xample', 'x_person', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'node_desc', NULL, '2005-10-29 20:04:34', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'node_id', 'xample', 'x_person', '0', 'node_id', '2', '2005-10-29 20:04:34', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'xample', 'x_tree_node', '0', 'x_tree_node_snr', 'x_tree_node_jnr', NULL, NULL, 'RES', NULL, '#calc#', 'x_tree_node_snr.node_desc AS node_desc_snr', '2005-10-29 20:08:38', 'AJM', '2006-01-18 20:11:14', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'node_id', 'xample', 'x_tree_node', '0', 'node_id_snr', '2', '2005-10-29 20:08:38', 'AJM', '2005-12-14 17:55:03', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'x_tree_type', NULL, 'Y', 'x_tree_type.tree_type_id', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:52', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'PRIMARY', 'tree_type_id', '1', 'Y', '0', '2005-10-01 18:01:37', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'tree_type_id', '1', 'tree_type_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2005-10-30 16:27:38', 'AJM'),
('xample', 'x_tree_type', 'tree_type_desc', '2', 'tree_type_desc', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', NULL, NULL),
('xample', 'x_tree_type', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2005-10-30 16:27:53', 'AJM'),
('xample', 'x_tree_type', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2005-10-30 16:28:04', 'AJM'),
('xample', 'x_tree_type', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2005-10-30 16:28:14', 'AJM'),
('xample', 'x_tree_type', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2005-10-30 16:28:25', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'xample', 'x_tree_level', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'tree_type_desc', NULL, '2005-10-29 20:05:21', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'tree_type_id', 'xample', 'x_tree_level', '0', 'tree_type_id', '2', '2005-10-29 20:05:21', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'xample', 'x_tree_node', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'tree_type_desc', NULL, '2005-10-29 20:05:57', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'tree_type_id', 'xample', 'x_tree_node', '0', 'tree_type_id', '2', '2005-10-29 20:05:57', 'AJM', '2005-12-14 17:55:02', 'AJM');

-- finished
