-- file created on February 27, 2007, 4:17 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `db_comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'xample', NULL, 'XAMPLE', '2005-03-27 15:45:42', 'AJM', '2005-03-27 15:47:43', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'test_autoincrement', 'test_autoincrement', NULL, 'N', NULL, '2005-10-01 16:39:56', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'test_autoincrement', 'PRIMARY', 'id', '1', 'Y', '0', '2005-10-01 18:01:13', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'test_autoincrement', 'id', '1', 'Id', NULL, 'int', 'int', NULL, NULL, '10', '10', 'N', 'Y', 'PRI', NULL, 'Y', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:13', 'AJM', '2006-10-06 19:12:34', 'batch'),
('xample', 'test_autoincrement', 'field1', '2', 'Field1', NULL, 'varchar', 'varchar', NULL, NULL, '40', '40', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:13', 'AJM', '2006-10-06 19:12:34', 'batch'),
('xample', 'test_autoincrement', 'field2', '3', 'Field2', NULL, 'varchar', 'varchar', NULL, NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:13', 'AJM', '2006-10-06 19:12:34', 'batch');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'x_option', NULL, 'Y', 'option_id', '2005-10-01 16:39:56', 'AJM', '2005-10-29 22:15:47', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'PRIMARY', 'option_id', '1', 'Y', '0', '2005-10-01 18:01:45', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'option_id', '1', 'Option Id', NULL, 'varchar', 'varchar', NULL, NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2006-10-06 19:12:34', 'batch'),
('xample', 'x_option', 'option_desc', '2', 'Option Description', NULL, 'varchar', 'varchar', NULL, NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2007-02-25 14:39:29', 'AJM'),
('xample', 'x_option', 'created_date', '3', 'Created Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2006-10-06 19:12:35', 'batch'),
('xample', 'x_option', 'created_user', '4', 'Created User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2006-10-06 19:12:35', 'batch'),
('xample', 'x_option', 'revised_date', '5', 'Revised Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2006-10-06 19:12:35', 'batch'),
('xample', 'x_option', 'revised_user', '6', 'Revised User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:45', 'AJM', '2006-10-06 19:12:36', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'xample', 'x_pers_opt_xref', '0', NULL, NULL, 'Links X_OPTION to X_PERS_OPT_XREF', NULL, 'RES', NULL, 'option_desc', NULL, '2005-10-29 20:09:50', 'AJM', '2006-08-22 16:05:49', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_option', 'option_id', 'xample', 'x_pers_opt_xref', '0', 'option_id', '1', '2005-10-29 20:09:50', 'AJM', '2006-08-22 16:05:49', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_opt_xref', 'x_pers_opt_xref', NULL, 'Y', 'option_id', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:28', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_opt_xref', 'option_id', 'option_id', '1', 'N', '2', '2005-10-01 18:01:00', 'AJM', NULL, NULL),
('xample', 'x_pers_opt_xref', 'PRIMARY', 'person_id', '1', 'Y', '0', '2005-10-01 18:01:00', 'AJM', NULL, NULL),
('xample', 'x_pers_opt_xref', 'PRIMARY', 'option_id', '2', 'Y', '1', '2005-10-01 18:01:00', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_opt_xref', 'person_id', '1', 'Person Id', NULL, 'varchar', 'varchar', NULL, NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:59', 'AJM', '2006-10-06 19:12:44', 'batch'),
('xample', 'x_pers_opt_xref', 'option_id', '2', 'Option Id', NULL, 'varchar', 'varchar', NULL, NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:59', 'AJM', '2006-10-06 19:12:44', 'batch'),
('xample', 'x_pers_opt_xref', 'created_date', '3', 'Created Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:59', 'AJM', '2006-10-06 19:12:44', 'batch'),
('xample', 'x_pers_opt_xref', 'created_user', '4', 'Created User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:59', 'AJM', '2006-10-06 19:12:45', 'batch'),
('xample', 'x_pers_opt_xref', 'revised_date', '5', 'Revised Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:00', 'AJM', '2006-10-06 19:12:45', 'batch'),
('xample', 'x_pers_opt_xref', 'revised_user', '6', 'Revised User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:00', 'AJM', '2006-10-06 19:12:45', 'batch');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'x_pers_type', NULL, 'Y', 'pers_type_id', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:34', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'PRIMARY', 'pers_type_id', '1', 'Y', '0', '2005-10-01 18:01:06', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'pers_type_id', '1', 'Pers Type Id', NULL, 'varchar', 'varchar', NULL, NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:05', 'AJM', '2006-10-06 19:12:45', 'batch'),
('xample', 'x_pers_type', 'pers_type_desc', '2', 'Person Type Description', NULL, 'varchar', 'varchar', NULL, NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2007-02-25 14:39:42', 'AJM'),
('xample', 'x_pers_type', 'created_date', '3', 'Created Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2006-10-06 19:12:46', 'batch'),
('xample', 'x_pers_type', 'created_user', '4', 'Created User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2006-10-06 19:12:46', 'batch'),
('xample', 'x_pers_type', 'revised_date', '5', 'Revised Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2006-10-06 19:12:46', 'batch'),
('xample', 'x_pers_type', 'revised_user', '6', 'Revised User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:06', 'AJM', '2006-10-06 19:12:46', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'xample', 'x_person', '0', NULL, NULL, 'Links X_PERS_TYPE to X_PERSON', NULL, 'RES', NULL, 'pers_type_desc', NULL, '2005-10-29 20:02:28', 'AJM', '2006-09-16 11:54:53', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_pers_type', 'pers_type_id', 'xample', 'x_person', '0', 'pers_type_id', '1', '2005-10-29 20:02:28', 'AJM', '2006-08-22 16:05:58', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'x_person', NULL, 'Y', 'person_id', '2005-10-01 18:03:28', 'AJM', '2005-10-30 16:46:16', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'nat_ins_no', 'nat_ins_no', '1', 'Y', '1', '2005-10-02 16:02:22', 'AJM', NULL, NULL),
('xample', 'x_person', 'pers_type_id', 'pers_type_id', '1', 'N', '2', '2005-10-02 16:02:22', 'AJM', NULL, NULL),
('xample', 'x_person', 'PRIMARY', 'person_id', '1', 'Y', '0', '2005-10-02 16:02:22', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'person_id', '1', 'Person Id', NULL, 'varchar', 'varchar', NULL, NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:35', 'AJM', '2006-10-06 19:12:36', 'batch'),
('xample', 'x_person', 'pers_type_id', '2', 'Pers Type Id', NULL, 'varchar', 'varchar', NULL, NULL, '6', '6', 'N', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'pers_type_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:35', 'AJM', '2006-10-06 19:12:36', 'batch'),
('xample', 'x_person', 'node_id', '3', 'Node Id', NULL, 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, NULL, 'x_tree_structure(popup)', 'node_desc', NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2007-01-03 22:13:45', 'AJM'),
('xample', 'x_person', 'nat_ins_no', '4', 'Nat Ins No', NULL, 'varchar', 'varchar', NULL, NULL, '10', '10', 'N', 'Y', 'UNI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:36', 'batch'),
('xample', 'x_person', 'first_name', '5', 'First Name', NULL, 'varchar', 'varchar', NULL, NULL, '20', '20', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:37', 'batch'),
('xample', 'x_person', 'last_name', '6', 'Last Name', NULL, 'varchar', 'varchar', NULL, NULL, '30', '30', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:37', 'batch'),
('xample', 'x_person', 'initials', '7', 'Initials', NULL, 'varchar', 'varchar', NULL, NULL, '6', '6', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:37', 'batch'),
('xample', 'x_person', 'star_sign', '8', 'Star Sign', NULL, 'char', 'char', NULL, NULL, '3', '3', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'star_sign', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:37', 'batch'),
('xample', 'x_person', 'email_addr', '9', 'Email Addr', NULL, 'varchar', 'varchar', NULL, NULL, '50', '50', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'email', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:38', 'batch'),
('xample', 'x_person', 'value1', '10', 'Value1', NULL, 'smallint', 'smallint', NULL, NULL, '5', '5', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:38', 'batch'),
('xample', 'x_person', 'value2', '11', 'Value2', NULL, 'decimal', 'decimal', NULL, NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'Y', 'BWZ', '10', '2', '0', '99999999.99', '0', '99999999.99', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:38', 'batch'),
('xample', 'x_person', 'last_addr_no', '12', 'Last Addr No', NULL, 'smallint', 'smallint', NULL, NULL, '4', '4', 'Y', 'N', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:38', 'batch'),
('xample', 'x_person', 'start_date', '13', 'Start Date', NULL, 'date', 'date', NULL, NULL, '12', '12', 'N', 'Y', NULL, '2000-01-01', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:38', 'batch'),
('xample', 'x_person', 'end_date', '14', 'End Date', NULL, 'date', 'date', NULL, NULL, '12', '12', 'Y', 'N', NULL, '9999-12-31', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:39', 'batch'),
('xample', 'x_person', 'picture', '15', 'Picture', NULL, 'varchar', 'varchar', NULL, NULL, '40', '40', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', 'image', '75', '95', 'N', NULL, NULL, 'filepicker', NULL, NULL, 'x_person(filepicker)', NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:39', 'batch'),
('xample', 'x_person', 'favourite_food', '16', 'Favourite Food', NULL, 'set', 'set', NULL, '\'1\', \'2\', \'3\', \'4\', \'5\', \'6\', \'7\', \'8\', \'9\', \'10\'', NULL, NULL, 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multidrop', 'favourite_food', NULL, NULL, NULL, NULL, NULL, NULL, '5', NULL, '2006-08-01 11:49:27', 'AJM', '2007-01-09 17:39:00', 'AJM'),
('xample', 'x_person', 'fckeditor_test', '17', 'Fckeditor Test', NULL, 'text', 'text', NULL, NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, NULL, NULL, '60', '10', NULL, '2006-08-04 18:44:34', 'AJM', '2006-10-06 19:12:39', 'batch'),
('xample', 'x_person', 'created_date', '18', 'Created Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:40', 'batch'),
('xample', 'x_person', 'created_user', '19', 'Created User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:40', 'batch'),
('xample', 'x_person', 'revised_date', '20', 'Revised Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:40', 'batch'),
('xample', 'x_person', 'revised_user', '21', 'Revised User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:03:36', 'AJM', '2006-10-06 19:12:40', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'xample', 'x_pers_opt_xref', '0', NULL, NULL, 'Links X_PERSON to X_PERS_OPT_XREF', NULL, 'RES', NULL, '#calc#', 'CONCAT(first_name, \' \', last_name) AS person_name', '2005-10-29 19:56:26', 'AJM', '2006-08-22 16:05:55', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'person_id', 'xample', 'x_pers_opt_xref', '0', 'person_id', '1', '2005-10-29 19:56:26', 'AJM', '2006-08-22 16:05:55', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'xample', 'x_person_addr', '0', NULL, NULL, 'Links X_PERSON to X_PERSON_ADDR', NULL, 'DEL', 'address_no desc', '#calc#', 'CONCAT(first_name, \' \', last_name) AS person_name', '2005-10-29 17:02:46', 'AJM', '2006-08-22 16:05:52', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person', 'person_id', 'xample', 'x_person_addr', '0', 'person_id', '1', '2005-10-29 17:02:46', 'AJM', '2006-08-22 16:05:52', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person_addr', 'x_person_addr', NULL, 'Y', 'person_id, address_no', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:22', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person_addr', 'PRIMARY', 'person_id', '1', 'Y', '0', '2005-10-02 15:32:32', 'AJM', NULL, NULL),
('xample', 'x_person_addr', 'PRIMARY', 'address_no', '2', 'Y', '1', '2005-10-02 15:32:32', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_person_addr', 'person_id', '1', 'Person Id', NULL, 'varchar', 'varchar', NULL, NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:47', 'AJM', '2006-10-06 19:12:40', 'batch'),
('xample', 'x_person_addr', 'address_no', '2', 'Address No', NULL, 'smallint', 'smallint', NULL, NULL, '4', '4', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:47', 'AJM', '2006-10-06 19:12:41', 'batch'),
('xample', 'x_person_addr', 'telephone_no', '3', 'Telephone No', NULL, 'varchar', 'varchar', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sample.validation.class.inc/sample_validation_class/telephone_no', '2005-10-01 18:00:47', 'AJM', '2006-12-14 11:12:48', 'AJM'),
('xample', 'x_person_addr', 'fax_no', '4', 'Fax No', NULL, 'varchar', 'varchar', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sample.validation.class.inc/sample_validation_class/fax_no', '2005-10-01 18:00:47', 'AJM', '2006-12-14 11:13:03', 'AJM'),
('xample', 'x_person_addr', 'addr_line_1', '5', 'Addr Line 1', NULL, 'varchar', 'varchar', NULL, NULL, '30', '30', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:47', 'AJM', '2006-10-06 19:12:41', 'batch'),
('xample', 'x_person_addr', 'addr_line_2', '6', 'Addr Line 2', NULL, 'varchar', 'varchar', NULL, NULL, '30', '30', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:42', 'batch'),
('xample', 'x_person_addr', 'addr_line_3', '7', 'Addr Line 3', NULL, 'varchar', 'varchar', NULL, NULL, '30', '30', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:42', 'batch'),
('xample', 'x_person_addr', 'town', '8', 'Town', NULL, 'varchar', 'varchar', NULL, NULL, '30', '30', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:42', 'batch'),
('xample', 'x_person_addr', 'county', '9', 'County', NULL, 'varchar', 'varchar', NULL, NULL, '30', '30', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:42', 'batch'),
('xample', 'x_person_addr', 'postcode', '10', 'Postcode', NULL, 'varchar', 'varchar', NULL, NULL, '10', '10', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', 'custom', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sample.validation.class.inc/sample_validation_class/postcode', '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:42', 'batch'),
('xample', 'x_person_addr', 'start_date', '11', 'Start Date', NULL, 'date', 'date', NULL, NULL, '12', '12', 'N', 'Y', NULL, '2000-01-01', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:43', 'batch'),
('xample', 'x_person_addr', 'end_date', '12', 'End Date', NULL, 'date', 'date', NULL, NULL, '12', '12', 'Y', 'N', NULL, '9999-12-31', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'Y', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:43', 'batch'),
('xample', 'x_person_addr', 'created_date', '13', 'Created Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:43', 'batch'),
('xample', 'x_person_addr', 'created_user', '14', 'Created User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:43', 'batch'),
('xample', 'x_person_addr', 'revised_date', '15', 'Revised Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:43', 'batch'),
('xample', 'x_person_addr', 'revised_user', '16', 'Revised User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:00:48', 'AJM', '2006-10-06 19:12:44', 'batch');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'x_tree_level', NULL, 'Y', 'x_tree_level.tree_level_seq', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:40', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'PRIMARY', 'tree_type_id', '1', 'Y', '0', '2005-10-01 18:01:23', 'AJM', NULL, NULL),
('xample', 'x_tree_level', 'PRIMARY', 'tree_level_id', '2', 'Y', '1', '2005-10-01 18:01:23', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'tree_type_id', '1', 'Tree Type Id', NULL, 'varchar', 'varchar', NULL, NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2006-10-06 19:12:47', 'batch'),
('xample', 'x_tree_level', 'tree_level_id', '2', 'Tree Level Id', NULL, 'tinyint', 'tinyint', NULL, NULL, '3', '3', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2006-10-06 19:12:47', 'batch'),
('xample', 'x_tree_level', 'tree_level_seq', '3', 'Tree Level Seq', NULL, 'tinyint', 'tinyint', NULL, NULL, '3', '3', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2006-10-06 19:12:47', 'batch'),
('xample', 'x_tree_level', 'tree_level_desc', '4', 'Tree Level Description', NULL, 'varchar', 'varchar', NULL, NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2007-02-25 14:39:51', 'AJM'),
('xample', 'x_tree_level', 'created_date', '5', 'Created Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2006-10-06 19:12:47', 'batch'),
('xample', 'x_tree_level', 'created_user', '6', 'Created User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2006-10-06 19:12:48', 'batch'),
('xample', 'x_tree_level', 'revised_date', '7', 'Revised Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:22', 'AJM', '2006-10-06 19:12:48', 'batch'),
('xample', 'x_tree_level', 'revised_user', '8', 'Revised User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:23', 'AJM', '2006-10-06 19:12:48', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'xample', 'x_tree_node', '0', NULL, NULL, 'Links X_TREE_LEVEL to X_TREE_NODE', NULL, 'RES', NULL, '#calc#', 'tree_level_seq, tree_level_desc', '2005-10-29 20:06:29', 'AJM', '2006-08-22 16:06:02', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_level', 'tree_level_id', 'xample', 'x_tree_node', '0', 'tree_level_id', '2', '2005-10-29 20:06:29', 'AJM', '2005-12-14 17:55:02', 'AJM'),
('xample', 'x_tree_level', 'tree_type_id', 'xample', 'x_tree_node', '0', 'tree_type_id', '1', '2005-10-29 20:06:29', 'AJM', '2006-08-22 16:06:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'x_tree_node', NULL, 'Y', 'tree_level_id, node_id', '2005-10-01 16:39:56', 'AJM', '2005-10-30 18:49:34', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'node_id_snr', 'node_id_snr', '1', 'N', '3', '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'PRIMARY', 'node_id', '1', 'Y', '0', '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'tree_type_id', 'tree_type_id', '1', 'N', '1', '2005-10-01 18:01:29', 'AJM', NULL, NULL),
('xample', 'x_tree_node', 'tree_type_id', 'tree_level_id', '2', 'N', '2', '2005-10-01 18:01:29', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'node_id', '1', 'Node Id', NULL, 'smallint', 'smallint', NULL, NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:28', 'AJM', '2006-10-06 19:12:48', 'batch'),
('xample', 'x_tree_node', 'tree_type_id', '2', 'Tree Type Id', NULL, 'varchar', 'varchar', NULL, NULL, '8', '8', 'N', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:28', 'AJM', '2006-10-06 19:12:49', 'batch'),
('xample', 'x_tree_node', 'tree_level_id', '3', 'Tree Level Id', NULL, 'tinyint', 'tinyint', NULL, NULL, '3', '3', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2006-10-06 19:12:49', 'batch'),
('xample', 'x_tree_node', 'node_desc', '4', 'Node Description', NULL, 'varchar', 'varchar', NULL, NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2007-02-25 14:40:05', 'AJM'),
('xample', 'x_tree_node', 'node_id_snr', '5', 'Node Id Snr', NULL, 'smallint', 'smallint', NULL, NULL, '5', '5', 'Y', 'N', 'MUL', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2006-10-06 19:12:49', 'batch'),
('xample', 'x_tree_node', 'external_code', '6', 'External Code', NULL, 'varchar', 'varchar', NULL, NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2006-10-06 19:12:49', 'batch'),
('xample', 'x_tree_node', 'created_date', '7', 'Created Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2006-10-06 19:12:50', 'batch'),
('xample', 'x_tree_node', 'created_user', '8', 'Created User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2006-10-06 19:12:50', 'batch'),
('xample', 'x_tree_node', 'revised_date', '9', 'Revised Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2006-10-06 19:12:50', 'batch'),
('xample', 'x_tree_node', 'revised_user', '10', 'Revised User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:29', 'AJM', '2006-10-06 19:12:50', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'xample', 'x_person', '0', NULL, NULL, 'Links X_TREE_NODE to X_PERSON', NULL, 'RES', NULL, 'node_desc', NULL, '2005-10-29 20:04:34', 'AJM', '2006-09-16 11:55:43', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'node_id', 'xample', 'x_person', '0', 'node_id', '1', '2005-10-29 20:04:34', 'AJM', '2006-08-22 16:06:05', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'xample', 'x_tree_node', '0', 'x_tree_node_snr', 'x_tree_node_jnr', 'Links X_TREE_NODE to X_TREE_NODE', NULL, 'RES', NULL, '#calc#', 'node_desc AS node_desc_snr', '2005-10-29 20:08:38', 'AJM', '2006-08-22 16:06:08', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_node', 'node_id', 'xample', 'x_tree_node', '0', 'node_id_snr', '1', '2005-10-29 20:08:38', 'AJM', '2006-08-22 16:06:08', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `tbl_comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'x_tree_type', NULL, 'Y', 'x_tree_type.tree_type_id', '2005-10-01 16:39:56', 'AJM', '2005-10-30 16:46:52', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'PRIMARY', 'tree_type_id', '1', 'Y', '0', '2005-10-01 18:01:37', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `col_comment`, `col_type`, `col_type_native`, `col_array_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `no_search`, `no_audit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `col_subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `checkbox_label`, `task_id`, `foreign_field`, `align_hv`, `align_lr`, `multi_cols`, `multi_rows`, `custom_validation`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'tree_type_id', '1', 'Tree Type Id', NULL, 'varchar', 'varchar', NULL, NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2006-10-06 19:12:51', 'batch'),
('xample', 'x_tree_type', 'tree_type_desc', '2', 'Tree Type Description', NULL, 'varchar', 'varchar', NULL, NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2007-02-25 14:40:14', 'AJM'),
('xample', 'x_tree_type', 'created_date', '3', 'Created Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2006-10-06 19:12:51', 'batch'),
('xample', 'x_tree_type', 'created_user', '4', 'Created User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2006-10-06 19:12:51', 'batch'),
('xample', 'x_tree_type', 'revised_date', '5', 'Revised Date', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2006-10-06 19:12:52', 'batch'),
('xample', 'x_tree_type', 'revised_user', '6', 'Revised User', NULL, 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', 'NSR', NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-01 18:01:37', 'AJM', '2006-10-06 19:12:52', 'batch');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'xample', 'x_tree_level', '0', NULL, NULL, 'Links X_TREE_TYPE to X_TREE_LEVEL', NULL, 'RES', NULL, 'tree_type_desc', NULL, '2005-10-29 20:05:21', 'AJM', '2006-10-24 11:18:06', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'tree_type_id', 'xample', 'x_tree_level', '0', 'tree_type_id', '1', '2005-10-29 20:05:21', 'AJM', '2006-08-22 16:06:11', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `rel_comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'xample', 'x_tree_node', '0', NULL, NULL, 'Links X_TREE_TYPE to X_TREE_NODE', NULL, 'RES', NULL, 'tree_type_desc', NULL, '2005-10-29 20:05:57', 'AJM', '2006-10-24 11:18:13', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('xample', 'x_tree_type', 'tree_type_id', 'xample', 'x_tree_node', '0', 'tree_type_id', '1', '2005-10-29 20:05:57', 'AJM', '2006-08-22 16:06:14', 'AJM');

-- finished
