<?php

// Each entry must be an array of values

$array['conflict_type']         = array(''  => ' ',
                                        'C' => 'Class',
                                        'S' => 'Student',
                                        'T' => 'Teacher');

$array['day_no']                = array('' => ' ',
                                        1  => 'Monday',
                                        2  => 'Tuesday',
                                        3  => 'Wednesday',
                                        4  => 'Thursday',
                                        5  => 'Friday',
                                        6  => 'Saturday',
                                        7  => 'Sunday');

$array['title']                 = array(''     => ' ',
                                        'Mr'   => 'Mr',
                                        'Mrs'  => 'Mrs',
                                        'Ms'   => 'Ms',
                                        'Miss' => 'Miss',
                                        'Dr'   => 'Doctor',
                                        'Prof' => 'Professor',
                                        'Rev'  => 'Reverend');
                                     

return $array;

?>