<?php
// *****************************************************************************
// Copyright 2003-2005 by A J Marston <http://www.tonymarston.net>
// Copyright 2006-2008 by Radicore Software Limited <http://www.radicore.org>
// *****************************************************************************

// name = std.list1.popup.inc

// type = list1 popup

// This will list occurrences from a database table, with a CHOOSE button

// add extra buttons to action bar
$act_buttons['choose']     = 'choose';
$act_buttons['choosenull'] = 'choosenull';

require 'std.list1.inc';                // activate page controller

?>
