<?php
// *****************************************************************************
// Copyright 2003-2006 by A J Marston <http://www.tonymarston.net>
// Licensed to Radicore Software Limited <http://www.radicore.org>
// *****************************************************************************

// name = std.list1.popup.inc

// type = list1 popup

// This will list occurrences from a database table, with a CHOOSE button

// add 'choose' button to action bar
$act_buttons['choose'] = 'CHOOSE';

require 'std.list1.inc';                // activate page controller

?>
