<?php

// Each text string may include parameter substitution - refer to SPRINTF() function

$array['e0001'] = "If field is NOT NULL then 'is required' must be set";
$array['e0002'] = "Invalid unless CONTROL = 'multi-line'";
$array['e0003'] = "If TYPE = 'boolean' CONTROL can only be 'dropdown' or 'radiogroup' or 'checkbox'";
$array['e0004'] = "Invalid unless CONTROL = 'filepicker' or 'image hyperlink";
$array['e0005'] = "Unknown value for 'subtype' (%1\$s)";
$array['e0006'] = "Invalid unless CONTROL = 'image' or SUBTYPE = 'image'";
$array['e0007'] = "Invalid unless CONTROL = 'radio group' or 'multi-checkbox'";
$array['e0008'] = "Invalid unless CONTROL = 'popup'";
$array['e0009'] = "Invalid unless CONTROL = 'popup' or 'filepicker'";

$array['e0010'] = "Invalid unless CONTROL = 'dropdown', 'multi-dropdown', 'radio group' or 'multi-checkbox'";
$array['e0011'] = "Required if CONTROL = 'dropdown', 'multi-dropdown' or 'multi-checkbox'";
$array['e0012'] = "Required if CONTROL = 'radio group'";
$array['e0013'] = "Required if CONTROL = 'multi-line'";
$array['e0014'] = "Required if CONTROL = 'popup'";
$array['e0015'] = "Required if CONTROL = 'file picker'";
$array['e0016'] = "Unknown value for 'control' (%1\$s)";
$array['e0017'] = "Cannot be greater than %1\$s";
$array['e0018'] = "Cannot be less than %1\$s";
$array['e0019'] = "Database and/or Table id is missing - please check selection";

$array['e0020'] = "Invalid unless relation type = 'DELETE'";
$array['e0021'] = "Invalid unless display field = 'CALCULATED'";
$array['e0022'] = "Required if display field = 'CALCULATED'";
$array['e0023'] = "There is no data to insert";
$array['e0024'] = "Exported to %1\$s";
$array['e0025'] = "There are no new database schemas to be imported";
$array['e0026'] = "Nothing exported for %1\$s as it has no columns";
$array['e0027'] = "Value is missing for fieldspec['type']";
$array['e0028'] = "";
$array['e0029'] = "";

$array['e0030'] = "Invalid unless CONTROL = 'radio group', 'checkbox' or 'multi-checkbox'";
$array['e0031'] = "CONTROL cannot be 'checkbox' unless TYPE is 'boolean'";
$array['e0032'] = "Invalid unless CONTROL = 'checkbox'";
$array['e0033'] = "TEXT-ALIGN is invalid for CHECKBOX unless CHECKBOX_LABEL is set";
$array['e0034'] = "CONTROL cannot be 'hyperlink' unless TYPE is 'string'";
$array['e0035'] = "Invalid unless CONTROL = 'multi-line', 'dropdown' or 'dropdown-multi";
$array['e0036'] = "Invalid unless SUBTYPE = 'custom'";
$array['e0037'] = "Required if SUBTYPE = 'custom'";
$array['e0038'] = "Invalid format for CUSTOM_VALIDATION - must be 'file/class/method'";
$array['e0039'] = "This field can only contain a single word";

$array['e0040'] = "This id is already in use";
$array['e0041'] = "A file with this name already exists";
$array['e0042'] = "Script has been generated";
$array['e0043'] = "Table %1\$s is not related to %2\$s";
$array['e0044'] = "Table name '%1\$s' is used more than once, so one must be aliased";
$array['e0045'] = "Alias name must not be the same as the table name";
$array['e0046'] = "";
$array['e0047'] = "";
$array['e0048'] = "";
$array['e0049'] = "SUBSYS_DIR is missing for database '%1\$s'";

$array['e0050'] = "Alternate Language Table must not be the same as this table";
$array['e0051'] = "This table does not exist";
$array['e0052'] = "Primary key of alternate language table must end in 'language_id'";
$array['e0053'] = "Primary key of alternate language table has wrong number of columns";
$array['e0054'] = "Primary keys of the two tables do not match";
$array['e0055'] = "There are no columns which are common in these two tables";
$array['e0056'] = "";
$array['e0057'] = "";
$array['e0058'] = "";
$array['e0059'] = "There are no new tables to be imported";

$array['e0060'] = "Alias name for START_DATE cannot be same as alias name for END_DATE";
$array['e0061'] = "Alias name for END_DATE cannot be same as alias name for START_DATE";
$array['e0062'] = "Alias name cannot be either START_DATE or END_DATE";
$array['e0063'] = "Alias name must be of type DATE or DATETIME";
$array['e0064'] = "";
$array['e0065'] = "";
$array['e0066'] = "";
$array['e0067'] = "";
$array['e0068'] = "";
$array['e0069'] = "";

$array['e0070'] = "CONTROL cannot be 'image hyperlink' unless TYPE is 'string'";
$array['e0071'] = "CONTROL cannot be 'image' unless TYPE is 'string'";
$array['e0072'] = "";
$array['e0073'] = "";
$array['e0074'] = "";
$array['e0075'] = "";
$array['e0076'] = "";
$array['e0077'] = "";
$array['e0078'] = "";
$array['e0079'] = "";

$array['e0080'] = "";
$array['e0081'] = "";
$array['e0082'] = "";
$array['e0083'] = "";
$array['e0084'] = "";
$array['e0085'] = "";
$array['e0086'] = "";
$array['e0087'] = "";
$array['e0088'] = "";
$array['e0089'] = "";

// text entries used in dict_table_s04.class.inc
$array['t0001'] = "Add1, Delete1, Enquire1, Search, Update1, Audit";
$array['t0002'] = "Add2, Delete1, Enquire1, Search, Update1, Audit";
$array['t0003'] = "Add3, Popup, Delete2, Search";
$array['t0004'] = "Add2, Delete1, Enqire1, Search, Update1";
$array['t0005'] = "Search";
$array['t0006'] = "Link %1\$s to selected %2\$s";
$array['t0007'] = "List %1\$s by %2\$s";
$array['t0008'] = "List %1\$s by %2\$s by %3\$s";
$array['t0009'] = "Update2, Popup, Delete3, Search";

$array['t0010'] = "";
$array['t0011'] = "Add2, Delete1";
$array['t0012'] = "Add3, Popup, Delete2";
$array['t0013'] = "";
$array['t0014'] = "";
$array['t0015'] = "";
$array['t0016'] = "";
$array['t0017'] = "";
$array['t0018'] = "";
$array['t0019'] = "";

$array['t0020'] = "Output %1\$s to CSV";
$array['t0021'] = "Output to CSV";
$array['t0022'] = "Output %1\$s to PDF (list view)";
$array['t0023'] = "Output to PDF(L)";
$array['t0024'] = "Output %1\$s to PDF (detail view)";
$array['t0025'] = "Output to PDF(D)";
$array['t0026'] = "Timetable for %1\$s";
$array['t0027'] = "Tree Structure for %1\$s";
$array['t0028'] = "Output %1\$s to PDF (address labels)";
$array['t0029'] = "Address labels";

$array['batch']             = 'batch';
$array['by']                = 'by';
$array['DEFAULT']           = 'DEFAULT';
$array['Link']              = 'Link';
$array['List']              = 'List';
$array['Maintain']          = 'Maintain';
$array['Select/Display']    = 'Select/Display';
$array['Timetable']         = 'Timetable';
$array['Tree Structure']    = 'Tree Structure';

// menu details for subsystem DICT
$array['Columns']                       = 'Columns';
$array['Databases']                     = 'Databases';
$array['Keys']                          = 'Keys';
$array['Relationships']                 = 'Relationships';
$array['Tables']                        = 'Tables';

// task details for subsystem DICT (NOT REQUIRED AS OF VERSION 1.77.0)

// navigation button details for subsystem DICT
$array['Columns']                       = 'Columns';
$array['Databases']                     = 'Databases';
$array['Export to PHP']                 = 'Export to PHP';
$array['Generate PHP']                  = 'Generate PHP';
$array['Import Columns']                = 'Import Columns';
$array['Import Databases']              = 'Import Databases';
$array['Import Tables']                 = 'Import Tables';
$array['Output to PDF(D)']              = 'Output to PDF(D)';
$array['Output to PDF(L)']              = 'Output to PDF(L)';
$array['Relationships (DB)']            = 'Relationships (DB)';
$array['Relationships (Table)']         = 'Relationships (Table)';

// field names for subsystem XXX
$array['']     = '';

// field labels for subsystem DICT
$array['Alias (jnr)']               = 'Alias (jnr)';
$array['Alias (snr)']               = 'Alias (snr)';
$array['Align H/V']                 = 'Align H/V';
$array['Align L/R']                 = 'Align L/R';
$array['Attributes']                = 'Attributes';
$array['Audit Logging?']            = 'Audit Logging?';
$array['Auto Increment?']           = 'Auto Increment?';
$array['Auto Insert']               = 'Auto Insert';
$array['Auto Update']               = 'Auto Update';
$array['Calculated Field']          = 'Calculated Field';
$array['Column Id']                 = 'Column Id';
$array['Column Id (jnr)']           = 'Column Id (jnr)';
$array['Column Id (snr)']           = 'Column Id (snr)';
$array['Column Seq']                = 'Column Seq';
$array['Column Size']               = 'Column Size';
$array['Column Type']               = 'Column Type';
$array['Column Values']             = 'Column Values';
$array['Comments']                  = 'Comments';
$array['Constraint']                = 'Constraint';
$array['Control']                   = 'Control';
$array['Database Id']               = 'Database Id';
$array['Database Id (jnr)']         = 'Database Id (jnr)';
$array['Database Id (snr)']         = 'Database Id (snr)';
$array['Default']                   = 'Default';
$array['Default Sort Seq']          = 'Default Sort Seq';
$array['Directory']                 = 'Directory';
$array['Foreign Field']             = 'Foreign Field';
$array['Image Height']              = 'Image Height';
$array['Image Width']               = 'Image Width';
$array['Infinity Is Null?']         = 'Infinity Is Null?';
$array['Inner Table Name']          = 'Inner Table Name';
$array['Inner Table Alias']         = 'Inner Table Alias';
$array['Insert or Update']          = 'Insert or Update';
$array['Is Unique?']                = 'Is Unique?';
$array['Key?']                      = 'Key?';
$array['Key Name']                  = 'Key Name';
$array['Max. Value']                = 'Max. Value';
$array['Middle Table Name']         = 'Middle Table Name';
$array['Minimum Value']             = 'Minimum Value';
$array['No Audit']                  = 'No Audit';
$array['No Edit/Display']           = 'No Edit/Display';
$array['No Search']                 = 'No Search';
$array['No. of Columns']            = 'No. of Columns';
$array['No. of Rows']               = 'No. of Rows';
$array['Null?']                     = 'Null?';
$array['Order By']                  = 'Order By';
$array['Option List']               = 'Option List';
$array['Outer Table Name']          = 'Outer Table Name';
$array['Parent Field']              = 'Parent Field';
$array['Password?']                 = 'Password?';
$array['Pattern ID']                = 'Pattern ID';
$array['Precision']                 = 'Precision';
$array['Relationship Type']         = 'Relationship Type';
$array['Required?']                 = 'Required?';
$array['Scale']                     = 'Scale';
$array['Screen Structure']          = 'Screen Structure';
$array['Script ID']                 = 'Script ID';
$array['Seq']                       = 'Seq';
$array['Seq in Index']              = 'Seq in Index';
$array['Seq Number']                = 'Seq Number';
$array['Subsystem']                 = 'Subsystem';
$array['Subtype']                   = 'Subtype';
$array['Table Id']                  = 'Table Id';
$array['Table Id (jnr)']            = 'Table Id (jnr)';
$array['Table Id (snr)']            = 'Table Id (snr)';
$array['Table Name']                = 'Table Name';
$array['Task Id']                   = 'Task Id';
$array['Unsigned?']                 = 'Unsigned?';
$array['Upper/Lowercase']           = 'Upper/Lowercase';
$array['ZF/BWZ?']                   = 'ZF/BWZ?';

$array['']     = '';

return $array;

?>