<?php

// Each entry must be an array of values

$array['pswd_change'] = array('AR' => 'At Random',
                              'AL' => "After 'n' logons",
                              'AD' => "After 'n' days");

$array['access_type'] = array('FULL' => 'Full',
                              'NED'  => 'NOEDIT',
                              'NDI'  => 'NODISPLAY');

$array['task_type'] = array('' => ' ',
                            'PROC' => 'Proc',
                            'MENU' => 'Menu');
return $array;

?>