<?php

// Each text string may include parameter substitution - refer to SPRINTF() function

$array['sys0000'] = "You must log in to access this system.";
$array['sys0001'] = "Cannot connect to database '%1\$s'.";
$array['sys0002'] = "A record already exists with this ID.";
$array['sys0003'] = "A record already exists with this key.";
$array['sys0004'] = "%1\$d records were deleted from %2\$s";
$array['sys0005'] = "%1\$d records were inserted into %2\$s";
$array['sys0006'] = "%1\$d records were updated in %2\$s";
$array['sys0007'] = "Could not locate original %1\$s record for updating (%2\$s)";
$array['sys0008'] = "Cannot delete - record still linked to %1\$s table";
$array['sys0009'] = "COMMIT failed!";

$array['sys0010'] = "Unknown relation type: '%1\$s'";
$array['sys0011'] = "Definition of INNER_TABLE is missing";
$array['sys0012'] = "setAction: 2nd parameter is unknown action";
$array['sys0013'] = "Role does not exist.";
$array['sys0014'] = "This task has been assigned to role %1\$s";
$array['sys0015'] = "This task has been assigned to user %1\$s";
$array['sys0016'] = "Unknown integer type: %1\$s";
$array['sys0017'] = "Must not use wildcard character (%%) in primary key";
$array['sys0018'] = "Primary key (%1\$s) is not complete - check selection";
$array['sys0019'] = "Missing 'AND' after 'BETWEEN' in WHERE clause";

$array['sys0020'] = "%1\$s cannot be blank.";
$array['sys0021'] = "%1\$s cannot be greater than %2\$d characters.";
$array['sys0022'] = "Value is not a number";
$array['sys0023'] = "Value is not numeric";
$array['sys0024'] = "Value is below minimum value (%1\$s)";
$array['sys0025'] = "Value is above maximum value (%1\$s)";
$array['sys0026'] = "Specification missing for PRECISION";
$array['sys0027'] = "Value has too many digits";
$array['sys0028'] = "Value cannot be negative";
$array['sys0029'] = "Value is not a whole number";

$array['sys0030'] = "Task '%1\$s' does not exist.";
$array['sys0031'] = "Task '%1\$s' has been disabled.";
$array['sys0032'] = "Access to task '%1\$s' has not been allowed.";
$array['sys0033'] = "*NO PRIMARY KEY HAS BEEN DEFINED*";
$array['sys0034'] = "";
$array['sys0035'] = "DELETESELECTION method has not been defined in class %1\$1";
$array['sys0036'] = "Unknown value for 'type': {%1\$s}";
$array['sys0037'] = "%1\$s: specification for '%2\$s' is invalid";
$array['sys0038'] = "Not allowed in batch mode";
$array['sys0039'] = "Invalid format for e-mail address.";

$array['sys0040'] = "This is not a valid date";
$array['sys0041'] = "This is not a valid time";
$array['sys0042'] = "Month name is invalid";
$array['sys0043'] = "Invalid HOURS";
$array['sys0044'] = "Invalid MINUTES";
$array['sys0045'] = "Invalid SECONDS";
$array['sys0046'] = "Invalid date format: expected 'yyyymmdd'";
$array['sys0047'] = "Invalid date format: expected 'dd-mm-yyyy'";
$array['sys0048'] = "This is not a valid datetime";
$array['sys0049'] = "Invalid date format: expected 'dd-Mmm-yyyy'";

$array['sys0050'] = "No data available to be copied";
$array['sys0051'] = "Data has been copied";
$array['sys0052'] = "task_id is not defined"; // *****
$array['sys0053'] = "FIELDS array for zone '%1\$s' in screen structure file is not indexed by rownum";
$array['sys0054'] = "Node %1\$s does not exist in node array";
$array['sys0055'] = "Cannot write to file %1\$s";
$array['sys0056'] = "File %1\$s cannot be found";
$array['sys0057'] = "File name '%1\$s' does not exist";
$array['sys0058'] = "No subdirectories found for '%1\$s'";
$array['sys0059'] = "Source directory (%1\$s) does not exist";

$array['sys0060'] = "This application has encountered an unrecoverable error";
$array['sys0061'] = "The following has been reported to the administrator:";
$array['sys0062'] = "Uncaught exception fron %1\$s, message = %2\$s";
$array['sys0063'] = "Fatal Error: %1\$s (# %2\$s).";
$array['sys0064'] = "SQL query: %1\$s";
$array['sys0065'] = "Error in line %1\$s of file '%2\$s'.";
$array['sys0066'] = "Script: %1\$s";
$array['sys0067'] = "User Id: %1\$s";
$array['sys0068'] = "Remote Address: %1\$s";
$array['sys0069'] = "Request URI: %1\$s";

$array['sys0070'] = "%1\$s functions are not available.";
$array['sys0071'] = "Could not create %1\$s process.";
$array['sys0072'] = "XSL transformation failed.";
$array['sys0073'] = "Page Stack:";
$array['sys0074'] = "";
$array['sys0075'] = "";
$array['sys0076'] = "Cannot open file %1\$s";
$array['sys0077'] = "Directory '%1\$s' does not exist";
$array['sys0078'] = "Locale is not defined in string '%1\$s'";
$array['sys0079'] = "Cannot set locale to '%1\$s'";

$array['sys0080'] = "Record inserted OK.";
$array['sys0081'] = "Nothing has been selected yet.";
$array['sys0082'] = "No parent has been selected yet.";
$array['sys0083'] = "Nothing selected from popup screen.";
$array['sys0084'] = "Cannot insert where %1\$s";
$array['sys0085'] = "Nothing retrieved from the database.";
$array['sys0086'] = "Press SUBMIT to confirm deletion.";
$array['sys0087'] = "Nothing selected from filepicker screen.";
$array['sys0088'] = "No entries found on %1\$s";
$array['sys0089'] = "Nothing was found matching this profile";

$array['sys0090'] = "Nothing retrieved from database table %1\$s";
$array['sys0091'] = "Update successful.";
$array['sys0092'] = "Record updated OK.";
$array['sys0093'] = "Data exported to %1\$s";
$array['sys0094'] = "Item has been erased";
$array['sys0095'] = "";
$array['sys0096'] = "";
$array['sys0097'] = "";
$array['sys0098'] = "";
$array['sys0099'] = "Help text for '%1\$s'";

$array['sys0100'] = "** SCRAMBLE1 is not same length as SCRAMBLE2 **";
$array['sys0101'] = "No value has been supplied for decryption";
$array['sys0102'] = "Source string contains an invalid character (%1\$s)";
$array['sys0103'] = "No value has been supplied for encryption";
$array['sys0104'] = "No value has been supplied for the encryption key";
$array['sys0105'] = "Key contains an invalid character (%1\$s)";
$array['sys0106'] = "";
$array['sys0107'] = "";
$array['sys0108'] = "";
$array['sys0109'] = "";

$array['sys0110'] = "Name of child field missing in relationship with %1\$s";
$array['sys0111'] = "Press SUBMIT to erase this entry, and ALL child entries, from the database.";
$array['sys0112'] = "Name of parent field missing in relationship with %1\$s";
$array['sys0113'] = "";
$array['sys0114'] = "";
$array['sys0115'] = "";
$array['sys0116'] = "";
$array['sys0117'] = "";
$array['sys0118'] = "";
$array['sys0119'] = "";

$array['sys0120'] = "Upload this file:";
$array['sys0121'] = "Maximum file size is %1\$s bytes";
$array['sys0122'] = "File must be of type '%1\$s'";
$array['sys0123'] = "Destination directory (%1\$s) does not exist";
$array['sys0124'] = "";
$array['sys0125'] = "File is not of correct type";
$array['sys0126'] = "File uploaded into %1\$s";
$array['sys0127'] = "Failed to copy file into specified folder";
$array['sys0128'] = "The uploaded file exceeds the upload_max_filesize directive in php.ini";
$array['sys0129'] = "The uploaded file exceeds %1\$s bytes";

$array['sys0130'] = "The uploaded file was only partially uploaded";
$array['sys0131'] = "No file was uploaded";
$array['sys0132'] = "Temporary folder is missing";
$array['sys0133'] = "Failed to write file to disk";
$array['sys0134'] = "No file specified for download";
$array['sys0135'] = "";
$array['sys0136'] = "";
$array['sys0137'] = "";
$array['sys0138'] = "";
$array['sys0139'] = "";

$array['sys0140'] = "System will be shutting down between %1\$s and %2\$s";
$array['sys0141'] = "System has been shut down. It will be available at %1\$s";
$array['sys0142'] = "";
$array['sys0143'] = "";
$array['sys0144'] = "";
$array['sys0145'] = "";
$array['sys0146'] = "";
$array['sys0147'] = "";
$array['sys0148'] = "";
$array['sys0149'] = "";

$array['sys0150'] = "Enter e-mail address where password is to be sent";
$array['sys0151'] = "E-mail address was not found";
$array['sys0152'] = "Your password has been e-mailed";
$array['sys0153'] = "Here is your password for";
$array['sys0154'] = "";
$array['sys0155'] = "";
$array['sys0156'] = "";
$array['sys0157'] = "Custom validation - File name '%1\$s' does not exist";
$array['sys0158'] = "Custom validation - Class name '%1\$s' does not exist";
$array['sys0159'] = "Custom validation - Method name '%1\$s' does not exist";

$array['sys0160'] = "Report structure has not been defined";
$array['sys0161'] = "Orienation has not been defined in %1\$s";
$array['sys0162'] = "Unts have not been defined in %1\$s";
$array['sys0163'] = "Format has not been defined in %1\$s";
$array['sys0164'] = "";
$array['sys0165'] = "";
$array['sys0166'] = "";
$array['sys0167'] = "";
$array['sys0168'] = "";
$array['sys0169'] = "";

// the following entries are for ACTION buttons
$array['cancel']     = 'CANCEL';
$array['choose']     = 'CHOOSE';
$array['choosenull'] = 'CHOOSE NULL';
$array['clear']      = 'CLEAR';
$array['close']      = 'CLOSE';
$array['collapse']   = 'COLLAPSE';
$array['copy']       = 'COPY';
$array['delete']     = 'DELETE';
$array['expand']     = 'EXPAND';
$array['login']      = 'LOGIN';
$array['paste']      = 'Paste';
$array['quit']       = 'QUIT';
$array['reset']      = 'RESET';
$array['retrieve']   = 'RETRIEVE';
$array['submit']     = 'SUBMIT';
$array['submitnext'] = 'SUBMIT+next';
$array['submitstay'] = 'SUBMIT+stay';

// the following entries are for NAVIGATION buttons
$array['Add']    = 'Add';
$array['Choose'] = 'Choose';
$array['Delete'] = 'Delete';
$array['Erase']  = 'Erase';
$array['Insert'] = 'Insert';
$array['New']    = 'New';
$array['Read']   = 'Read';
$array['Search'] = 'Search';
$array['Update'] = 'Update';

// the following entries are for field LABELS
$array['Count']                 = 'Count';
$array['Created By']            = 'Created By';
$array['Created Date']          = 'Created Date';
$array['Current or Historic']   = 'Current or Historic';
$array['Description']           = 'Description';
$array['End Date']              = 'End Date';
$array['False']                 = 'False';
$array['File Download']         = 'File Download';
$array['Id']                    = 'Id';
$array['ID']                    = 'ID';
$array['Revised By']            = 'Revised By';
$array['Revised Date']          = 'Revised Date';
$array['Select']                = 'Select';
$array['Selected']              = 'Selected';
$array['Seq']                   = 'Seq';
$array['Sequence']              = 'Sequence';
$array['Start Date']            = 'Start Date';
$array['Status']                = 'Status';
$array['True']                  = 'True';
$array['undefined']             = '(undefined)';
$array['Yes']                   = 'Yes';
$array['No']                    = 'No';
$array['Not Applicable']        = 'Not Applicable';

// the following entries are for the days of the week
$array['Monday']                = 'Monday';
$array['Tuesday']               = 'Tuesday';
$array['Wednesday']             = 'Wednesday';
$array['Thursday']              = 'Thursday';
$array['Friday']                = 'Friday';
$array['Saturday']              = 'Saturday';
$array['Sunday']                = 'Sunday';

// the following entries are for the months of the year
$array['January']               = 'January';
$array['February']              = 'February';
$array['March']                 = 'March';
$array['April']                 = 'April';
$array['May']                   = 'May';
$array['June']                  = 'June';
$array['July']                  = 'July';
$array['August']                = 'August';
$array['September']             = 'September';
$array['October']               = 'October';
$array['November']              = 'November';
$array['December']              = 'December';

// the following entries are for pieces of text in the XSL stylesheet
$array['xsl_page']              = 'Page';
$array['xsl_item']              = 'Item';
$array['xsl_of']                = 'of';
$array['xsl_first']             = 'FIRST';
$array['xsl_last']              = 'LAST';
$array['xsl_prev']              = 'PREV';
$array['xsl_next']              = 'NEXT';
$array['xsl_show']              = 'show';
$array['xsl_select_all']        = 'select all';
$array['xsl_unselect_all']      = 'unselect all';
$array['xsl_logout']            = 'logout';
$array['xsl_logout_all']        = 'logout (all)';
$array['xsl_new_session']       = 'new session';
$array['xsl_help']              = 'help';
$array['xsl_page_created']      = 'page created in';
$array['xsl_seconds']           = 'seconds';
$array['xsl_workitems_role']    = 'Workitems for Role';
$array['xsl_workitems_user']    = 'Workitems for User';
$array['xsl_todo_user']         = 'To Do list for User';
$array['xsl_print']             = 'print';
$array['xsl_noprint']           = 'noprint';
$array['xsl_logged_in_as']      = 'You are logged in as:';
$array['xsl_recover_pswd']      = 'recover password';

return $array;

?>