#!/usr/bin/bash

mysql

CREATE DATABASE `audit`    CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE `dict`     CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE `menu`     CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE `workflow` CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE DATABASE `classroom` CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE `product`   CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE `survey`    CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE `xample`    CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `audit`.* TO 'appusr'@'localhost'; 
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `dict`.* TO 'appusr'@'localhost'; 
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `menu`.* TO 'appusr'@'localhost'; 
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `workflow`.* TO 'appusr'@'localhost'; 
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `classroom`.* TO 'appusr'@'localhost'; 
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `product`.* TO 'appusr'@'localhost'; 
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `survey`.* TO 'appusr'@'localhost'; 
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `xample`.* TO 'appusr'@'localhost'; 
FLUSH PRIVILEGES;

quit
