-- file created on January 10, 2006, 6:37 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'classroom', NULL, 'CRSS', '2005-03-27 15:45:32', 'AJM', '2005-03-27 15:47:13', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'crs_class', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'PRIMARY', 'class_id', '1', 'Y', '0', '2005-04-10 20:30:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'class_id', '1', 'class_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:30:51', 'AJM', '2005-10-11 18:14:10', 'AJM'),
('classroom', 'crs_class', 'class_name', '2', 'class_name', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:30:51', 'AJM', '2005-10-11 18:14:10', 'AJM'),
('classroom', 'crs_class', 'year', '3', 'year', NULL, 'decimal', NULL, '2', '2', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, '1', '0', '0', '9', '1', '9', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:30:51', 'AJM', '2005-10-11 18:14:10', 'AJM'),
('classroom', 'crs_class', 'class_notes', '4', 'class_notes', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:30:51', 'AJM', '2005-10-11 18:14:10', 'AJM'),
('classroom', 'crs_class', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:30:51', 'AJM', '2005-10-11 18:14:10', 'AJM'),
('classroom', 'crs_class', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:30:51', 'AJM', '2005-10-11 18:14:11', 'AJM'),
('classroom', 'crs_class', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:30:52', 'AJM', '2005-10-11 18:14:11', 'AJM'),
('classroom', 'crs_class', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:30:52', 'AJM', '2005-10-11 18:14:11', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'classroom', 'crs_class_lesson', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'class_name', NULL, '2005-04-10 20:37:10', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'class_id', 'classroom', 'crs_class_lesson', '0', 'class_id', '2', '2005-04-10 20:37:10', 'AJM', '2005-12-14 17:54:58', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'classroom', 'crs_conflict', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, 'class_name', NULL, '2005-04-10 20:36:39', 'AJM', '2005-04-11 13:51:27', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'class_id', 'classroom', 'crs_conflict', '0', 'class_id', '2', '2005-04-10 20:36:39', 'AJM', '2005-12-14 17:54:58', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'classroom', 'crs_student', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'class_name', NULL, '2005-04-10 20:38:32', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class', 'class_id', 'classroom', 'crs_student', '0', 'class_id', '2', '2005-04-10 20:38:32', 'AJM', '2005-12-14 17:54:58', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class_lesson', 'crs_class_lesson', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class_lesson', 'PRIMARY', 'class_id', '1', 'Y', '0', '2005-04-10 20:31:01', 'AJM', NULL, NULL),
('classroom', 'crs_class_lesson', 'PRIMARY', 'lesson_id', '2', 'Y', '1', '2005-04-10 20:31:01', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_class_lesson', 'class_id', '1', 'class_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:00', 'AJM', '2005-10-11 18:14:59', 'AJM'),
('classroom', 'crs_class_lesson', 'lesson_id', '2', 'lesson_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:00', 'AJM', '2005-10-11 18:14:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_conflict', 'crs_conflict', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_conflict', 'lesson_id', 'lesson_id1', '1', 'N', '1', '2005-04-10 20:31:09', 'AJM', NULL, NULL),
('classroom', 'crs_conflict', 'PRIMARY', 'conflict_id', '1', 'Y', '0', '2005-04-10 20:31:08', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_conflict', 'conflict_id', '1', 'conflict_id', NULL, 'int', NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '4294967295', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:08', 'AJM', '2005-10-11 18:15:09', 'AJM'),
('classroom', 'crs_conflict', 'conflict_type', '2', 'conflict_type', NULL, 'char', NULL, '1', '1', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'conflict_type', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:08', 'AJM', '2005-10-11 18:15:09', 'AJM'),
('classroom', 'crs_conflict', 'teacher_id', '3', 'teacher_id', NULL, 'smallint', NULL, '5', '5', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'teacher_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:08', 'AJM', '2005-10-11 18:15:09', 'AJM'),
('classroom', 'crs_conflict', 'student_id', '4', 'student_id', NULL, 'smallint', NULL, '5', '5', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'crs_student(popup)', 'student_name', NULL, NULL, NULL, '2005-04-10 20:31:08', 'AJM', '2005-10-11 18:15:09', 'AJM'),
('classroom', 'crs_conflict', 'class_id', '5', 'class_id', NULL, 'varchar', NULL, '8', '8', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'class_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:08', 'AJM', '2005-10-11 18:15:09', 'AJM'),
('classroom', 'crs_conflict', 'lesson_id1', '6', 'lesson_id1', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'MUL', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'lesson_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:08', 'AJM', '2005-10-11 18:15:09', 'AJM'),
('classroom', 'crs_conflict', 'lesson_id2', '7', 'lesson_id2', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'lesson_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:08', 'AJM', '2005-10-11 18:15:10', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'crs_lesson', NULL, 'Y', 'lesson_name', '2005-04-10 20:30:42', 'AJM', '2005-04-15 21:44:22', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'PRIMARY', 'lesson_id', '1', 'Y', '0', '2005-04-10 20:31:15', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'lesson_id', '1', 'lesson_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:14', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'lesson_name', '2', 'lesson_name', NULL, 'varchar', NULL, '40', '40', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'lesson_short_name', '3', 'lesson_short_name', NULL, 'varchar', NULL, '30', '30', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'year', '4', 'year', NULL, 'decimal', NULL, '2', '2', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, '1', '0', '0', '9', '1', '9', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'teacher_id', '5', 'teacher_id', NULL, 'smallint', NULL, '5', '5', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'teacher_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'lesson_notes', '6', 'lesson_notes', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'subject_id', '7', 'subject_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'subject_id', NULL, NULL, NULL, NULL, NULL, '2005-07-28 14:07:22', 'AJM', '2005-07-28 14:08:13', 'AJM'),
('classroom', 'crs_lesson', 'created_date', '8', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'created_user', '9', 'created_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'revised_date', '10', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM'),
('classroom', 'crs_lesson', 'revised_user', '11', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:15', 'AJM', '2005-07-28 14:07:22', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'classroom', 'crs_class_lesson', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'lesson_name', NULL, '2005-04-10 20:53:59', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'lesson_id', 'classroom', 'crs_class_lesson', '0', 'lesson_id', '2', '2005-04-10 20:53:59', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'classroom', 'crs_conflict', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, 'lesson_name', NULL, '2005-04-10 20:55:05', 'AJM', '2005-04-11 13:51:33', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'lesson_id', 'classroom', 'crs_conflict', '0', 'lesson_id1', '2', '2005-04-10 20:55:05', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'classroom', 'crs_conflict', '1', NULL, NULL, NULL, NULL, 'DEL', NULL, 'lesson_name', NULL, '2005-04-10 20:55:42', 'AJM', '2005-04-11 13:51:40', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'lesson_id', 'classroom', 'crs_conflict', '1', 'lesson_id2', '2', '2005-04-10 20:55:42', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'classroom', 'crs_schedule', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'lesson_name', NULL, '2005-04-10 20:56:11', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'lesson_id', 'classroom', 'crs_schedule', '0', 'lesson_id', '2', '2005-04-10 20:56:11', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'classroom', 'crs_student_lesson', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'lesson_name', NULL, '2005-04-10 20:54:28', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_lesson', 'lesson_id', 'classroom', 'crs_student_lesson', '0', 'lesson_id', '2', '2005-04-10 20:54:28', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_room', 'crs_room', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_room', 'PRIMARY', 'room_id', '1', 'Y', '0', '2005-04-10 20:31:24', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_room', 'room_id', '1', 'room_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:23', 'AJM', '2005-10-11 18:17:39', 'AJM'),
('classroom', 'crs_room', 'room_desc', '2', 'room_desc', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:23', 'AJM', '2005-10-11 18:17:39', 'AJM'),
('classroom', 'crs_room', 'room_capacity', '3', 'room_capacity', NULL, 'decimal', NULL, '3', '3', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, '2', '0', '0', '99', '0', '99', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:23', 'AJM', '2005-10-11 18:17:39', 'AJM'),
('classroom', 'crs_room', 'room_notes', '4', 'room_notes', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:31:23', 'AJM', '2005-10-11 18:17:39', 'AJM'),
('classroom', 'crs_room', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:23', 'AJM', '2005-10-11 18:17:39', 'AJM'),
('classroom', 'crs_room', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:23', 'AJM', '2005-10-11 18:17:39', 'AJM'),
('classroom', 'crs_room', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:24', 'AJM', '2005-10-11 18:17:39', 'AJM'),
('classroom', 'crs_room', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:24', 'AJM', '2005-10-11 18:17:39', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_room', 'classroom', 'crs_schedule', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'room_desc', NULL, '2005-04-10 20:34:23', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_room', 'room_id', 'classroom', 'crs_schedule', '0', 'room_id', '2', '2005-04-10 20:34:23', 'AJM', '2005-12-14 17:54:58', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_schedule', 'crs_schedule', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_schedule', 'PRIMARY', 'schedule_id', '1', 'Y', '0', '2005-04-10 20:31:30', 'AJM', NULL, NULL),
('classroom', 'crs_schedule', 'PRIMARY', 'seq_no', '2', 'Y', '1', '2005-04-10 20:31:30', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_schedule', 'schedule_id', '1', 'schedule_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'seq_no', '2', 'seq_no', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'room_id', '3', 'room_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'room_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'day_no', '4', 'day_no', NULL, 'decimal', NULL, '1', '2', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, '1', '0', '0', '9', '1', '7', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'start_time', '5', 'start_time', NULL, 'time', NULL, '5', '8', 'N', 'Y', NULL, '00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'end_time', '6', 'end_time', NULL, 'time', NULL, '5', '8', 'N', 'Y', NULL, '00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'lesson_id', '7', 'lesson_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'lesson_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'is_valid', '8', 'is_valid', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'schedule_errors', '9', 'schedule_errors', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'created_date', '10', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:29', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'created_user', '11', 'created_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:30', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'revised_date', '12', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:30', 'AJM', '2005-10-11 18:17:55', 'AJM'),
('classroom', 'crs_schedule', 'revised_user', '13', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:30', 'AJM', '2005-10-11 18:17:55', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_schedule_hdr', 'crs_schedule_hdr', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_schedule_hdr', 'PRIMARY', 'schedule_id', '1', 'Y', '0', '2005-04-10 20:31:37', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_schedule_hdr', 'schedule_id', '1', 'schedule_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'schedule_desc', '2', 'schedule_desc', NULL, 'varchar', NULL, '40', '40', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'schedule_notes', '3', 'schedule_notes', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'is_active', '4', 'is_active', NULL, 'boolean', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'start_time', '5', 'start_time', NULL, 'time', NULL, '8', '8', 'N', 'Y', NULL, '00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'end_time', '6', 'end_time', NULL, 'time', NULL, '8', '8', 'N', 'Y', NULL, '00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'last_day_no', '7', 'last_day_no', NULL, 'decimal', NULL, '1', '2', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, '1', '0', '0', '9', '1', '7', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'created_date', '8', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'created_user', '9', 'created_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'revised_date', '10', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:10', 'AJM'),
('classroom', 'crs_schedule_hdr', 'revised_user', '11', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:37', 'AJM', '2005-10-11 18:18:11', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_schedule_hdr', 'classroom', 'crs_schedule', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'schedule_desc', NULL, '2005-04-10 20:39:17', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_schedule_hdr', 'schedule_id', 'classroom', 'crs_schedule', '0', 'schedule_id', '2', '2005-04-10 20:39:17', 'AJM', '2005-12-14 17:54:58', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student', 'crs_student', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student', 'PRIMARY', 'student_id', '1', 'Y', '0', '2005-04-10 20:31:45', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student', 'student_id', '1', 'student_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:44', 'AJM', '2005-10-11 18:18:24', 'AJM'),
('classroom', 'crs_student', 'first_name', '2', 'first_name', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:44', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'last_name', '3', 'last_name', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:44', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'initials', '4', 'initials', NULL, 'varchar', NULL, '4', '4', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:44', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'year', '5', 'year', NULL, 'decimal', NULL, '2', '2', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, '1', '0', '0', '9', '1', '9', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:44', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'class_id', '6', 'class_id', NULL, 'varchar', NULL, '8', '8', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'class_id', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:44', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'student_notes', '7', 'student_notes', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:31:45', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'created_date', '8', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:45', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'created_user', '9', 'created_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:45', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'revised_date', '10', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:45', 'AJM', '2005-10-11 18:18:25', 'AJM'),
('classroom', 'crs_student', 'revised_user', '11', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:45', 'AJM', '2005-10-11 18:18:25', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student', 'classroom', 'crs_conflict', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, '#calc#', 'CONCAT(last_name, \", \", first_name) AS student_name', '2005-04-10 20:39:55', 'AJM', '2005-04-24 15:46:29', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student', 'student_id', 'classroom', 'crs_conflict', '0', 'student_id', '2', '2005-04-10 20:39:56', 'AJM', '2005-12-14 17:54:58', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student', 'classroom', 'crs_student_lesson', '0', NULL, NULL, NULL, NULL, 'RES', NULL, '#calc#', 'CONCAT(last_name, \", \", first_name) AS student_name', '2005-04-10 20:40:22', 'AJM', '2005-04-24 15:46:53', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student', 'student_id', 'classroom', 'crs_student_lesson', '0', 'student_id', '2', '2005-04-10 20:40:22', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student_lesson', 'crs_student_lesson', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student_lesson', 'PRIMARY', 'student_id', '1', 'Y', '0', '2005-04-10 20:31:51', 'AJM', NULL, NULL),
('classroom', 'crs_student_lesson', 'PRIMARY', 'lesson_id', '2', 'Y', '1', '2005-04-10 20:31:51', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_student_lesson', 'student_id', '1', 'student_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:51', 'AJM', '2005-10-11 18:18:58', 'AJM'),
('classroom', 'crs_student_lesson', 'lesson_id', '2', 'lesson_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:51', 'AJM', '2005-10-11 18:18:58', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_subject', 'crs_subject', NULL, 'Y', 'subject_name', '2005-07-28 12:20:05', 'AJM', '2005-07-28 12:36:37', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_subject', 'PRIMARY', 'subject_id', '1', 'Y', '0', '2005-07-28 12:20:25', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_subject', 'subject_id', '1', 'subject_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-28 12:20:24', 'AJM', '2005-07-28 12:21:30', 'AJM'),
('classroom', 'crs_subject', 'subject_name', '2', 'subject_name', NULL, 'varchar', NULL, '80', '80', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-28 12:20:24', 'AJM', NULL, NULL),
('classroom', 'crs_subject', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-28 12:20:24', 'AJM', '2005-07-28 12:52:14', 'AJM'),
('classroom', 'crs_subject', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-28 12:20:24', 'AJM', '2005-07-28 12:52:22', 'AJM'),
('classroom', 'crs_subject', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-28 12:20:24', 'AJM', '2005-07-28 12:52:28', 'AJM'),
('classroom', 'crs_subject', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-28 12:20:25', 'AJM', '2005-07-28 12:52:34', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_subject', 'classroom', 'crs_lesson', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'subject_name', NULL, '2005-07-28 14:09:00', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_subject', 'subject_id', 'classroom', 'crs_lesson', '0', 'subject_id', '2', '2005-07-28 14:09:00', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_teacher', 'crs_teacher', NULL, 'Y', NULL, '2005-04-10 20:30:42', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_teacher', 'PRIMARY', 'teacher_id', '1', 'Y', '0', '2005-04-10 20:31:57', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_teacher', 'teacher_id', '1', 'teacher_id', NULL, 'smallint', NULL, '5', '5', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:56', 'AJM', '2005-10-11 18:19:14', 'AJM'),
('classroom', 'crs_teacher', 'first_name', '2', 'first_name', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:56', 'AJM', '2005-10-11 18:19:15', 'AJM'),
('classroom', 'crs_teacher', 'last_name', '3', 'last_name', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:56', 'AJM', '2005-10-11 18:19:15', 'AJM'),
('classroom', 'crs_teacher', 'initials', '4', 'initials', NULL, 'varchar', NULL, '4', '4', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:56', 'AJM', '2005-10-11 18:19:15', 'AJM'),
('classroom', 'crs_teacher', 'title', '5', 'title', NULL, 'varchar', NULL, '4', '4', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'title', NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:56', 'AJM', '2005-10-11 18:19:15', 'AJM'),
('classroom', 'crs_teacher', 'teacher_notes', '6', 'teacher_notes', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-04-10 20:31:57', 'AJM', '2005-10-11 18:19:15', 'AJM'),
('classroom', 'crs_teacher', 'created_date', '7', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '0000-00-00 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:57', 'AJM', '2005-10-11 18:19:15', 'AJM'),
('classroom', 'crs_teacher', 'created_user', '8', 'created_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:57', 'AJM', '2005-10-11 18:19:15', 'AJM'),
('classroom', 'crs_teacher', 'revised_date', '9', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:57', 'AJM', '2005-10-11 18:19:15', 'AJM'),
('classroom', 'crs_teacher', 'revised_user', '10', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 20:31:57', 'AJM', '2005-10-11 18:19:15', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_teacher', 'classroom', 'crs_conflict', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, NULL, NULL, '2005-04-10 20:35:54', 'AJM', '2005-04-11 13:51:51', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_teacher', 'teacher_id', 'classroom', 'crs_conflict', '0', 'teacher_id', '2', '2005-04-10 20:35:54', 'AJM', '2005-12-14 17:54:58', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_teacher', 'classroom', 'crs_lesson', '0', NULL, NULL, NULL, NULL, 'NUL', NULL, NULL, NULL, '2005-04-10 20:35:18', 'AJM', '2005-04-11 13:59:06', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('classroom', 'crs_teacher', 'teacher_id', 'classroom', 'crs_lesson', '0', 'teacher_id', '2', '2005-04-10 20:35:18', 'AJM', '2005-12-14 17:54:58', 'AJM');

-- finished
