-- file created on January 10, 2006, 6:37 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'Menu and Security (RBAC) System', 'Author: A J Marston
Date: June, 2003', 'MENU', '2005-03-27 15:45:36', 'AJM', '2005-06-05 14:51:44', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'help_text', 'help_text', NULL, 'Y', 'task_id', '2005-04-07 11:16:02', 'AJM', '2005-04-15 21:36:48', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'help_text', 'PRIMARY', 'task_id', '1', 'Y', '0', '2005-04-07 11:16:36', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'help_text', 'task_id', '1', 'task_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:16:35', 'AJM', '2005-10-11 20:14:01', 'AJM'),
('menu', 'help_text', 'help_text', '2', 'help_text', NULL, 'text', NULL, '65535', '65535', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '15', '2005-04-07 11:16:35', 'AJM', '2005-10-11 20:14:02', 'AJM'),
('menu', 'help_text', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:16:35', 'AJM', '2005-10-30 12:08:49', 'AJM'),
('menu', 'help_text', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:16:35', 'AJM', '2005-10-30 12:08:49', 'AJM'),
('menu', 'help_text', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:16:35', 'AJM', '2005-10-11 20:14:02', 'AJM'),
('menu', 'help_text', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:16:36', 'AJM', '2005-10-11 20:14:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_control', 'mnu_control', NULL, 'Y', 'record_id, field_id', '2005-04-07 11:16:02', 'AJM', '2005-04-15 21:37:17', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_control', 'PRIMARY', 'record_id', '1', 'Y', '0', '2005-04-07 11:30:02', 'AJM', NULL, NULL),
('menu', 'mnu_control', 'PRIMARY', 'field_id', '2', 'Y', '1', '2005-04-07 11:30:02', 'AJM', '2005-04-10 18:16:24', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_control', 'record_id', '1', 'record_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:30:01', 'AJM', '2005-10-11 20:14:09', 'AJM'),
('menu', 'mnu_control', 'field_id', '2', 'field_id', NULL, 'varchar', NULL, '32', '32', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:30:01', 'AJM', '2005-10-11 20:14:09', 'AJM'),
('menu', 'mnu_control', 'field_value', '3', 'field_value', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:30:01', 'AJM', '2005-10-11 20:14:09', 'AJM'),
('menu', 'mnu_control', 'created_date', '4', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:30:01', 'AJM', '2005-10-30 12:10:31', 'AJM'),
('menu', 'mnu_control', 'created_user', '5', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:30:02', 'AJM', '2005-10-30 12:10:31', 'AJM'),
('menu', 'mnu_control', 'revised_date', '6', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:30:02', 'AJM', '2005-10-11 20:14:09', 'AJM'),
('menu', 'mnu_control', 'revised_user', '7', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:30:02', 'AJM', '2005-10-11 20:14:09', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_dialog_type', 'mnu_dialog_type', NULL, 'Y', 'dialog_type_id', '2005-04-07 11:16:02', 'AJM', '2005-12-26 17:20:27', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_dialog_type', 'PRIMARY', 'dialog_type_id', '1', 'Y', '0', '2005-04-07 11:34:31', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_dialog_type', 'dialog_type_id', '1', 'dialog_type_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:30', 'AJM', '2005-10-11 20:14:16', 'AJM'),
('menu', 'mnu_dialog_type', 'dialog_type_desc', '2', 'dialog_type_desc', NULL, 'varchar', NULL, '60', '60', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:30', 'AJM', '2005-10-11 20:14:16', 'AJM'),
('menu', 'mnu_dialog_type', 'dialog_type_long_desc', '3', 'dialog_type_long_desc', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '50', '5', '2005-04-07 11:34:30', 'AJM', '2005-10-11 20:14:16', 'AJM'),
('menu', 'mnu_dialog_type', 'visible_screen', '4', 'visible_screen', NULL, 'boolean', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:30', 'AJM', '2005-10-11 20:14:16', 'AJM'),
('menu', 'mnu_dialog_type', 'context_preselect', '5', 'context_preselect', NULL, 'boolean', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:30', 'AJM', '2005-10-11 20:14:16', 'AJM'),
('menu', 'mnu_dialog_type', 'keep_data', '6', 'context_preselect', NULL, 'boolean', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:30', 'AJM', '2005-10-11 20:14:17', 'AJM'),
('menu', 'mnu_dialog_type', 'created_date', '7', 'context_preselect', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:30', 'AJM', '2005-10-30 12:11:43', 'AJM'),
('menu', 'mnu_dialog_type', 'created_user', '8', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:30', 'AJM', '2005-10-30 12:11:43', 'AJM'),
('menu', 'mnu_dialog_type', 'revised_date', '9', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:31', 'AJM', '2005-10-11 20:14:17', 'AJM'),
('menu', 'mnu_dialog_type', 'revised_user', '10', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:34:31', 'AJM', '2005-10-11 20:14:17', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_dialog_type', 'menu', 'mnu_task', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'dialog_type_desc', NULL, '2005-04-07 11:45:12', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_dialog_type', 'dialog_type_id', 'menu', 'mnu_task', '0', 'dialog_type_id', '2', '2005-04-07 11:45:12', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_menu', 'mnu_menu', NULL, 'Y', 'sort_seq', '2005-04-07 11:16:02', 'AJM', '2005-04-15 21:37:57', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_menu', 'PRIMARY', 'menu_id', '1', 'Y', '0', '2005-04-07 12:08:08', 'AJM', NULL, NULL),
('menu', 'mnu_menu', 'PRIMARY', 'task_id_jnr', '2', 'Y', '1', '2005-04-07 12:08:08', 'AJM', '2005-04-10 18:16:50', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_menu', 'menu_id', '1', 'menu_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:08:08', 'AJM', '2005-10-11 20:14:55', 'AJM'),
('menu', 'mnu_menu', 'task_id_jnr', '2', 'task_id_jnr', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:08:08', 'AJM', '2005-10-11 20:14:55', 'AJM'),
('menu', 'mnu_menu', 'sort_seq', '3', 'sort_seq', NULL, 'tinyint', NULL, '3', '3', 'N', 'Y', NULL, '000', 'N', 'Y', 'ZF', NULL, NULL, '0', '255', '0', '255', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:08:08', 'AJM', '2005-07-17 16:13:26', 'AJM'),
('menu', 'mnu_menu', 'button_text', '4', 'button_text', NULL, 'varchar', NULL, '40', '40', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:08:08', 'AJM', '2005-10-11 20:14:55', 'AJM'),
('menu', 'mnu_menu', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:08:08', 'AJM', '2005-10-30 12:11:51', 'AJM'),
('menu', 'mnu_menu', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:08:08', 'AJM', '2005-10-30 12:11:51', 'AJM'),
('menu', 'mnu_menu', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:08:08', 'AJM', '2005-10-11 20:14:56', 'AJM'),
('menu', 'mnu_menu', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:08:08', 'AJM', '2005-10-11 20:14:56', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_nav_button', 'mnu_nav_button', NULL, 'Y', 'sort_seq', '2005-04-07 11:16:02', 'AJM', '2005-04-15 21:38:20', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_nav_button', 'PRIMARY', 'task_id_snr', '1', 'Y', '0', '2005-04-07 12:17:29', 'AJM', NULL, NULL),
('menu', 'mnu_nav_button', 'PRIMARY', 'task_id_jnr', '2', 'Y', '1', '2005-04-07 12:17:30', 'AJM', '2005-04-10 18:17:01', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_nav_button', 'task_id_snr', '1', 'task_id_snr', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-10-11 20:15:03', 'AJM'),
('menu', 'mnu_nav_button', 'task_id_jnr', '2', 'task_id_jnr', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-10-11 20:15:03', 'AJM'),
('menu', 'mnu_nav_button', 'sort_seq', '3', 'sort_seq', NULL, 'tinyint', NULL, '3', '3', 'N', 'Y', NULL, '000', 'N', 'Y', 'ZF', NULL, NULL, '0', '255', '0', '255', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-07-17 16:14:02', 'AJM'),
('menu', 'mnu_nav_button', 'button_text', '4', 'button_text', NULL, 'varchar', NULL, '40', '40', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-10-11 20:15:03', 'AJM'),
('menu', 'mnu_nav_button', 'context_preselect', '5', 'context_preselect', NULL, 'boolean', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-10-11 20:15:03', 'AJM'),
('menu', 'mnu_nav_button', 'created_date', '6', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-10-30 12:11:58', 'AJM'),
('menu', 'mnu_nav_button', 'created_user', '7', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-10-30 12:11:58', 'AJM'),
('menu', 'mnu_nav_button', 'revised_date', '8', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-10-11 20:15:03', 'AJM'),
('menu', 'mnu_nav_button', 'revised_user', '9', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:17:29', 'AJM', '2005-10-11 20:15:03', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'mnu_role', NULL, 'Y', 'role_id', '2005-04-07 11:16:02', 'AJM', '2005-09-12 18:28:58', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'PRIMARY', 'role_id', '1', 'Y', '0', '2005-04-07 12:30:05', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'role_id', '1', 'role_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:04', 'AJM', '2005-10-11 20:15:11', 'AJM'),
('menu', 'mnu_role', 'role_desc', '2', 'role_desc', NULL, 'varchar', NULL, '30', '30', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:05', 'AJM', '2005-10-11 20:15:11', 'AJM'),
('menu', 'mnu_role', 'start_task_id', '3', 'start_task_id', NULL, 'varchar', NULL, '40', '40', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'mnu_task(popup)b', 'task_desc', NULL, NULL, NULL, '2005-04-07 12:30:05', 'AJM', '2005-10-11 20:15:12', 'AJM'),
('menu', 'mnu_role', 'global_access', '4', 'global_access', NULL, 'boolean', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:05', 'AJM', '2005-10-11 20:15:12', 'AJM'),
('menu', 'mnu_role', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:05', 'AJM', '2005-10-30 12:12:05', 'AJM'),
('menu', 'mnu_role', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:05', 'AJM', '2005-10-30 12:12:05', 'AJM'),
('menu', 'mnu_role', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:05', 'AJM', '2005-10-11 20:15:12', 'AJM'),
('menu', 'mnu_role', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:05', 'AJM', '2005-10-11 20:15:12', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'menu', 'mnu_role_task', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'role_desc', NULL, '2005-04-07 12:52:52', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'role_id', 'menu', 'mnu_role_task', '0', 'role_id', '2', '2005-04-07 12:52:52', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'menu', 'mnu_role_taskfield', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'role_desc', NULL, '2005-04-07 12:53:23', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'role_id', 'menu', 'mnu_role_taskfield', '0', 'role_id', '2', '2005-04-07 12:53:23', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'menu', 'mnu_user', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'role_desc', NULL, '2005-04-07 12:53:44', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'role_id', 'menu', 'mnu_user', '0', 'role_id', '2', '2005-04-07 12:53:44', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'workflow', 'wf_transition', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'role_desc', NULL, '2005-04-24 17:41:44', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'role_id', 'workflow', 'wf_transition', '0', 'role_id', '2', '2005-04-24 17:41:44', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'workflow', 'wf_workitem', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'role_desc', NULL, '2005-04-24 17:41:00', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role', 'role_id', 'workflow', 'wf_workitem', '0', 'role_id', '2', '2005-04-24 17:41:00', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role_task', 'mnu_role_task', NULL, 'Y', NULL, '2005-04-07 11:16:02', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role_task', 'PRIMARY', 'role_id', '1', 'Y', '0', '2005-04-07 12:30:37', 'AJM', NULL, NULL),
('menu', 'mnu_role_task', 'PRIMARY', 'task_id', '2', 'Y', '1', '2005-04-07 12:30:37', 'AJM', '2005-04-10 18:17:22', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role_task', 'role_id', '1', 'role_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:37', 'AJM', '2005-10-11 20:15:20', 'AJM'),
('menu', 'mnu_role_task', 'task_id', '2', 'task_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:37', 'AJM', '2005-10-11 20:15:20', 'AJM'),
('menu', 'mnu_role_task', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:37', 'AJM', '2005-10-30 12:12:12', 'AJM'),
('menu', 'mnu_role_task', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:37', 'AJM', '2005-10-30 12:12:12', 'AJM'),
('menu', 'mnu_role_task', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:37', 'AJM', '2005-10-11 20:15:21', 'AJM'),
('menu', 'mnu_role_task', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:37', 'AJM', '2005-10-11 20:15:21', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role_task', 'menu', 'mnu_role_taskfield', '0', NULL, NULL, NULL, NULL, 'RES', NULL, NULL, NULL, '2005-04-09 15:31:28', 'AJM', '2005-04-09 15:40:44', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role_task', 'role_id', 'menu', 'mnu_role_taskfield', '0', 'role_id', '2', '2005-04-09 15:31:28', 'AJM', '2005-12-14 17:54:59', 'AJM'),
('menu', 'mnu_role_task', 'task_id', 'menu', 'mnu_role_taskfield', '0', 'task_id', '2', '2005-04-09 15:31:28', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role_taskfield', 'mnu_role_taskfield', NULL, 'Y', NULL, '2005-04-07 11:16:02', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role_taskfield', 'PRIMARY', 'role_id', '1', 'Y', '0', '2005-04-07 12:31:02', 'AJM', NULL, NULL),
('menu', 'mnu_role_taskfield', 'PRIMARY', 'task_id', '2', 'Y', '1', '2005-04-07 12:31:02', 'AJM', '2005-04-10 18:17:30', 'AJM'),
('menu', 'mnu_role_taskfield', 'PRIMARY', 'field_id', '3', 'Y', '2', '2005-04-07 12:31:02', 'AJM', '2005-04-10 18:17:30', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_role_taskfield', 'role_id', '1', 'role_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:01', 'AJM', '2005-10-11 20:15:29', 'AJM'),
('menu', 'mnu_role_taskfield', 'task_id', '2', 'task_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:01', 'AJM', '2005-10-11 20:15:29', 'AJM'),
('menu', 'mnu_role_taskfield', 'field_id', '3', 'field_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:01', 'AJM', '2005-10-11 20:15:29', 'AJM'),
('menu', 'mnu_role_taskfield', 'access_type', '4', 'access_type', NULL, 'varchar', NULL, '4', '4', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'access_type', NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:01', 'AJM', '2005-10-11 20:15:29', 'AJM'),
('menu', 'mnu_role_taskfield', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:01', 'AJM', '2005-10-30 12:12:20', 'AJM'),
('menu', 'mnu_role_taskfield', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:01', 'AJM', '2005-10-30 12:12:20', 'AJM'),
('menu', 'mnu_role_taskfield', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:01', 'AJM', '2005-10-11 20:15:30', 'AJM'),
('menu', 'mnu_role_taskfield', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:01', 'AJM', '2005-10-11 20:15:30', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_subsystem', 'mnu_subsystem', NULL, 'Y', 'subsys_id', '2005-04-07 11:16:02', 'AJM', '2005-09-12 18:26:49', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_subsystem', 'PRIMARY', 'subsys_id', '1', 'Y', '0', '2005-04-07 12:31:17', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_subsystem', 'subsys_id', '1', 'subsys_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:16', 'AJM', '2005-10-11 20:15:36', 'AJM'),
('menu', 'mnu_subsystem', 'subsys_desc', '2', 'subsys_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:16', 'AJM', '2005-10-11 20:15:36', 'AJM'),
('menu', 'mnu_subsystem', 'subsys_dir', '3', 'subsys_dir', NULL, 'varchar', NULL, '255', '255', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:16', 'AJM', '2005-10-11 20:15:36', 'AJM'),
('menu', 'mnu_subsystem', 'created_date', '4', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:16', 'AJM', '2005-10-30 12:12:28', 'AJM'),
('menu', 'mnu_subsystem', 'created_user', '5', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:16', 'AJM', '2005-10-30 12:12:29', 'AJM'),
('menu', 'mnu_subsystem', 'revised_date', '6', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:16', 'AJM', '2005-10-11 20:15:36', 'AJM'),
('menu', 'mnu_subsystem', 'revised_user', '7', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:16', 'AJM', '2005-10-11 20:15:36', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_subsystem', 'dict', 'dict_database', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'subsys_desc', NULL, '2005-04-07 14:16:14', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_subsystem', 'subsys_id', 'dict', 'dict_database', '0', 'subsys_id', '2', '2005-04-07 14:16:14', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_subsystem', 'menu', 'mnu_task', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'subsys_desc', NULL, '2005-04-07 14:12:49', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_subsystem', 'subsys_id', 'menu', 'mnu_task', '0', 'subsys_id', '2', '2005-04-07 14:12:49', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'mnu_task', NULL, 'Y', 'task_id', '2005-04-07 11:16:02', 'AJM', '2005-07-31 15:18:47', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'dialog_type_id', 'dialog_type_id', '1', 'N', '1', '2005-04-07 11:54:48', 'AJM', '2005-04-10 18:17:51', 'AJM'),
('menu', 'mnu_task', 'PRIMARY', 'task_id', '1', 'Y', '0', '2005-04-07 11:54:48', 'AJM', NULL, NULL),
('menu', 'mnu_task', 'subsys_id', 'subsys_id', '1', 'N', '2', '2005-04-07 11:54:48', 'AJM', '2005-04-10 18:17:53', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', '1', 'task_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:47', 'AJM', '2005-10-11 20:15:46', 'AJM'),
('menu', 'mnu_task', 'task_desc', '2', 'task_desc', NULL, 'varchar', NULL, '50', '50', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:47', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'button_text', '3', 'button_text', NULL, 'varchar', NULL, '40', '40', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:47', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'task_type', '4', 'task_type', NULL, 'varchar', NULL, '4', '4', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'task_type', NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:47', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'script_id', '5', 'script_id', NULL, 'varchar', NULL, '40', '40', 'Y', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:47', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'is_disabled', '6', 'is_disabled', NULL, 'boolean', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:47', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'dialog_type_id', '7', 'dialog_type_id', NULL, 'varchar', NULL, '16', '16', 'Y', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'dialog_type_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:47', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'subsys_id', '8', 'subsys_id', NULL, 'varchar', NULL, '8', '8', 'Y', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'subsys_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:47', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'initial_passthru', '9', 'initial_passthru', NULL, 'varchar', NULL, '40', '40', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'selection_fixed', '10', 'selection_fixed', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'selection_temp', '11', 'selection_temp', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'settings', '12', 'settings', NULL, 'varchar', NULL, '40', '40', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'order_by', '13', 'order_by', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'keep_data', '14', 'keep_data', NULL, 'boolean', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'created_date', '15', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-30 12:12:38', 'AJM'),
('menu', 'mnu_task', 'created_user', '16', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-30 12:12:38', 'AJM'),
('menu', 'mnu_task', 'revised_date', '17', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-11 20:15:47', 'AJM'),
('menu', 'mnu_task', 'revised_user', '18', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 11:54:48', 'AJM', '2005-10-11 20:15:47', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'dict', 'dict_column', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-07 14:29:13', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'dict', 'dict_column', '0', 'task_id', '2', '2005-04-07 14:29:13', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'help_text', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-07 14:25:01', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'help_text', '0', 'task_id', '2', '2005-04-07 14:25:01', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_menu', '0', 'mnu_task_snr', NULL, NULL, NULL, 'RES', NULL, '#calc#', 'task_desc AS task_desc_snr', '2005-04-07 12:12:45', 'AJM', '2005-06-16 17:24:25', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_menu', '0', 'menu_id', '2', '2005-04-07 12:12:45', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_menu', '1', 'mnu_task_jnr', NULL, NULL, NULL, 'RES', NULL, '#calc#', 'task_desc AS task_desc_jnr', '2005-04-07 16:35:01', 'AJM', '2005-06-16 17:24:43', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_menu', '1', 'task_id_jnr', '2', '2005-04-07 16:35:01', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_nav_button', '0', 'mnu_task_snr', NULL, NULL, NULL, 'RES', NULL, '#calc#', 'task_desc AS task_desc_snr', '2005-04-07 12:20:34', 'AJM', '2005-05-02 10:31:38', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_nav_button', '0', 'task_id_snr', '2', '2005-04-07 12:20:34', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_nav_button', '1', 'mnu_task_jnr', NULL, NULL, NULL, 'RES', NULL, '#calc#', 'task_desc AS task_desc_jnr', '2005-04-07 16:36:30', 'AJM', '2005-05-02 10:31:08', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_nav_button', '1', 'task_id_jnr', '2', '2005-04-07 16:36:30', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_role', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-24 16:09:09', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_role', '0', 'start_task_id', '2', '2005-04-24 16:09:09', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_role_task', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-07 14:22:43', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_role_task', '0', 'task_id', '2', '2005-04-07 14:22:43', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_role_taskfield', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-07 14:24:33', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_role_taskfield', '0', 'task_id', '2', '2005-04-07 14:24:33', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_task', '0', NULL, NULL, NULL, NULL, 'RES', NULL, NULL, NULL, '2005-04-23 15:11:30', 'AJM', '2005-04-23 15:13:08', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_task', '0', 'initial_passthru', '2', '2005-04-23 15:11:30', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'menu', 'mnu_task_field', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-07 14:24:00', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'menu', 'mnu_task_field', '0', 'task_id', '2', '2005-04-07 14:24:00', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'workflow', 'wf_transition', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-22 19:55:13', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'workflow', 'wf_transition', '0', 'task_id', '2', '2005-04-22 19:55:13', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'workflow', 'wf_workflow', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-22 19:54:19', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'workflow', 'wf_workflow', '0', 'start_task_id', '2', '2005-04-22 19:54:19', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'workflow', 'wf_workitem', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'task_desc', NULL, '2005-04-22 19:54:48', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task', 'task_id', 'workflow', 'wf_workitem', '0', 'task_id', '2', '2005-04-22 19:54:49', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task_field', 'mnu_task_field', NULL, 'Y', NULL, '2005-04-07 11:16:02', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task_field', 'PRIMARY', 'task_id', '1', 'Y', '0', '2005-04-07 12:31:22', 'AJM', NULL, NULL),
('menu', 'mnu_task_field', 'PRIMARY', 'field_id', '2', 'Y', '1', '2005-04-07 12:31:22', 'AJM', '2005-04-10 18:18:09', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task_field', 'task_id', '1', 'task_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:22', 'AJM', '2005-10-11 20:16:01', 'AJM'),
('menu', 'mnu_task_field', 'field_id', '2', 'field_id', NULL, 'varchar', NULL, '40', '40', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:22', 'AJM', '2005-10-11 20:16:01', 'AJM'),
('menu', 'mnu_task_field', 'created_date', '3', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:22', 'AJM', '2005-10-30 12:12:47', 'AJM'),
('menu', 'mnu_task_field', 'created_user', '4', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:22', 'AJM', '2005-10-30 12:12:47', 'AJM'),
('menu', 'mnu_task_field', 'revised_date', '5', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:22', 'AJM', '2005-10-11 20:16:01', 'AJM'),
('menu', 'mnu_task_field', 'revised_user', '6', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:31:22', 'AJM', '2005-10-11 20:16:01', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task_field', 'menu', 'mnu_role_taskfield', '0', NULL, NULL, NULL, NULL, 'RES', NULL, NULL, NULL, '2005-04-09 15:33:14', 'AJM', '2005-04-09 15:40:26', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_task_field', 'field_id', 'menu', 'mnu_role_taskfield', '0', 'field_id', '2', '2005-04-09 15:33:14', 'AJM', '2005-12-14 17:55:00', 'AJM'),
('menu', 'mnu_task_field', 'task_id', 'menu', 'mnu_role_taskfield', '0', 'task_id', '2', '2005-04-09 15:33:14', 'AJM', '2005-12-14 17:55:00', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_todo', 'mnu_todo', NULL, 'N', 'user_id, due_date, seq_no', '2005-07-30 15:22:48', 'AJM', '2005-07-30 20:23:31', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_todo', 'PRIMARY', 'user_id', '1', 'Y', '0', '2005-07-30 15:22:57', 'AJM', NULL, NULL),
('menu', 'mnu_todo', 'PRIMARY', 'seq_no', '2', 'Y', '1', '2005-07-30 15:22:58', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_todo', 'user_id', '1', 'user_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'user_id', NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', '2005-07-30 15:51:10', 'AJM'),
('menu', 'mnu_todo', 'seq_no', '2', 'seq_no', NULL, 'smallint', NULL, '10', '10', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', 'NSR', NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', '2005-07-30 18:48:10', 'AJM'),
('menu', 'mnu_todo', 'item_desc', '3', 'item_desc', NULL, 'varchar', NULL, '80', '80', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', NULL, NULL),
('menu', 'mnu_todo', 'item_notes', '4', 'item_notes', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '70', '5', '2005-07-30 15:22:57', 'AJM', '2005-07-30 18:27:08', 'AJM'),
('menu', 'mnu_todo', 'due_date', '5', 'due_date', NULL, 'date', NULL, '12', '12', 'N', 'Y', NULL, '0000-00-00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', '2005-07-30 18:43:36', 'AJM'),
('menu', 'mnu_todo', 'is_complete', '6', 'is_complete', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', '2005-07-30 15:55:20', 'AJM'),
('menu', 'mnu_todo', 'created_date', '7', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', '2005-10-30 12:12:54', 'AJM'),
('menu', 'mnu_todo', 'created_user', '8', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', '2005-10-30 12:12:54', 'AJM'),
('menu', 'mnu_todo', 'revised_date', '9', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', '2005-07-30 15:56:16', 'AJM'),
('menu', 'mnu_todo', 'revised_user', '10', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 15:22:57', 'AJM', '2005-07-30 15:56:27', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'mnu_user', NULL, 'Y', NULL, '2005-04-07 11:16:02', 'AJM', NULL, NULL);

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'PRIMARY', 'user_id', '1', 'Y', '0', '2005-04-07 12:30:49', 'AJM', NULL, NULL),
('menu', 'mnu_user', 'role_id', 'role_id', '1', 'N', '1', '2005-04-07 12:30:49', 'AJM', '2005-04-10 18:18:23', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'user_id', '1', 'user_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:48', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'user_name', '2', 'user_name', NULL, 'varchar', NULL, '30', '30', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:48', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'user_password', '3', 'user_password', NULL, 'varchar', NULL, '16', '40', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NSR', 'NAL', NULL, 'Y', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:48', 'AJM', '2005-12-14 18:14:22', 'AJM'),
('menu', 'mnu_user', 'role_id', '4', 'role_id', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'role_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:48', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'pswd_chg_date', '5', 'pswd_chg_date', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:48', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'pswd_chg_time', '6', 'pswd_chg_time', NULL, 'time', NULL, '8', '8', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:48', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'pswd_count', '7', 'pswd_count', NULL, 'smallint', NULL, '6', '6', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'in_use', '8', 'in_use', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'is_disabled', '9', 'is_disabled', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'logon_date', '10', 'logon_date', NULL, 'date', NULL, '12', '12', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'logon_time', '11', 'logon_time', NULL, 'time', NULL, '8', '8', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'language_code', '12', 'language_code', NULL, 'varchar', NULL, '6', '6', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'language_code', NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-11-08 17:58:17', 'AJM'),
('menu', 'mnu_user', 'created_date', '13', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-30 12:13:03', 'AJM'),
('menu', 'mnu_user', 'created_user', '14', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-30 12:13:03', 'AJM'),
('menu', 'mnu_user', 'revised_date', '15', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-11 20:16:20', 'AJM'),
('menu', 'mnu_user', 'revised_user', '16', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 12:30:49', 'AJM', '2005-10-11 20:16:20', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'menu', 'mnu_todo', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'user_name', NULL, '2005-07-30 15:24:56', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'user_id', 'menu', 'mnu_todo', '0', 'user_id', '2', '2005-07-30 15:24:56', 'AJM', '2005-12-14 17:55:03', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'survey', 'survey_answer_hdr', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'user_name', NULL, '2005-04-24 17:39:11', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'user_id', 'survey', 'survey_answer_hdr', '0', 'user_id', '2', '2005-04-24 17:39:11', 'AJM', '2005-12-14 17:55:02', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'workflow', 'wf_workitem', '0', NULL, NULL, NULL, NULL, 'RES', NULL, 'user_name', NULL, '2005-04-24 17:39:46', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('menu', 'mnu_user', 'user_id', 'workflow', 'wf_workitem', '0', 'user_id', '2', '2005-04-24 17:39:46', 'AJM', '2005-12-14 17:55:02', 'AJM');

-- finished
