-- file created on June 24, 2015, 2:51 pm
    
REPLACE INTO `mnu_subsystem` (`subsys_id`, `subsys_desc`, `subsys_dir`, `task_prefix`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('MISC', 'Miscellaneous Tasks', 'menu', NULL, '2004-04-17 17:12:15', 'AJM', NULL, NULL);

REPLACE INTO `mnu_task` (`task_id`, `task_desc`, `button_text`, `task_type`, `script_id`, `is_disabled`, `pattern_id`, `subsys_id`, `initial_passthru`, `selection_fixed`, `selection_temp`, `settings`, `order_by`, `keep_data`, `log_sql_query`, `screen_refresh`, `use_https`, `max_execution_time`, `task_id_run_at_end`, `task_id_run_at_cancel`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('batch_log(filedownload)', 'Download Batch Log File', 'Batch Log Files', 'PROC', 'batch_log_filedownload.php', 'N', 'FILEDOWNLOAD', 'MISC', NULL, NULL, NULL, 'hyperlink_direct=Y', NULL, 'N', 'N', NULL, 'N', NULL, NULL, NULL, '2008-11-21 11:42:41', 'AJM', '2009-08-25 16:36:16', 'AJM');

REPLACE INTO `mnu_task` (`task_id`, `task_desc`, `button_text`, `task_type`, `script_id`, `is_disabled`, `pattern_id`, `subsys_id`, `initial_passthru`, `selection_fixed`, `selection_temp`, `settings`, `order_by`, `keep_data`, `log_sql_query`, `screen_refresh`, `use_https`, `max_execution_time`, `task_id_run_at_end`, `task_id_run_at_cancel`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('batch_log(filepicker)', 'Show Batch Log File', 'Batch Log Files', 'PROC', 'batch_log_filepicker.php', 'N', 'FILEPICKER', 'MISC', NULL, NULL, NULL, 'download=FALSE', 'date desc', 'N', 'N', '10', 'N', NULL, NULL, NULL, '2008-11-21 12:09:14', 'AJM', '2015-04-14 14:51:03', 'AJM');

REPLACE INTO `mnu_task` (`task_id`, `task_desc`, `button_text`, `task_type`, `script_id`, `is_disabled`, `pattern_id`, `subsys_id`, `initial_passthru`, `selection_fixed`, `selection_temp`, `settings`, `order_by`, `keep_data`, `log_sql_query`, `screen_refresh`, `use_https`, `max_execution_time`, `task_id_run_at_end`, `task_id_run_at_cancel`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('date(current)', 'Select Records with Current Dates', 'Current', 'PROC', 'date_current.php', 'N', 'OTHER', 'MISC', NULL, NULL, NULL, NULL, NULL, 'N', 'N', NULL, 'N', NULL, NULL, NULL, '2004-04-17 17:14:09', 'AJM', '2008-02-01 14:30:06', 'AJM');

REPLACE INTO `mnu_task` (`task_id`, `task_desc`, `button_text`, `task_type`, `script_id`, `is_disabled`, `pattern_id`, `subsys_id`, `initial_passthru`, `selection_fixed`, `selection_temp`, `settings`, `order_by`, `keep_data`, `log_sql_query`, `screen_refresh`, `use_https`, `max_execution_time`, `task_id_run_at_end`, `task_id_run_at_cancel`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('date(future)', 'Select Records with Future Dates', 'Future', 'PROC', 'date_future.php', 'N', 'OTHER', 'MISC', NULL, NULL, NULL, NULL, NULL, 'N', 'N', NULL, 'N', NULL, NULL, NULL, '2004-04-17 17:15:38', 'AJM', '2008-02-01 14:30:15', 'AJM');

REPLACE INTO `mnu_task` (`task_id`, `task_desc`, `button_text`, `task_type`, `script_id`, `is_disabled`, `pattern_id`, `subsys_id`, `initial_passthru`, `selection_fixed`, `selection_temp`, `settings`, `order_by`, `keep_data`, `log_sql_query`, `screen_refresh`, `use_https`, `max_execution_time`, `task_id_run_at_end`, `task_id_run_at_cancel`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('date(historic)', 'Select Records with Historic Dates', 'Historic', 'PROC', 'date_historic.php', 'N', 'OTHER', 'MISC', NULL, NULL, NULL, NULL, NULL, 'N', 'N', NULL, 'N', NULL, NULL, NULL, '2004-04-17 17:15:01', 'AJM', '2008-02-01 14:30:25', 'AJM');

REPLACE INTO `mnu_task` (`task_id`, `task_desc`, `button_text`, `task_type`, `script_id`, `is_disabled`, `pattern_id`, `subsys_id`, `initial_passthru`, `selection_fixed`, `selection_temp`, `settings`, `order_by`, `keep_data`, `log_sql_query`, `screen_refresh`, `use_https`, `max_execution_time`, `task_id_run_at_end`, `task_id_run_at_cancel`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('file(delete)', 'Delete File Name', 'Delete', 'PROC', 'file(delete).php', 'N', 'DEL2', 'MISC', NULL, NULL, NULL, NULL, NULL, 'N', 'N', NULL, 'N', NULL, NULL, NULL, '2008-11-24 16:33:57', 'AJM', NULL, NULL);

REPLACE INTO `mnu_task` (`task_id`, `task_desc`, `button_text`, `task_type`, `script_id`, `is_disabled`, `pattern_id`, `subsys_id`, `initial_passthru`, `selection_fixed`, `selection_temp`, `settings`, `order_by`, `keep_data`, `log_sql_query`, `screen_refresh`, `use_https`, `max_execution_time`, `task_id_run_at_end`, `task_id_run_at_cancel`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('file(search)', 'Search File Name', 'Search', 'PROC', 'file(search).php', 'N', 'SRCH', 'MISC', NULL, NULL, NULL, NULL, NULL, 'N', 'N', NULL, 'N', NULL, NULL, NULL, '2008-11-22 16:19:22', 'AJM', '2008-11-22 23:06:30', 'AJM');

REPLACE INTO `mnu_task` (`task_id`, `task_desc`, `button_text`, `task_type`, `script_id`, `is_disabled`, `pattern_id`, `subsys_id`, `initial_passthru`, `selection_fixed`, `selection_temp`, `settings`, `order_by`, `keep_data`, `log_sql_query`, `screen_refresh`, `use_https`, `max_execution_time`, `task_id_run_at_end`, `task_id_run_at_cancel`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES ('directory(up)', 'Go up a Directory in a Filepicker screen', 'Up Directory', 'PROC', 'directory_up.php', 'N', 'OTHER', 'MISC', NULL, NULL, NULL, NULL, NULL, 'N', 'N', NULL, 'N', NULL, NULL, NULL, '2015-06-23 17:18:59', 'AJM', NULL, NULL);

-- finished
