-- file created on January 10, 2006, 6:37 pm

REPLACE INTO `dict_database` (`database_id`, `database_desc`, `comment`, `subsys_id`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'Data Dictionary', NULL, 'DICT', '2005-03-27 15:45:34', 'AJM', '2005-05-09 19:48:23', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_column', 'dict_column', NULL, 'Y', 'database_id, table_id, column_seq', '2005-04-07 14:14:05', 'AJM', '2005-04-17 10:53:47', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_column', 'PRIMARY', 'database_id', '1', 'Y', '0', '2005-04-07 14:14:27', 'AJM', NULL, NULL),
('dict', 'dict_column', 'PRIMARY', 'table_id', '2', 'Y', '1', '2005-04-07 14:14:27', 'AJM', '2005-04-10 15:16:34', 'AJM'),
('dict', 'dict_column', 'PRIMARY', 'column_id', '3', 'Y', '2', '2005-04-07 14:14:27', 'AJM', '2005-04-10 15:16:34', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_column', 'database_id', '1', 'database_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'database_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'table_id', '2', 'table_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'dict_table(popup)', 'table_desc', NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'column_id', '3', 'column_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'column_seq', '4', 'column_seq', NULL, 'smallint', NULL, '6', '6', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', 'NSR', NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'column_desc', '5', 'column_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'comment', '6', 'comment', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NSR', NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '65', '5', '2005-05-09 19:53:03', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'col_type', '7', 'col_type', NULL, 'varchar', NULL, '12', '12', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'col_type', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'col_values', '8', 'col_values', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'user_size', '9', 'user_size', NULL, 'bigint', NULL, '20', '20', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '1.844674407371e+019', '0', '1.844674407371e+019', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-11 18:56:37', 'AJM', '2005-10-30 11:52:44', 'AJM'),
('dict', 'dict_column', 'col_maxsize', '10', 'col_maxsize', NULL, 'bigint', NULL, '20', '20', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '1.844674407371e+019', '0', '1.844674407371e+019', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-08 12:15:30', 'AJM', '2005-10-30 11:52:25', 'AJM'),
('dict', 'dict_column', 'col_null', '11', 'col_null', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'Y', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'col_null', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-20 17:49:19', 'AJM'),
('dict', 'dict_column', 'is_required', '12', 'is_required', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'is_required', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'col_key', '13', 'col_key', NULL, 'char', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'col_key', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:24', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'col_default', '14', 'col_default', NULL, 'varchar', NULL, '40', '40', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'col_auto_increment', '15', 'col_auto_increment', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'col_auto_increment', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'col_unsigned', '16', 'col_unsigned', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'col_unsigned', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-07-17 15:54:25', 'AJM'),
('dict', 'dict_column', 'col_zerofill_bwz', '17', 'col_zerofill_bwz', NULL, 'char', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'col_zerofill_bwz', NULL, NULL, NULL, NULL, NULL, '2005-07-17 15:54:25', 'AJM', '2005-07-17 15:56:18', 'AJM'),
('dict', 'dict_column', 'col_precision', '18', 'col_precision', NULL, 'tinyint', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '32', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-07-17 15:54:26', 'AJM'),
('dict', 'dict_column', 'col_scale', '19', 'col_scale', NULL, 'tinyint', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '32', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-07-17 15:54:26', 'AJM'),
('dict', 'dict_column', 'col_minvalue', '20', 'col_minvalue', NULL, 'double', NULL, '21', '21', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-12-26 17:21:10', 'AJM'),
('dict', 'dict_column', 'col_maxvalue', '21', 'col_maxvalue', NULL, 'double', NULL, '20', '21', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-10-30 11:42:36', 'AJM'),
('dict', 'dict_column', 'user_minvalue', '22', 'user_minvalue', NULL, 'double', NULL, '21', '21', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-11 18:56:37', 'AJM', '2005-12-26 17:21:45', 'AJM'),
('dict', 'dict_column', 'user_maxvalue', '23', 'user_maxvalue', NULL, 'double', NULL, '20', '21', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-10-11 18:56:37', 'AJM', '2005-10-30 11:42:36', 'AJM'),
('dict', 'dict_column', 'noedit_nodisplay', '24', 'noedit_nodisplay', NULL, 'char', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'noedit_nodisplay', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-07-17 15:54:26', 'AJM'),
('dict', 'dict_column', 'nosearch', '25', 'nosearch', NULL, 'char', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'nosearch', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-07-17 15:54:26', 'AJM'),
('dict', 'dict_column', 'noaudit', '26', 'noaudit', NULL, 'char', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'noaudit', NULL, NULL, NULL, NULL, NULL, '2005-12-14 17:54:50', 'AJM', '2005-12-14 18:06:48', 'AJM'),
('dict', 'dict_column', 'upper_lowercase', '27', 'upper_lowercase', NULL, 'varchar', NULL, '5', '5', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'upper_lowercase', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'is_password', '28', 'is_password', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'is_password', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:25', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'auto_insert', '29', 'auto_insert', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'auto_insert', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'auto_update', '30', 'auto_update', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'auto_update', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'infinityisnull', '31', 'infinityisnull', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'infinityisnull', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'subtype', '32', 'subtype', NULL, 'varchar', NULL, '10', '10', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'subtype', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'image_width', '33', 'image_width', NULL, 'smallint', NULL, '6', '6', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'image_height', '34', 'image_height', NULL, 'smallint', NULL, '5', '5', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'is_boolean', '35', 'is_boolean', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 15:16:29', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'boolean_true', '36', 'boolean_true', NULL, 'varchar', NULL, '4', '4', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-08 12:15:30', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'boolean_false', '37', 'boolean_false', NULL, 'varchar', NULL, '4', '4', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-08 12:15:30', 'AJM', '2005-12-14 17:54:52', 'AJM'),
('dict', 'dict_column', 'control', '38', 'control', NULL, 'varchar', NULL, '10', '10', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'control', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'optionlist', '39', 'optionlist', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'task_id', '40', 'task_id', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'mnu_task(popup)a', 'task_desc', NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'foreign_field', '41', 'foreign_field', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:26', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'align_hv', '42', 'align_hv', NULL, 'char', NULL, '1', '1', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'align_hv', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:27', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'multi_cols', '43', 'multi_cols', NULL, 'tinyint', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '127', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:27', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'multi_rows', '44', 'multi_rows', NULL, 'tinyint', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '127', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:27', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'created_date', '45', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:27', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'created_user', '46', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:27', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'revised_date', '47', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:27', 'AJM', '2005-12-14 17:54:53', 'AJM'),
('dict', 'dict_column', 'revised_user', '48', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:27', 'AJM', '2005-12-14 17:54:53', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_column', 'dict', 'dict_related_column', '0', 'dict_column_snr', 'dict_related_column_snr', NULL, NULL, 'RES', NULL, '#calc#', 'column_desc AS column_desc_snr', '2005-05-30 11:43:08', 'AJM', '2005-05-30 11:49:58', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_column', 'column_id', 'dict', 'dict_related_column', '0', 'column_id_snr', '2', '2005-05-30 11:43:08', 'AJM', '2005-12-14 17:55:03', 'AJM'),
('dict', 'dict_column', 'database_id', 'dict', 'dict_related_column', '0', 'database_id_snr', '2', '2005-05-30 11:43:08', 'AJM', '2005-12-14 17:55:03', 'AJM'),
('dict', 'dict_column', 'table_id', 'dict', 'dict_related_column', '0', 'table_id_snr', '2', '2005-05-30 11:43:08', 'AJM', '2005-12-14 17:55:03', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_column', 'dict', 'dict_related_column', '1', 'dict_column_jnr', 'dict_related_column_jnr', NULL, NULL, 'RES', NULL, '#calc#', 'column_desc AS column_desc_jnr', '2005-05-30 11:44:15', 'AJM', '2005-05-30 11:50:11', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_column', 'column_id', 'dict', 'dict_related_column', '1', 'column_id_jnr', '2', '2005-05-30 11:44:15', 'AJM', '2005-12-14 17:55:03', 'AJM'),
('dict', 'dict_column', 'database_id', 'dict', 'dict_related_column', '1', 'database_id_jnr', '2', '2005-05-30 11:44:15', 'AJM', '2005-12-14 17:55:03', 'AJM'),
('dict', 'dict_column', 'table_id', 'dict', 'dict_related_column', '1', 'table_id_jnr', '2', '2005-05-30 11:44:15', 'AJM', '2005-12-14 17:55:03', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_database', 'dict_database', NULL, 'Y', NULL, '2005-04-07 14:14:05', 'AJM', '2005-04-17 10:53:50', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_database', 'PRIMARY', 'database_id', '1', 'Y', '0', '2005-04-07 14:14:38', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_database', 'database_id', '1', 'database_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'database_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:38', 'AJM', '2005-10-11 18:58:14', 'AJM'),
('dict', 'dict_database', 'database_desc', '2', 'database_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:38', 'AJM', '2005-10-11 18:58:14', 'AJM'),
('dict', 'dict_database', 'comment', '3', 'comment', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NSR', NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '65', '5', '2005-05-09 19:45:36', 'AJM', '2005-10-11 18:58:14', 'AJM'),
('dict', 'dict_database', 'subsys_id', '4', 'subsys_id', NULL, 'varchar', NULL, '8', '8', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'subsys_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:38', 'AJM', '2005-10-11 18:58:14', 'AJM'),
('dict', 'dict_database', 'created_date', '5', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:38', 'AJM', '2005-10-30 11:59:55', 'AJM'),
('dict', 'dict_database', 'created_user', '6', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:38', 'AJM', '2005-10-30 11:59:55', 'AJM'),
('dict', 'dict_database', 'revised_date', '7', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:38', 'AJM', '2005-10-11 18:58:14', 'AJM'),
('dict', 'dict_database', 'revised_user', '8', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:38', 'AJM', '2005-10-11 18:58:14', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_database', 'dict', 'dict_table', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, 'database_desc', NULL, '2005-04-07 17:06:31', 'AJM', '2005-04-14 19:04:15', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_database', 'database_id', 'dict', 'dict_table', '0', 'database_id', '2', '2005-04-07 17:06:31', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_related_column', 'dict_related_column', NULL, 'Y', 'seq_in_index', '2005-04-07 14:14:05', 'AJM', '2005-04-17 10:53:54', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_related_column', 'PRIMARY', 'database_id_snr', '1', 'Y', '0', '2005-04-07 14:14:48', 'AJM', NULL, NULL),
('dict', 'dict_related_column', 'PRIMARY', 'table_id_snr', '2', 'Y', '1', '2005-04-07 14:14:48', 'AJM', '2005-04-10 17:35:44', 'AJM'),
('dict', 'dict_related_column', 'PRIMARY', 'column_id_snr', '3', 'Y', '2', '2005-04-07 14:14:48', 'AJM', '2005-04-10 17:35:44', 'AJM'),
('dict', 'dict_related_column', 'PRIMARY', 'database_id_jnr', '4', 'Y', '3', '2005-04-07 14:14:48', 'AJM', '2005-04-10 17:35:44', 'AJM'),
('dict', 'dict_related_column', 'PRIMARY', 'table_id_jnr', '5', 'Y', '4', '2005-04-07 14:14:48', 'AJM', '2005-04-10 17:35:44', 'AJM'),
('dict', 'dict_related_column', 'PRIMARY', 'seq_no', '6', 'Y', '5', '2005-07-30 12:31:11', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_related_column', 'database_id_snr', '1', 'database_id_snr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-07-30 12:31:11', 'AJM'),
('dict', 'dict_related_column', 'table_id_snr', '2', 'table_id_snr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-07-30 12:31:11', 'AJM'),
('dict', 'dict_related_column', 'column_id_snr', '3', 'column_id_snr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-07-30 12:31:11', 'AJM'),
('dict', 'dict_related_column', 'database_id_jnr', '4', 'database_id_jnr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-07-30 12:31:11', 'AJM'),
('dict', 'dict_related_column', 'table_id_jnr', '5', 'table_id_jnr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-07-30 12:31:11', 'AJM'),
('dict', 'dict_related_column', 'seq_no', '6', 'seq_no', NULL, 'tinyint', NULL, '3', '3', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 12:31:10', 'AJM', NULL, NULL),
('dict', 'dict_related_column', 'column_id_jnr', '7', 'column_id_jnr', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'column_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-07-30 12:31:11', 'AJM'),
('dict', 'dict_related_column', 'seq_in_index', '8', 'seq_in_index', NULL, 'tinyint', NULL, '4', '4', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 17:35:43', 'AJM', '2005-07-30 12:31:11', 'AJM'),
('dict', 'dict_related_column', 'created_date', '9', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-10-30 12:00:04', 'AJM'),
('dict', 'dict_related_column', 'created_user', '10', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-10-30 12:00:04', 'AJM'),
('dict', 'dict_related_column', 'revised_date', '11', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:47', 'AJM', '2005-07-30 12:31:11', 'AJM'),
('dict', 'dict_related_column', 'revised_user', '12', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:48', 'AJM', '2005-07-30 12:31:11', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_relationship', 'dict_relationship', NULL, 'Y', NULL, '2005-04-07 14:14:05', 'AJM', '2005-04-17 10:53:57', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_relationship', 'PRIMARY', 'database_id_snr', '1', 'Y', '0', '2005-04-07 14:14:54', 'AJM', NULL, NULL),
('dict', 'dict_relationship', 'PRIMARY', 'table_id_snr', '2', 'Y', '1', '2005-04-07 14:14:54', 'AJM', '2005-04-10 17:36:52', 'AJM'),
('dict', 'dict_relationship', 'PRIMARY', 'database_id_jnr', '3', 'Y', '2', '2005-04-07 14:14:54', 'AJM', '2005-04-10 17:36:52', 'AJM'),
('dict', 'dict_relationship', 'PRIMARY', 'table_id_jnr', '4', 'Y', '3', '2005-04-07 14:14:54', 'AJM', '2005-04-10 17:36:52', 'AJM'),
('dict', 'dict_relationship', 'PRIMARY', 'seq_no', '5', 'Y', '4', '2005-07-30 12:30:05', 'AJM', NULL, NULL);

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_relationship', 'database_id_snr', '1', 'database_id_snr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'database_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:53', 'AJM', '2005-07-30 12:30:04', 'AJM'),
('dict', 'dict_relationship', 'table_id_snr', '2', 'table_id_snr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'dict_table(popup)snr', 'table_id_snr', NULL, NULL, NULL, '2005-04-07 14:14:53', 'AJM', '2005-07-30 12:30:04', 'AJM'),
('dict', 'dict_relationship', 'database_id_jnr', '3', 'database_id_jnr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'database_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:53', 'AJM', '2005-07-30 12:30:04', 'AJM'),
('dict', 'dict_relationship', 'table_id_jnr', '4', 'table_id_jnr', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'popup', NULL, 'dict_table(popup)', 'table_id_jnr', NULL, NULL, NULL, '2005-04-07 14:14:53', 'AJM', '2005-07-30 12:30:04', 'AJM'),
('dict', 'dict_relationship', 'seq_no', '5', 'seq_no', NULL, 'tinyint', NULL, '3', '3', 'N', 'Y', 'PRI', '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-07-30 12:30:04', 'AJM', NULL, NULL),
('dict', 'dict_relationship', 'table_alias_snr', '6', 'table_alias_snr', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-05-02 09:32:08', 'AJM', '2005-07-30 12:30:04', 'AJM'),
('dict', 'dict_relationship', 'table_alias_jnr', '7', 'table_alias_jnr', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-05-02 09:32:08', 'AJM', '2005-07-30 12:30:05', 'AJM'),
('dict', 'dict_relationship', 'relation_desc', '8', 'relation_desc', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-05-09 19:54:41', 'AJM', '2005-07-30 12:30:05', 'AJM'),
('dict', 'dict_relationship', 'comment', '9', 'comment', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NSR', NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '65', '5', '2005-05-09 19:54:41', 'AJM', '2005-07-30 12:30:05', 'AJM'),
('dict', 'dict_relationship', 'rel_type', '10', 'rel_type', NULL, 'char', NULL, '3', '3', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'rel_type', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:54', 'AJM', '2005-07-30 12:30:05', 'AJM'),
('dict', 'dict_relationship', 'orderby', '11', 'orderby', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:54', 'AJM', '2005-07-30 12:30:05', 'AJM'),
('dict', 'dict_relationship', 'parent_field', '12', 'parent_field', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'parent_field', NULL, NULL, NULL, NULL, NULL, '2005-04-24 14:46:02', 'AJM', '2005-07-30 12:30:05', 'AJM'),
('dict', 'dict_relationship', 'calc_field', '13', 'calc_field', NULL, 'varchar', NULL, '255', '255', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:54', 'AJM', '2005-07-30 12:30:05', 'AJM'),
('dict', 'dict_relationship', 'created_date', '14', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:54', 'AJM', '2005-10-30 12:00:17', 'AJM'),
('dict', 'dict_relationship', 'created_user', '15', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:54', 'AJM', '2005-10-30 12:00:17', 'AJM'),
('dict', 'dict_relationship', 'revised_date', '16', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:54', 'AJM', '2005-07-30 12:30:05', 'AJM'),
('dict', 'dict_relationship', 'revised_user', '17', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:14:54', 'AJM', '2005-07-30 12:30:05', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_relationship', 'dict', 'dict_related_column', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, NULL, NULL, '2005-04-10 17:49:05', 'AJM', NULL, NULL);

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_relationship', 'database_id_jnr', 'dict', 'dict_related_column', '0', 'database_id_jnr', '2', '2005-04-10 17:49:05', 'AJM', '2005-12-14 17:54:59', 'AJM'),
('dict', 'dict_relationship', 'database_id_snr', 'dict', 'dict_related_column', '0', 'database_id_snr', '2', '2005-04-10 17:49:05', 'AJM', '2005-12-14 17:54:59', 'AJM'),
('dict', 'dict_relationship', 'seq_no', 'dict', 'dict_related_column', '0', 'seq_no', '2', '2005-07-30 12:30:05', 'AJM', '2005-12-14 17:55:03', 'AJM'),
('dict', 'dict_relationship', 'table_id_jnr', 'dict', 'dict_related_column', '0', 'table_id_jnr', '2', '2005-04-10 17:49:05', 'AJM', '2005-12-14 17:54:59', 'AJM'),
('dict', 'dict_relationship', 'table_id_snr', 'dict', 'dict_related_column', '0', 'table_id_snr', '2', '2005-04-10 17:49:05', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'dict_table', NULL, 'Y', NULL, '2005-04-07 14:14:05', 'AJM', '2005-04-24 11:13:10', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'PRIMARY', 'database_id', '1', 'Y', '0', '2005-04-07 14:15:01', 'AJM', NULL, NULL),
('dict', 'dict_table', 'PRIMARY', 'table_id', '2', 'Y', '1', '2005-04-07 14:15:01', 'AJM', '2005-04-10 17:37:46', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'database_id', '1', 'database_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'database_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:00', 'AJM', '2005-10-11 18:58:48', 'AJM'),
('dict', 'dict_table', 'table_id', '2', 'table_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:00', 'AJM', '2005-10-11 18:58:48', 'AJM'),
('dict', 'dict_table', 'table_desc', '3', 'table_desc', NULL, 'varchar', NULL, '255', '255', 'N', 'Y', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:00', 'AJM', '2005-10-11 18:58:48', 'AJM'),
('dict', 'dict_table', 'comment', '4', 'comment', NULL, 'text', NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NSR', NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'multiline', NULL, NULL, NULL, NULL, '65', '5', '2005-05-09 19:48:37', 'AJM', '2005-10-11 18:58:48', 'AJM'),
('dict', 'dict_table', 'audit_logging', '5', 'audit_logging', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'Y', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', 'dropdown', 'audit_logging', NULL, NULL, NULL, NULL, NULL, '2005-04-17 10:47:40', 'AJM', '2005-10-11 18:58:48', 'AJM'),
('dict', 'dict_table', 'default_orderby', '6', 'default_orderby', NULL, 'varchar', NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-14 22:11:44', 'AJM', '2005-10-11 18:58:48', 'AJM'),
('dict', 'dict_table', 'created_date', '7', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:00', 'AJM', '2005-10-30 12:00:31', 'AJM'),
('dict', 'dict_table', 'created_user', '8', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:00', 'AJM', '2005-10-30 12:00:31', 'AJM'),
('dict', 'dict_table', 'revised_date', '9', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:00', 'AJM', '2005-10-11 18:58:48', 'AJM'),
('dict', 'dict_table', 'revised_user', '10', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:01', 'AJM', '2005-10-11 18:58:48', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'dict', 'dict_column', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, 'table_desc', NULL, '2005-04-07 17:10:47', 'AJM', '2005-04-10 23:20:04', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'database_id', 'dict', 'dict_column', '0', 'database_id', '2', '2005-04-07 17:10:47', 'AJM', '2005-12-14 17:54:59', 'AJM'),
('dict', 'dict_table', 'table_id', 'dict', 'dict_column', '0', 'table_id', '2', '2005-04-07 17:10:48', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'dict', 'dict_relationship', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, '#calc#', 'table_desc as table_desc_snr', '2005-04-07 17:11:48', 'AJM', '2005-04-12 07:05:55', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'database_id', 'dict', 'dict_relationship', '0', 'database_id_snr', '2', '2005-04-07 17:11:48', 'AJM', '2005-12-14 17:54:59', 'AJM'),
('dict', 'dict_table', 'table_id', 'dict', 'dict_relationship', '0', 'table_id_snr', '2', '2005-04-07 17:11:48', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'dict', 'dict_relationship', '1', NULL, NULL, NULL, NULL, 'DEL', NULL, '#calc#', 'table_desc as table_desc_jnr', '2005-04-07 17:12:12', 'AJM', '2005-04-12 07:06:06', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'database_id', 'dict', 'dict_relationship', '1', 'database_id_jnr', '2', '2005-04-07 17:12:12', 'AJM', '2005-12-14 17:54:59', 'AJM'),
('dict', 'dict_table', 'table_id', 'dict', 'dict_relationship', '1', 'table_id_jnr', '2', '2005-04-07 17:12:12', 'AJM', '2005-12-14 17:54:59', 'AJM');

REPLACE INTO `dict_relationship` (`database_id_snr`, `table_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `table_alias_snr`, `table_alias_jnr`, `relation_desc`, `comment`, `rel_type`, `orderby`, `parent_field`, `calc_field`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'dict', 'dict_table_key', '0', NULL, NULL, NULL, NULL, 'DEL', NULL, 'table_desc', NULL, '2005-06-25 17:01:22', 'AJM', '2005-06-26 14:44:41', 'AJM');

REPLACE INTO `dict_related_column` (`database_id_snr`, `table_id_snr`, `column_id_snr`, `database_id_jnr`, `table_id_jnr`, `seq_no`, `column_id_jnr`, `seq_in_index`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table', 'database_id', 'dict', 'dict_table_key', '0', 'database_id', '2', '2005-06-25 17:01:22', 'AJM', '2005-12-14 17:54:59', 'AJM'),
('dict', 'dict_table', 'table_id', 'dict', 'dict_table_key', '0', 'table_id', '2', '2005-06-25 17:01:22', 'AJM', '2005-12-14 17:55:03', 'AJM');

REPLACE INTO `dict_table` (`database_id`, `table_id`, `table_desc`, `comment`, `audit_logging`, `default_orderby`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table_key', 'dict_table_key', NULL, 'Y', NULL, '2005-04-07 14:14:05', 'AJM', '2005-04-17 10:54:04', 'AJM');

REPLACE INTO `dict_table_key` (`database_id`, `table_id`, `key_name`, `column_id`, `seq_in_index`, `is_unique`, `column_seq`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table_key', 'PRIMARY', 'database_id', '1', 'Y', '0', '2005-04-07 14:15:07', 'AJM', NULL, NULL),
('dict', 'dict_table_key', 'PRIMARY', 'table_id', '2', 'Y', '1', '2005-04-07 14:15:07', 'AJM', '2005-04-10 17:37:57', 'AJM'),
('dict', 'dict_table_key', 'PRIMARY', 'key_name', '3', 'Y', '2', '2005-04-07 14:15:07', 'AJM', '2005-04-10 17:37:57', 'AJM'),
('dict', 'dict_table_key', 'PRIMARY', 'column_id', '4', 'Y', '3', '2005-04-09 11:45:48', 'AJM', '2005-04-10 17:37:57', 'AJM');

REPLACE INTO `dict_column` (`database_id`, `table_id`, `column_id`, `column_seq`, `column_desc`, `comment`, `col_type`, `col_values`, `user_size`, `col_maxsize`, `col_null`, `is_required`, `col_key`, `col_default`, `col_auto_increment`, `col_unsigned`, `col_zerofill_bwz`, `col_precision`, `col_scale`, `col_minvalue`, `col_maxvalue`, `user_minvalue`, `user_maxvalue`, `noedit_nodisplay`, `nosearch`, `noaudit`, `upper_lowercase`, `is_password`, `auto_insert`, `auto_update`, `infinityisnull`, `subtype`, `image_width`, `image_height`, `is_boolean`, `boolean_true`, `boolean_false`, `control`, `optionlist`, `task_id`, `foreign_field`, `align_hv`, `multi_cols`, `multi_rows`, `created_date`, `created_user`, `revised_date`, `revised_user`) VALUES 
('dict', 'dict_table_key', 'database_id', '1', 'database_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, 'dropdown', 'database_id', NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:06', 'AJM', '2005-10-11 18:59:36', 'AJM'),
('dict', 'dict_table_key', 'table_id', '2', 'table_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:06', 'AJM', '2005-10-11 18:59:36', 'AJM'),
('dict', 'dict_table_key', 'key_name', '3', 'key_name', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:06', 'AJM', '2005-10-11 18:59:36', 'AJM'),
('dict', 'dict_table_key', 'column_id', '4', 'column_id', NULL, 'varchar', NULL, '64', '64', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:06', 'AJM', '2005-10-11 18:59:36', 'AJM'),
('dict', 'dict_table_key', 'seq_in_index', '5', 'seq_in_index', NULL, 'tinyint', NULL, '3', '3', 'N', 'Y', NULL, '0', 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', 'NED', 'NSR', NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:06', 'AJM', '2005-10-11 18:59:36', 'AJM'),
('dict', 'dict_table_key', 'is_unique', '6', 'is_unique', NULL, 'boolean', NULL, '1', '1', 'N', 'Y', NULL, 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'Y', 'Y', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:06', 'AJM', '2005-10-11 18:59:37', 'AJM'),
('dict', 'dict_table_key', 'column_seq', '7', 'column_seq', NULL, 'tinyint', NULL, '3', '3', 'Y', 'N', NULL, NULL, 'N', 'Y', NULL, NULL, NULL, '0', '255', '0', '255', 'NED', 'NSR', NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-10 17:37:56', 'AJM', '2005-10-11 18:59:37', 'AJM'),
('dict', 'dict_table_key', 'created_date', '8', 'created_date', NULL, 'datetime', NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:06', 'AJM', '2005-10-30 12:00:40', 'AJM'),
('dict', 'dict_table_key', 'created_user', '9', 'created_user', NULL, 'varchar', NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:06', 'AJM', '2005-10-30 12:00:40', 'AJM'),
('dict', 'dict_table_key', 'revised_date', '10', 'revised_date', NULL, 'datetime', NULL, '20', '20', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:07', 'AJM', '2005-10-11 18:59:37', 'AJM'),
('dict', 'dict_table_key', 'revised_user', '11', 'revised_user', NULL, 'varchar', NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'Y', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-07 14:15:07', 'AJM', '2005-10-11 18:59:37', 'AJM');

-- finished
