<?php
// ****************************************************************************
// Copyright 2003-2005 by A J Marston <http://www.tonymarston.net>
// Copyright 2006-2016 by Radicore Software Limited <http://www.radicore.org>
// ****************************************************************************

// link to the standard file in the parent directory

require '../include.batch.inc';

?>
