<?php

// Each text string may include parameter substitution - refer to SPRINTF() function

$array['e0001'] = "Start Date cannot be later than End Date";
$array['e0002'] = "End Date cannot be earlier than Start Date";
$array['e0003'] = "This is the lowest level - no children allowed";
$array['e0004'] = "Cannot be empty";
$array['e0005'] = "Value too large (%1\$s)";
$array['e0006'] = "Must be an integer";
$array['e0007'] = "Must be greater than 0";
$array['e0008'] = "Must not be greater than %1\$s";
$array['e0009'] = "Value has already been used";

$array['e0010'] = "Could not locate first PERS_ADDR record";
$array['e0011'] = "Start Date cannot be later than End Date of first address";
$array['e0012'] = "Could not locate last PERS_ADDR record";
$array['e0013'] = "End Date cannot be earlier than Start Date of last address";
$array['e0014'] = "Could not locate next PERS_ADDR record";
$array['e0015'] = "End Date must be earlier than End Date of next entry";
$array['e0016'] = "Could not locate previous PERS_ADDR record";
$array['e0017'] = "Start Date must be later than Start Date of previous entry";
$array['e0018'] = "Cannot change start date of first address.";
$array['e0019'] = "Cannot change end date of last address.";

$array['e0020'] = "Invalid format for a postcode.";
$array['e0021'] = "Invalid format for a telephone number.";
$array['e0022'] = "Invalid format for a fax number.";
$array['e0023'] = "Could not locate PERSON record.";
$array['e0024'] = "You have not selected an address for deletion.";
$array['e0025'] = "Only the last address can be deleted.";
$array['e0026'] = "";
$array['e0027'] = "";
$array['e0028'] = "";
$array['e0029'] = "";

$array['e0030'] = "";
$array['e0031'] = "";
$array['e0032'] = "";
$array['e0033'] = "";
$array['e0034'] = "";
$array['e0035'] = "";
$array['e0036'] = "";
$array['e0037'] = "";
$array['e0038'] = "";
$array['e0039'] = "";

// these entries are used by 'sample.validation.class.inc'
$array['sample001'] = "Invalid format for a postcode.";
$array['sample002'] = "Invalid format for a telephone number.";
$array['sample003'] = "Invalid format for a fax number.";

// menu details for subsystem XAMPLE
$array['Auto-Increment']                = 'Auto-Increment';
$array['Option']                        = 'Option';
$array['Person']                        = 'Person';
$array['Person Type']                   = 'Person Type';
$array['Tree Type']                     = 'Tree Type';

// task details for subsystem XAMPLE (redundant)


// navigation button details for subsystem XAMPLE (redundant)


// field names for subsystem XAMPLE
$array['person_id']                 = 'Person Id';
$array['first_name']                = 'First Name';
$array['last_name']                 = 'Last Name';
$array['initials']                  = 'Initials';
$array['person_name']               = 'Person Name';
$array['pers_type_id']              = 'Person Type';
$array['pers_type_desc']            = 'Person Type Description';
$array['node_id']                   = 'Node Id';
$array['node_desc']                 = 'Node Description';
$array['nat_ins_no']                = 'Nat Ins No';
$array['star_sign']                 = 'Star Sign';
$array['email_addr']                = 'Email Address';
$array['value1']                    = 'Value1';
$array['value2']                    = 'Value2';
$array['start_date']                = 'Start Date';
$array['end_date']                  = 'End Date';
$array['favourite_food']            = 'Favourite Food';

// field labels for subsystem XAMPLE
$array['Address Line 1']    = 'Address Line 1';
$array['Address Line 2']    = 'Address Line 2';
$array['Address Line 3']    = 'Address Line 3';
$array['Address No']        = 'Address No';
$array['County']            = 'County';
$array['E-mail']            = 'E-mail';
$array['External Code']     = 'External Code';
$array['FAX No']            = 'FAX No';
$array['File Name']         = 'File Name';
$array['First Name']        = 'First Name';
$array['Image']             = 'Image';
$array['Initials']          = 'Initials';
$array['Last Address No']   = 'Last Address No';
$array['Last Name']         = 'Last Name';
$array['Level Description'] = 'Level Description';
$array['Level']             = 'Level';
$array['Nat. Ins. No.']     = 'Nat. Ins. No.';
$array['Node Description']  = 'Node Description';
$array['Node Id']           = 'Node Id';
$array['Node']              = 'Node';
$array['Option']            = 'Option';
$array['Organisation']      = 'Organisation';
$array['Parent Node']       = 'Parent Node';
$array['Parent']            = 'Parent';
$array['Person Type']       = 'Person Type';
$array['Person']            = 'Person';
$array['Picture']           = 'Picture';
$array['Postcode']          = 'Postcode';
$array['Seq']               = 'Seq';
$array['Star Sign']         = 'Star Sign';
$array['Telephone No']      = 'Telephone No';
$array['Town']              = 'Town';
$array['Tree Level Id']     = 'Tree Level Id';
$array['Tree Level Seq']    = 'Tree Level Seq';
$array['Tree Level']        = 'Tree Level';
$array['Tree Type']         = 'Tree Type';
$array['Value 1']           = 'Value 1';
$array['Value 2']           = 'Value 2';
$array['#']                 = '#';

return $array;

?>