ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SET SCAN OFF;

ALTER SESSION SET CURRENT_SCHEMA = "MENU";

ALTER TABLE MENU.MNU_USER ADD (force_pswd_chg CHAR(1 BYTE) DEFAULT 'N' NOT NULL );
