ALTER SESSION SET CURRENT_SCHEMA = "MENU";

UPDATE mnu_control SET field_id='AUTHENTICATION' WHERE record_id='SYSTEM' AND field_id='RADIUS_AUTHENTICATION';
UPDATE mnu_control SET field_value='RADIUS' WHERE record_id='SYSTEM' AND field_id='AUTHENTICATION' AND field_value='Y';
UPDATE mnu_control SET field_value='INTERNAL' WHERE record_id='SYSTEM' AND field_id='AUTHENTICATION' AND field_value='N';

ALTER TABLE MENU.MNU_ROLE RENAME COLUMN IS_RADIUS_AUTH_OFF TO IS_EXTERNAL_AUTH_OFF;
ALTER TABLE MENU.MNU_USER RENAME COLUMN IS_RADIUS_AUTH_OFF TO IS_EXTERNAL_AUTH_OFF;
ALTER TABLE MENU.MNU_USER RENAME COLUMN RADIUS_ID TO EXTERNAL_ID;
ALTER TABLE MENU.MNU_USER MODIFY(EXTERNAL_ID VARCHAR2(255 BYTE));

ALTER TABLE MENU.MNU_TASK  ADD (MAX_EXECUTION_TIME  NUMBER(5));
