ALTER SESSION SET CURRENT_SCHEMA = "MENU";

ALTER TABLE MENU.MNU_TASK MODIFY(INITIAL_PASSTHRU VARCHAR2(80 BYTE));

ALTER TABLE MENU.MNU_TASK  ADD (task_id_run_at_end  VARCHAR2(80 BYTE));
ALTER TABLE MENU.MNU_TASK  ADD (task_id_run_at_cancel  VARCHAR2(80 BYTE));
