ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SET SCAN OFF;

ALTER SESSION SET CURRENT_SCHEMA = "MENU";

ALTER TABLE MENU.MNU_TASK_FIELD  ADD (is_documentation_only  CHAR(1 BYTE) DEFAULT 'N' NOT NULL);

CREATE TABLE "MENU"."MNU_TASK_QUICKSEARCH" 
   (	task_id VARCHAR2(80 BYTE), 
	field_id VARCHAR2(40 BYTE), 
	sort_seq NUMBER(3,0) DEFAULT '000', 
	field_name VARCHAR2(40) NOT NULL,
	created_date TIMESTAMP(6) DEFAULT '2000-01-01 00:00:00',
	created_user VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN',
	revised_date TIMESTAMP(6) DEFAULT NULL,
	revised_user VARCHAR2(16 BYTE) DEFAULT NULL,
	PRIMARY KEY (task_id,field_id)
   ) ;

GRANT DELETE, INSERT, SELECT, UPDATE ON "MENU"."MNU_TASK_QUICKSEARCH" TO PUBLIC;

CREATE TABLE "MENU"."MNU_TASK_QUICKSEARCH_ALT" 
   (	task_id VARCHAR2(80 BYTE), 
	field_id VARCHAR2(40 BYTE), 
	language_id VARCHAR2(5) NOT NULL,
	field_name VARCHAR2(40) NOT NULL,
	created_date TIMESTAMP(6) DEFAULT '2000-01-01 00:00:00',
	created_user VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN',
	revised_date TIMESTAMP(6) DEFAULT NULL,
	revised_user VARCHAR2(16 BYTE) DEFAULT NULL,
	PRIMARY KEY (task_id,field_id,language_id)
   ) ;

GRANT DELETE, INSERT, SELECT, UPDATE ON "MENU"."MNU_TASK_QUICKSEARCH_ALT" TO PUBLIC;
