ALTER SESSION SET CURRENT_SCHEMA = "MENU";

--------------------------------------------------------
--  DDL for Table HELP_TEXT
--------------------------------------------------------

CREATE TABLE "MENU"."HELP_TEXT_ALT" (
	"TASK_ID" VARCHAR2(80 BYTE), 
	"LANGUAGE_ID" VARCHAR2(5 BYTE),
	"HELP_TEXT" CLOB, 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (task_id, language_id)
) ;
REVOKE ALL ON help_text_alt FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON help_text_alt TO PUBLIC;

CREATE TABLE "MENU"."MNU_TASK_ALT" (
	"TASK_ID" VARCHAR2(80 BYTE), 
	"LANGUAGE_ID" VARCHAR2(5 BYTE),
	"TASK_DESC" VARCHAR2(80 BYTE), 
        "BUTTON_TEXT" VARCHAR2(80 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (task_id, language_id)
) ;
REVOKE ALL ON mnu_task_alt FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_task_alt TO PUBLIC;