ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SET SCAN OFF;

ALTER SESSION SET CURRENT_SCHEMA = "MENU";

ALTER TABLE MNU_ACCOUNT MODIFY (ACCOUNT_NAME VARCHAR2(80 BYTE) );
ALTER TABLE MNU_ACCOUNT ADD (ACCOUNT_DESC CLOB );

ALTER TABLE MNU_FAVOURITE RENAME COLUMN TASK_DESC TO TASK_NAME;

ALTER TABLE MNU_PATTERN RENAME COLUMN PATTERN_DESC TO PATTERN_NAME;
ALTER TABLE MNU_PATTERN MODIFY (PATTERN_NAME VARCHAR2(80 BYTE) );

ALTER TABLE MNU_PATTERN RENAME COLUMN PATTERN_LONG_DESC TO PATTERN_DESC;

ALTER TABLE MNU_ROLE RENAME COLUMN ROLE_DESC TO ROLE_NAME;
ALTER TABLE MNU_ROLE MODIFY (ROLE_NAME VARCHAR2(80 BYTE) );
ALTER TABLE MNU_ROLE MODIFY (ROLE_NAME NOT NULL);
ALTER TABLE MNU_ROLE MODIFY (START_TASK_ID NOT NULL);

ALTER TABLE MNU_ROLE ADD (ROLE_DESC CLOB );

ALTER TABLE MNU_SAVED_SELECTION RENAME COLUMN SELECTION_DESC TO SELECTION_NAME;

ALTER TABLE MNU_SUBSYSTEM RENAME COLUMN SUBSYS_DESC TO SUBSYS_NAME;
ALTER TABLE MNU_SUBSYSTEM MODIFY (SUBSYS_NAME VARCHAR2(80 BYTE) );
ALTER TABLE MNU_SUBSYSTEM ADD (SUBSYS_DESC CLOB );

UPDATE mnu_task SET is_disabled='N' WHERE is_disabled IS NULL;
UPDATE mnu_task SET keep_data='N' WHERE keep_data IS NULL;
UPDATE mnu_task SET log_sql_query='N' WHERE log_sql_query IS NULL;
UPDATE mnu_task SET use_https='N' WHERE use_https IS NULL;

ALTER TABLE MNU_TASK RENAME COLUMN TASK_DESC TO TASK_NAME;
ALTER TABLE MNU_TASK MODIFY (TASK_NAME NOT NULL);
ALTER TABLE MNU_TASK ADD (TASK_DESC CLOB );
ALTER TABLE MNU_TASK MODIFY (BUTTON_TEXT VARCHAR2(40 BYTE) );
ALTER TABLE MNU_TASK MODIFY (BUTTON_TEXT NOT NULL);

ALTER TABLE MNU_TASK_ALT RENAME COLUMN TASK_DESC TO TASK_NAME;
ALTER TABLE MNU_TASK_ALT MODIFY (TASK_NAME NOT NULL);
ALTER TABLE MNU_TASK_ALT ADD (TASK_DESC CLOB );
ALTER TABLE MNU_TASK_ALT MODIFY (BUTTON_TEXT VARCHAR2(40 BYTE) NOT NULL);

ALTER TABLE MNU_TASK_QUICKSEARCH MODIFY (FIELD_NAME VARCHAR2(80 BYTE) );

ALTER TABLE MNU_TASK_QUICKSEARCH_ALT MODIFY (FIELD_NAME VARCHAR2(80 BYTE) );

ALTER TABLE MNU_TODO RENAME COLUMN ITEM_DESC TO ITEM_NAME;
ALTER TABLE MNU_TODO RENAME COLUMN ITEM_NOTES TO ITEM_DESC;

ALTER TABLE MNU_USER MODIFY (USER_NAME VARCHAR2(40 BYTE) );

ALTER TABLE MNU_USER_ALT MODIFY (USER_NAME VARCHAR2(40 BYTE) );

-- update database contents
UPDATE mnu_task_quicksearch SET field_id='database_name', field_name='Database Name' WHERE field_id='database_desc';
UPDATE mnu_task_quicksearch SET field_id='table_name', field_name='Table Name' WHERE field_id='table_desc';
UPDATE mnu_task_quicksearch SET field_id='pattern_name', field_name='Pattern Name' WHERE field_id='pattern_desc';
UPDATE mnu_task_quicksearch SET field_id='role_name', field_name='Role Name' WHERE field_id='role_desc';
UPDATE mnu_task_quicksearch SET field_id='subsys_name', field_name='Subsystem Name' WHERE field_id='subsys_desc';
UPDATE mnu_task_quicksearch SET field_id='task_name', field_name='Task Name' WHERE field_id='task_desc';
UPDATE mnu_task_quicksearch SET field_id='item_name', field_name='Item Name' WHERE field_id='item_desc';

-- set missing NOT NULL constraints
ALTER TABLE HELP_TEXT MODIFY (HELP_TEXT NOT NULL);
ALTER TABLE HELP_TEXT MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE HELP_TEXT MODIFY (CREATED_USER NOT NULL);

ALTER TABLE HELP_TEXT_ALT MODIFY (HELP_TEXT NOT NULL);
ALTER TABLE HELP_TEXT_ALT MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE HELP_TEXT_ALT MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_ACCOUNT MODIFY (ACCOUNT_NAME NOT NULL);
ALTER TABLE MNU_ACCOUNT MODIFY (RDCVERSION NOT NULL);
ALTER TABLE MNU_ACCOUNT MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_ACCOUNT MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_CONTROL MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_CONTROL MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_FAVOURITE MODIFY (TASK_ID NOT NULL);
ALTER TABLE MNU_FAVOURITE MODIFY (TASK_NAME NOT NULL);
ALTER TABLE MNU_FAVOURITE MODIFY (SORT_SEQ NOT NULL);
ALTER TABLE MNU_FAVOURITE MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_FAVOURITE MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_INITIAL_VALUE_ROLE MODIFY (INITIAL_VALUE NOT NULL);
ALTER TABLE MNU_INITIAL_VALUE_ROLE MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_INITIAL_VALUE_ROLE MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_INITIAL_VALUE_USER MODIFY (INITIAL_VALUE NOT NULL);
ALTER TABLE MNU_INITIAL_VALUE_USER MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_INITIAL_VALUE_USER MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_LANGUAGE MODIFY (LANGUAGE_NAME NOT NULL);
ALTER TABLE MNU_LANGUAGE MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_LANGUAGE MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_MENU MODIFY (SORT_SEQ NOT NULL);
ALTER TABLE MNU_MENU MODIFY (BUTTON_TEXT NOT NULL);
ALTER TABLE MNU_MENU MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_MENU MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_MOTD MODIFY (MOTD_SUBJECT NOT NULL);
ALTER TABLE MNU_MOTD MODIFY (START_DATE NOT NULL);
ALTER TABLE MNU_MOTD MODIFY (END_DATE DEFAULT NULL );
ALTER TABLE MNU_MOTD MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_MOTD MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_NAV_BUTTON MODIFY (SORT_SEQ NOT NULL);
ALTER TABLE MNU_NAV_BUTTON MODIFY (BUTTON_TEXT NOT NULL);
ALTER TABLE MNU_NAV_BUTTON MODIFY (CONTEXT_PRESELECT NOT NULL);
ALTER TABLE MNU_NAV_BUTTON MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_NAV_BUTTON MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_PATTERN MODIFY (PATTERN_NAME NOT NULL);
ALTER TABLE MNU_PATTERN MODIFY (VISIBLE_SCREEN NOT NULL);
ALTER TABLE MNU_PATTERN MODIFY (CONTEXT_PRESELECT NOT NULL);
ALTER TABLE MNU_PATTERN MODIFY (KEEP_DATA NOT NULL);
ALTER TABLE MNU_PATTERN MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_PATTERN MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_ROLE MODIFY (GLOBAL_ACCESS NOT NULL);
ALTER TABLE MNU_ROLE MODIFY (IS_EXTERNAL_AUTH_OFF NOT NULL);
ALTER TABLE MNU_ROLE MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_ROLE MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_ROLE_TASK MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_ROLE_TASK MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_ROLE_TASKFIELD MODIFY (ACCESS_TYPE NOT NULL);
ALTER TABLE MNU_ROLE_TASKFIELD MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_ROLE_TASKFIELD MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_SAVED_SELECTION MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_SAVED_SELECTION MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_SAVED_SELECTION_DATA MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_SAVED_SELECTION_DATA MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_SUBSYSTEM MODIFY (SUBSYS_NAME NOT NULL);
ALTER TABLE MNU_SUBSYSTEM MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_SUBSYSTEM MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_TASK MODIFY (TASK_TYPE NOT NULL);
ALTER TABLE MNU_TASK MODIFY (SCRIPT_ID NOT NULL);
ALTER TABLE MNU_TASK MODIFY (IS_DISABLED NOT NULL);
ALTER TABLE MNU_TASK MODIFY (PATTERN_ID NOT NULL);
ALTER TABLE MNU_TASK MODIFY (SUBSYS_ID NOT NULL);
ALTER TABLE MNU_TASK MODIFY (KEEP_DATA NOT NULL);
ALTER TABLE MNU_TASK MODIFY (LOG_SQL_QUERY NOT NULL);
ALTER TABLE MNU_TASK MODIFY (USE_HTTPS NOT NULL);
ALTER TABLE MNU_TASK MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TASK MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_TASK_ALT MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TASK_ALT MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_TASK_FIELD MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TASK_FIELD MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_TASK_IP_ADDRESS MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TASK_IP_ADDRESS MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_TASK_QUICKSEARCH MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TASK_QUICKSEARCH MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_TASK_QUICKSEARCH_ALT MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TASK_QUICKSEARCH_ALT MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (CREATED_USER NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (SCHEDULED_MONDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (SCHEDULED_TUESDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (SCHEDULED_WEDNESDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (SCHEDULED_THURSDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (SCHEDULED_FRIDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (SCHEDULED_SATURDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_ROLE MODIFY (SCHEDULED_SUNDAY NOT NULL);

ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_START_TIME NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_END_TIME NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_MONDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_TUESDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_WEDNESDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_THURSDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_FRIDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_SATURDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (SCHEDULED_SUNDAY NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TIME_LIMIT_USER MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_TODO MODIFY (DUE_DATE NOT NULL);
ALTER TABLE MNU_TODO MODIFY (VISIBILITY NOT NULL);
ALTER TABLE MNU_TODO MODIFY (IS_COMPLETE NOT NULL);
ALTER TABLE MNU_TODO MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_TODO MODIFY (CREATED_USER NOT NULL);

UPDATE mnu_user SET email_addr=user_id || '@null.null' WHERE email_addr IS NULL OR email_addr='';

ALTER TABLE MNU_USER MODIFY (EMAIL_ADDR NOT NULL);
ALTER TABLE MNU_USER MODIFY (IN_USE NOT NULL);
ALTER TABLE MNU_USER MODIFY (IS_DISABLED NOT NULL);
ALTER TABLE MNU_USER MODIFY (START_DATE NOT NULL);
ALTER TABLE MNU_USER MODIFY (IS_EXTERNAL_AUTH_OFF NOT NULL);
ALTER TABLE MNU_USER MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_USER MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_USER_ALT MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_USER_ALT MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_USER_IP_ADDRESS MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_USER_IP_ADDRESS MODIFY (CREATED_USER NOT NULL);

ALTER TABLE MNU_USER_ROLE MODIFY (IS_PRIMARY NOT NULL);
ALTER TABLE MNU_USER_ROLE MODIFY (CREATED_DATE NOT NULL);
ALTER TABLE MNU_USER_ROLE MODIFY (CREATED_USER NOT NULL);

-- combine separate DATE and TIME fields into a single DATETIME field
ALTER TABLE MNU_USER ADD (pswd_change_datetime TIMESTAMP(0));
-- UPDATE mnu_user SET pswd_change_datetime=null;
UPDATE mnu_user SET pswd_change_datetime=to_timestamp(to_char(pswd_chg_date, 'YYYY-MM-DD') || pswd_chg_time , 'YYYY-MM-DD HH24:MI:SS') WHERE pswd_change_datetime IS NULL;

ALTER TABLE MNU_USER DROP COLUMN pswd_chg_date;
ALTER TABLE MNU_USER DROP COLUMN pswd_chg_time;

ALTER TABLE MNU_USER ADD (logon_datetime TIMESTAMP(0));
-- UPDATE mnu_user SET logon_datetime=null;
UPDATE mnu_user SET logon_datetime=to_timestamp(to_char(logon_date, 'YYYY-MM-DD') || logon_time , 'YYYY-MM-DD HH24:MI:SS') WHERE logon_datetime IS NULL;

ALTER TABLE MNU_USER DROP COLUMN logon_date;
ALTER TABLE MNU_USER DROP COLUMN logon_time;

-- changes to allow output for responsive gui
ALTER TABLE mnu_role ADD (allow_responsive_gui CHAR(1) DEFAULT 'N' NOT NULL);
ALTER TABLE mnu_task ADD (allow_responsive_gui CHAR(1) DEFAULT 'N' NOT NULL);
ALTER TABLE mnu_user ADD (allow_responsive_gui CHAR(1) DEFAULT 'N' NOT NULL);

-- finish