CREATE USER "MENU" IDENTIFIED BY "MENU";
GRANT CONNECT, RESOURCE TO "MENU";
GRANT CREATE DATABASE LINK TO "MENU";
GRANT CREATE MATERIALIZED VIEW TO "MENU";
GRANT CREATE PROCEDURE TO "MENU";
GRANT CREATE PUBLIC SYNONYM TO "MENU";
GRANT CREATE ROLE TO "MENU";
GRANT CREATE SEQUENCE TO "MENU";
GRANT CREATE SYNONYM TO "MENU";
GRANT CREATE TABLE TO "MENU";
GRANT CREATE TRIGGER TO "MENU";
GRANT CREATE TYPE TO "MENU";
GRANT CREATE VIEW TO "MENU";

ALTER SESSION SET CURRENT_SCHEMA = "MENU";

--------------------------------------------------------
--  DDL for Table HELP_TEXT
--------------------------------------------------------

CREATE TABLE "MENU"."HELP_TEXT" (
	"TASK_ID" VARCHAR2(80 BYTE), 
	"HELP_TEXT" CLOB, 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (task_id)
) ;
REVOKE ALL ON help_text FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON help_text TO PUBLIC;


--------------------------------------------------------
--  DDL for Table MNU_ACCOUNT
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_ACCOUNT" (
	"RDCACCOUNT_ID" NUMBER(10,0), 
	"ACCOUNT_NAME" VARCHAR2(255 BYTE), 
	"RDCVERSION" NUMBER(10,0) DEFAULT 1, 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (rdcaccount_id)
) ;
REVOKE ALL ON mnu_account FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_account TO PUBLIC;

CREATE SEQUENCE mnu_account_seq;
REVOKE ALL ON mnu_account_seq FROM PUBLIC;
GRANT SELECT,ALTER ON mnu_account_seq TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_CONTROL
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_CONTROL" (
	"RECORD_ID" VARCHAR2(16 BYTE), 
	"FIELD_ID" VARCHAR2(32 BYTE), 
	"FIELD_VALUE" VARCHAR2(255 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (record_id,field_id)
) ;
REVOKE ALL ON mnu_control FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_control TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_FAVOURITE
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_FAVOURITE" (
	"USER_ID" VARCHAR2(16 BYTE), 
	"SEQ_NO" NUMBER(6,0), 
	"TASK_ID" VARCHAR2(80 BYTE), 
	"TASK_DESC" VARCHAR2(80 BYTE), 
	"SORT_SEQ" NUMBER(6,0), 
	"BREADCRUMBS" VARCHAR2(4000 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (user_id,seq_no)
) ;
REVOKE ALL ON mnu_favourite FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_favourite TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_INITIAL_VALUE_ROLE
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_INITIAL_VALUE_ROLE" (
	"ROLE_ID" VARCHAR2(16 BYTE), 
	"TASK_ID" VARCHAR2(80 BYTE), 
	"FIELD_ID" VARCHAR2(40 BYTE), 
	"INITIAL_VALUE" VARCHAR2(255 BYTE), 
	"IS_NOEDIT" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (role_id,task_id,field_id)
) ;
CREATE INDEX mnu_initial_value_role_idx1 ON mnu_initial_value_role (task_id);

REVOKE ALL ON mnu_initial_value_role FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_initial_value_role TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_INITIAL_VALUE_USER
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_INITIAL_VALUE_USER" (
	"USER_ID" VARCHAR2(16 BYTE), 
	"TASK_ID" VARCHAR2(80 BYTE), 
	"FIELD_ID" VARCHAR2(40 BYTE), 
	"INITIAL_VALUE" VARCHAR2(255 BYTE), 
	"IS_NOEDIT" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (user_id,task_id,field_id)
) ;
CREATE INDEX mnu_initial_value_user_idx1 ON mnu_initial_value_user (task_id);

REVOKE ALL ON mnu_initial_value_user FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_initial_value_user TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_LANGUAGE
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_LANGUAGE" (
	"LANGUAGE_ID" VARCHAR2(5 BYTE) DEFAULT 'EN', 
	"LANGUAGE_NAME" VARCHAR2(40 BYTE) DEFAULT 'English', 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT '2000-01-01 00:00:00', 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6) DEFAULT NULL, 
	"REVISED_USER" VARCHAR2(16 BYTE) DEFAULT NULL,
	PRIMARY KEY (language_id)
) ;
REVOKE ALL ON mnu_language FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_language TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_MENU
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_MENU" (
	"MENU_ID" VARCHAR2(80 BYTE), 
	"TASK_ID_JNR" VARCHAR2(80 BYTE), 
	"SORT_SEQ" NUMBER(3,0) DEFAULT '000', 
	"BUTTON_TEXT" VARCHAR2(40 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (menu_id,task_id_jnr)
) ;
REVOKE ALL ON mnu_menu FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_menu TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_MOTD
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_MOTD" (
	"MOTD_ID" NUMBER, 
	"MOTD_SUBJECT" CHAR(80 BYTE), 
	"MOTD_MESSAGE" CLOB, 
	"START_DATE" DATE DEFAULT '2001-01-01', 
	"END_DATE" DATE DEFAULT '9999-12-31', 
	"ROLE_ID" VARCHAR2(16 BYTE), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT '2001-01-01', 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (motd_id)
) ;
REVOKE ALL ON mnu_motd FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_motd TO PUBLIC;

CREATE SEQUENCE mnu_motd_seq;
REVOKE ALL ON mnu_motd_seq FROM PUBLIC;
GRANT SELECT,ALTER ON mnu_motd_seq TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_NAV_BUTTON
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_NAV_BUTTON" (
	"TASK_ID_SNR" VARCHAR2(80 BYTE), 
	"TASK_ID_JNR" VARCHAR2(80 BYTE), 
	"SORT_SEQ" NUMBER(3,0) DEFAULT '000', 
	"BUTTON_TEXT" VARCHAR2(40 BYTE), 
	"CONTEXT_PRESELECT" CHAR(1 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (task_id_snr,task_id_jnr)
) ;
REVOKE ALL ON mnu_nav_button FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_nav_button TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_PATTERN
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_PATTERN" (
	"PATTERN_ID" VARCHAR2(16 BYTE), 
	"PATTERN_DESC" VARCHAR2(60 BYTE), 
	"PATTERN_LONG_DESC" CLOB, 
	"VISIBLE_SCREEN" CHAR(1 BYTE), 
	"CONTEXT_PRESELECT" CHAR(1 BYTE), 
	"KEEP_DATA" CHAR(1 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (pattern_id)
) ;
REVOKE ALL ON mnu_pattern FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_pattern TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_ROLE
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_ROLE" (
	"ROLE_ID" VARCHAR2(16 BYTE), 
	"ROLE_DESC" VARCHAR2(30 BYTE), 
	"START_TASK_ID" VARCHAR2(80 BYTE), 
	"GLOBAL_ACCESS" CHAR(1 BYTE) DEFAULT 'N', 
	"IS_EXTERNAL_AUTH_OFF" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (role_id)
) ;
REVOKE ALL ON mnu_role FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_role TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_ROLE_TASK
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_ROLE_TASK" (
	"ROLE_ID" VARCHAR2(16 BYTE), 
	"TASK_ID" VARCHAR2(80 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (role_id,task_id)
) ;
REVOKE ALL ON mnu_role_task FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_role_task TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_ROLE_TASKFIELD
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_ROLE_TASKFIELD" (
	"ROLE_ID" VARCHAR2(16 BYTE), 
	"TASK_ID" VARCHAR2(80 BYTE), 
	"FIELD_ID" VARCHAR2(40 BYTE), 
	"ACCESS_TYPE" VARCHAR2(4 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (role_id,task_id,field_id)
) ;
CREATE INDEX mnu_role_taskfield_idx1 ON mnu_role_taskfield (task_id);

REVOKE ALL ON mnu_role_task FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_role_task TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_SUBSYSTEM
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_SUBSYSTEM" (
	"SUBSYS_ID" VARCHAR2(16 BYTE), 
	"SUBSYS_DESC" VARCHAR2(255 BYTE), 
	"SUBSYS_DIR" VARCHAR2(255 BYTE), 
	"TASK_PREFIX" VARCHAR2(8 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (subsys_id)
) ;
REVOKE ALL ON mnu_subsystem FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_subsystem TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_TASK
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_TASK" (
	"TASK_ID" VARCHAR2(80 BYTE), 
	"TASK_DESC" VARCHAR2(80 BYTE), 
	"BUTTON_TEXT" VARCHAR2(80 BYTE), 
	"TASK_TYPE" VARCHAR2(4 BYTE), 
	"SCRIPT_ID" VARCHAR2(80 BYTE), 
	"IS_DISABLED" CHAR(1 BYTE), 
	"PATTERN_ID" VARCHAR2(16 BYTE), 
	"SUBSYS_ID" VARCHAR2(16 BYTE), 
	"INITIAL_PASSTHRU" VARCHAR2(80 BYTE), 
	"SELECTION_FIXED" VARCHAR2(255 BYTE), 
	"SELECTION_TEMP" VARCHAR2(255 BYTE), 
	"SETTINGS" VARCHAR2(255 BYTE), 
	"ORDER_BY" VARCHAR2(255 BYTE), 
	"KEEP_DATA" CHAR(1 BYTE), 
	"LOG_SQL_QUERY" CHAR(1 BYTE), 
	"SCREEN_REFRESH" NUMBER(5,0), 
	"USE_HTTPS" CHAR(1 BYTE), 
	"MAX_EXECUTION_TIME" NUMBER(5,0), 
	"TASK_ID_RUN_AT_END" VARCHAR2(80 BYTE), 
	"TASK_ID_RUN_AT_CANCEL" VARCHAR2(80 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (task_id)
) ;
CREATE INDEX mnu_task_idx1 ON mnu_task (subsys_id);
CREATE INDEX mnu_task_idx2 ON mnu_task (pattern_id);

REVOKE ALL ON mnu_task FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_task TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_TASK_FIELD
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_TASK_FIELD" (
	"TASK_ID" VARCHAR2(80 BYTE), 
	"FIELD_ID" VARCHAR2(40 BYTE), 
	"FIELD_DESC" VARCHAR2(255 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (task_id,field_id)
) ;
REVOKE ALL ON mnu_task_field FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_task_field TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_TASK_IP_ADDRESS
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_TASK_IP_ADDRESS" (
	"TASK_ID" VARCHAR2(80 BYTE), 
	"IP_ADDRESS" VARCHAR2(40 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (task_id,ip_address)
) ;
REVOKE ALL ON mnu_task_ip_address FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_task_ip_address TO PUBLIC;


--------------------------------------------------------
--  DDL for Table MNU_TODO
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_TODO" (
	"USER_ID" VARCHAR2(16 BYTE), 
	"SEQ_NO" NUMBER(6,0), 
	"ITEM_DESC" VARCHAR2(80 BYTE), 
	"ITEM_NOTES" CLOB, 
	"DUE_DATE" DATE, 
	"VISIBILITY" NUMBER(3,0), 
	"IS_COMPLETE" CHAR(1 BYTE) DEFAULT 'N', 
	"REPEAT_INTERVAL" NUMBER(3,0), 
	"REPEAT_UNIT" CHAR(1 BYTE), 
	"TASK_ID" VARCHAR2(80 BYTE), 
	"TASK_CONTEXT" VARCHAR2(255 BYTE) DEFAULT NULL, 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (user_id,seq_no)
) ;
REVOKE ALL ON mnu_todo FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_todo TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_USER
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_USER" (
	"USER_ID" VARCHAR2(16 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_PASSWORD" VARCHAR2(40 BYTE), 
	"ROLE_ID" VARCHAR2(16 BYTE), 
	"RDCACCOUNT_ID" NUMBER(10,0), 
	"PSWD_CHG_DATE" DATE, 
	"PSWD_CHG_TIME" CHAR(8 BYTE), 
	"PSWD_COUNT" NUMBER(6,0), 
	"IN_USE" CHAR(1 BYTE) DEFAULT 'N', 
	"IS_DISABLED" CHAR(1 BYTE) DEFAULT 'N', 
	"LOGON_DATE" DATE, 
	"LOGON_TIME" CHAR(8 BYTE), 
	"LANGUAGE_CODE" VARCHAR2(6 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"IP_ADDRESS" VARCHAR2(40 BYTE), 
	"EMAIL_ADDR" VARCHAR2(50 BYTE), 
	"EXTERNAL_ID" VARCHAR2(255 BYTE), 
	"IS_EXTERNAL_AUTH_OFF" CHAR(1 BYTE) DEFAULT 'N', 
	"PARTY_ID" NUMBER(10,0), 
	"USER_TIMEZONE" VARCHAR2(40 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (user_id)
) ;
CREATE UNIQUE INDEX mnu_user_idx1 ON mnu_user (email_addr);
CREATE INDEX mnu_user_idx2 ON mnu_user (role_id);
CREATE INDEX mnu_user_idx3 ON mnu_user (rdcaccount_id);

REVOKE ALL ON mnu_user FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_user TO PUBLIC;
 

--------------------------------------------------------
--  DDL for Table MNU_USER_IP_ADDRESS
--------------------------------------------------------

CREATE TABLE "MENU"."MNU_USER_IP_ADDRESS" (
	"USER_ID" VARCHAR2(16 BYTE), 
	"IP_ADDRESS" VARCHAR2(40 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN', 
	"REVISED_DATE" TIMESTAMP (6), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY (user_id,ip_address)
) ;
REVOKE ALL ON mnu_user_ip_address FROM PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON mnu_user_ip_address TO PUBLIC;
