--------------------------------------------------------
--  File created - Sunday-May-7-2017  
--------------------------------------------------------

CREATE USER "MENU" IDENTIFIED BY "MENU";
GRANT CONNECT, RESOURCE TO "MENU";
GRANT CREATE DATABASE LINK TO "MENU";
GRANT CREATE MATERIALIZED VIEW TO "MENU";
GRANT CREATE PROCEDURE TO "MENU";
GRANT CREATE PUBLIC SYNONYM TO "MENU";
GRANT CREATE ROLE TO "MENU";
GRANT CREATE SEQUENCE TO "MENU";
GRANT CREATE SYNONYM TO "MENU";
GRANT CREATE TABLE TO "MENU";
GRANT CREATE TRIGGER TO "MENU";
GRANT CREATE TYPE TO "MENU";
GRANT CREATE VIEW TO "MENU";

ALTER SESSION SET CURRENT_SCHEMA = "MENU";

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

--------------------------------------------------------
--  DDL for Sequence MNU_ACCOUNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MNU_ACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "MNU_ACCOUNT_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence MNU_MOTD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MNU_MOTD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "MNU_MOTD_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence MNU_SAVED_SELECTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MNU_SAVED_SELECTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "MNU_SAVED_SELECTION_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table HELP_TEXT
--------------------------------------------------------

  CREATE TABLE "HELP_TEXT" 
   (	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"HELP_TEXT" CLOB NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "HELP_TEXT" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table HELP_TEXT_ALT
--------------------------------------------------------

  CREATE TABLE "HELP_TEXT_ALT" 
   (	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"LANGUAGE_ID" VARCHAR2(5 BYTE) NOT NULL, 
	"HELP_TEXT" CLOB NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL,  
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID", "LANGUAGE_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "HELP_TEXT_ALT" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "MNU_ACCOUNT" 
   (	"RDCACCOUNT_ID" NUMBER(10,0) NOT NULL, 
	"ACCOUNT_NAME" VARCHAR2(80 BYTE) NOT NULL, 
        "ACCOUNT_DESC" CLOB,
	"RDCVERSION" NUMBER(10,0) DEFAULT 1, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("RDCACCOUNT_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_ACCOUNT" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_CONTROL
--------------------------------------------------------

  CREATE TABLE "MNU_CONTROL" 
   (	"RECORD_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"FIELD_ID" VARCHAR2(32 BYTE) NOT NULL, 
	"FIELD_VALUE" VARCHAR2(255 BYTE), 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("RECORD_ID", "FIELD_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_CONTROL" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_FAVOURITE
--------------------------------------------------------

  CREATE TABLE "MNU_FAVOURITE" 
   (	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"SEQ_NO" NUMBER(6,0) NOT NULL, 
	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"TASK_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"SORT_SEQ" NUMBER(6,0) NOT NULL, 
	"BREADCRUMBS" VARCHAR2(4000 BYTE), 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("USER_ID", "SEQ_NO")
   ) ;
  CREATE UNIQUE INDEX "MNU_FAVOURITE_IDX1" ON "MNU_FAVOURITE" ("USER_ID", "TASK_ID");
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_FAVOURITE" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_INITIAL_VALUE_ROLE
--------------------------------------------------------

  CREATE TABLE "MNU_INITIAL_VALUE_ROLE" 
   (	"ROLE_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"FIELD_ID" VARCHAR2(40 BYTE) NOT NULL, 
	"INITIAL_VALUE" VARCHAR2(255 BYTE), 
	"IS_NOEDIT" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("ROLE_ID", "TASK_ID", "FIELD_ID")
   ) ;
  CREATE INDEX "MNU_INITIAL_VALUE_ROLE_IDX1" ON "MNU_INITIAL_VALUE_ROLE" ("TASK_ID");
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_INITIAL_VALUE_ROLE" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_INITIAL_VALUE_USER
--------------------------------------------------------

  CREATE TABLE "MNU_INITIAL_VALUE_USER" 
   (	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"FIELD_ID" VARCHAR2(40 BYTE) NOT NULL, 
	"INITIAL_VALUE" VARCHAR2(255 BYTE), 
	"IS_NOEDIT" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("USER_ID", "TASK_ID", "FIELD_ID")
   ) ;
  CREATE INDEX "MNU_INITIAL_VALUE_USER_IDX1" ON "MNU_INITIAL_VALUE_USER" ("TASK_ID");
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_INITIAL_VALUE_USER" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_LANGUAGE
--------------------------------------------------------

  CREATE TABLE "MNU_LANGUAGE" 
   (	"LANGUAGE_ID" VARCHAR2(5 BYTE) DEFAULT 'EN' NOT NULL, 
	"LANGUAGE_NAME" VARCHAR2(40 BYTE) DEFAULT 'English' NOT NULL, 
	"INPUT_DATE_FORMAT" VARCHAR2(12 BYTE), 
	"OUTPUT_DATE_FORMAT" VARCHAR2(12 BYTE),
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("LANGUAGE_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_LANGUAGE" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_MENU
--------------------------------------------------------

  CREATE TABLE "MNU_MENU" 
   (	"MENU_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"TASK_ID_JNR" VARCHAR2(80 BYTE) NOT NULL, 
	"SORT_SEQ" NUMBER(3,0) DEFAULT '000' NOT NULL, 
	"BUTTON_TEXT" VARCHAR2(40 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("MENU_ID", "TASK_ID_JNR")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_MENU" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_MOTD
--------------------------------------------------------

  CREATE TABLE "MNU_MOTD" 
   (	"MOTD_ID" NUMBER NOT NULL, 
	"MOTD_SUBJECT" CHAR(80 BYTE) NOT NULL, 
	"MOTD_MESSAGE" CLOB, 
	"START_DATE" DATE DEFAULT '2001-01-01' NOT NULL, 
	"END_DATE" DATE DEFAULT '9999-12-31', 
	"ROLE_ID" VARCHAR2(16 BYTE), 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("MOTD_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_MOTD" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_NAV_BUTTON
--------------------------------------------------------

  CREATE TABLE "MNU_NAV_BUTTON" 
   (	"TASK_ID_SNR" VARCHAR2(80 BYTE) NOT NULL, 
	"TASK_ID_JNR" VARCHAR2(80 BYTE) NOT NULL, 
	"SORT_SEQ" NUMBER(3,0) DEFAULT '000' NOT NULL, 
	"BUTTON_TEXT" VARCHAR2(40 BYTE) NOT NULL, 
	"CONTEXT_PRESELECT" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID_SNR", "TASK_ID_JNR")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_NAV_BUTTON" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_PATTERN
--------------------------------------------------------

  CREATE TABLE "MNU_PATTERN" 
   (	"PATTERN_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"PATTERN_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"PATTERN_DESC" CLOB, 
	"VISIBLE_SCREEN" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"CONTEXT_PRESELECT" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"KEEP_DATA" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("PATTERN_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_PATTERN" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_ROLE
--------------------------------------------------------

  CREATE TABLE "MNU_ROLE" 
   (	"ROLE_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"ROLE_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"ROLE_DESC" CLOB,
	"START_TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"GLOBAL_ACCESS" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"IS_EXTERNAL_AUTH_OFF" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"ALLOW_RESPONSIVE_GUI" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("ROLE_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_ROLE" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_ROLE_TASK
--------------------------------------------------------

  CREATE TABLE "MNU_ROLE_TASK" 
   (	"ROLE_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("ROLE_ID", "TASK_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_ROLE_TASK" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_ROLE_TASKFIELD
--------------------------------------------------------

  CREATE TABLE "MNU_ROLE_TASKFIELD" 
   (	"ROLE_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"FIELD_ID" VARCHAR2(40 BYTE) NOT NULL, 
	"ACCESS_TYPE" VARCHAR2(4 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("ROLE_ID", "TASK_ID", "FIELD_ID")
   ) ;
  CREATE INDEX "MNU_ROLE_TASKFIELD_IDX1" ON "MNU_ROLE_TASKFIELD" ("TASK_ID");
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_ROLE_TASKFIELD" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_SAVED_SELECTION
--------------------------------------------------------

  CREATE TABLE "MNU_SAVED_SELECTION" 
   (	"SELECTION_ID" NUMBER(10,0) NOT NULL, 
	"SELECTION_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("SELECTION_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_SAVED_SELECTION" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_SAVED_SELECTION_DATA
--------------------------------------------------------

  CREATE TABLE "MNU_SAVED_SELECTION_DATA" 
   (	"SELECTION_ID" NUMBER(10,0) NOT NULL, 
	"FIELDNAME" VARCHAR2(80 BYTE) NOT NULL, 
	"FIELDVALUE" VARCHAR2(80 BYTE), 
	"SORT_SEQ" NUMBER(6,0), 
	"OUTPUT_NAME" VARCHAR2(80 BYTE),
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("SELECTION_ID", "FIELDNAME")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_SAVED_SELECTION_DATA" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_SUBSYSTEM
--------------------------------------------------------

  CREATE TABLE "MNU_SUBSYSTEM" 
   (	"SUBSYS_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"SUBSYS_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"SUBSYS_DESC" CLOB,
	"SUBSYS_DIR" VARCHAR2(255 BYTE) NOT NULL, 
	"TASK_PREFIX" VARCHAR2(8 BYTE), 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("SUBSYS_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_SUBSYSTEM" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TASK
--------------------------------------------------------

  CREATE TABLE "MNU_TASK" 
   (	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"TASK_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"TASK_DESC" CLOB,
	"BUTTON_TEXT" VARCHAR2(40 BYTE) NOT NULL, 
	"TASK_TYPE" VARCHAR2(4 BYTE) NOT NULL, 
	"SCRIPT_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"IS_DISABLED" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"PATTERN_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"SUBSYS_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"INITIAL_PASSTHRU" VARCHAR2(80 BYTE), 
	"SELECTION_FIXED" VARCHAR2(255 BYTE), 
	"SELECTION_TEMP" VARCHAR2(255 BYTE), 
	"SETTINGS" VARCHAR2(255 BYTE), 
	"ORDER_BY" VARCHAR2(255 BYTE), 
	"KEEP_DATA" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"LOG_SQL_QUERY" CHAR(1 BYTE) DEFAULT 'N'  NOT NULL, 
	"SCREEN_REFRESH" NUMBER(5,0), 
	"USE_HTTPS" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"MAX_EXECUTION_TIME" NUMBER(5,0), 
	"TASK_ID_RUN_AT_END" VARCHAR2(80 BYTE), 
	"TASK_ID_RUN_AT_CANCEL" VARCHAR2(80 BYTE), 
	"ALLOW_RESPONSIVE_GUI" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID")
   ) ;
  CREATE INDEX "MNU_TASK_IDX1" ON "MNU_TASK" ("SUBSYS_ID");
  CREATE INDEX "MNU_TASK_IDX2" ON "MNU_TASK" ("PATTERN_ID");
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TASK" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TASK_ALT
--------------------------------------------------------

  CREATE TABLE "MNU_TASK_ALT" 
   (	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"LANGUAGE_ID" VARCHAR2(5 BYTE) NOT NULL, 
	"TASK_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"TASK_DESC" CLOB,
	"BUTTON_TEXT" VARCHAR2(40 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID", "LANGUAGE_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TASK_ALT" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TASK_FIELD
--------------------------------------------------------

  CREATE TABLE "MNU_TASK_FIELD" 
   (	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"FIELD_ID" VARCHAR2(40 BYTE) NOT NULL, 
	"FIELD_DESC" VARCHAR2(255 BYTE), 
	"IS_DOCUMENTATION_ONLY" CHAR(1 BYTE) DEFAULT 'N',
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID", "FIELD_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TASK_FIELD" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TASK_IP_ADDRESS
--------------------------------------------------------

  CREATE TABLE "MNU_TASK_IP_ADDRESS" 
   (	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"IP_ADDRESS" VARCHAR2(40 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID", "IP_ADDRESS")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TASK_IP_ADDRESS" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TASK_QUICKSEARCH
--------------------------------------------------------

  CREATE TABLE "MNU_TASK_QUICKSEARCH" 
   (	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"FIELD_ID" VARCHAR2(40 BYTE) NOT NULL, 
	"SORT_SEQ" NUMBER(3,0) DEFAULT '000' NOT NULL, 
	"FIELD_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID", "FIELD_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TASK_QUICKSEARCH" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TASK_QUICKSEARCH_ALT
--------------------------------------------------------

  CREATE TABLE "MNU_TASK_QUICKSEARCH_ALT" 
   (	"TASK_ID" VARCHAR2(80 BYTE) NOT NULL, 
	"FIELD_ID" VARCHAR2(40 BYTE) NOT NULL, 
	"LANGUAGE_ID" VARCHAR2(5 BYTE) NOT NULL, 
	"FIELD_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("TASK_ID", "FIELD_ID", "LANGUAGE_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TASK_QUICKSEARCH_ALT" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TIME_LIMIT_ROLE
--------------------------------------------------------

  CREATE TABLE "MNU_TIME_LIMIT_ROLE" 
   (	"ROLE_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"SEQ_NO" NUMBER(6,0) NOT NULL, 
	"SCHEDULED_START_TIME" CHAR(8 BYTE) DEFAULT '09:00:00' NOT NULL, 
	"SCHEDULED_END_TIME" CHAR(8 BYTE) DEFAULT '17:30:00' NOT NULL, 
	"SCHEDULED_MONDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_TUESDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_WEDNESDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_THURSDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_FRIDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_SATURDAY" CHAR(1 BYTE) DEFAULT 0 NOT NULL, 
	"SCHEDULED_SUNDAY" CHAR(1 BYTE) DEFAULT 0 NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("ROLE_ID", "SEQ_NO")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TIME_LIMIT_ROLE" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TIME_LIMIT_USER
--------------------------------------------------------

  CREATE TABLE "MNU_TIME_LIMIT_USER" 
   (	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"SEQ_NO" NUMBER(6,0) NOT NULL, 
	"SCHEDULED_START_TIME" CHAR(8 BYTE) DEFAULT '09:00:00' NOT NULL, 
	"SCHEDULED_END_TIME" CHAR(8 BYTE) DEFAULT '17:30:00' NOT NULL, 
	"SCHEDULED_MONDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_TUESDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_WEDNESDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_THURSDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_FRIDAY" CHAR(1 BYTE) DEFAULT 1 NOT NULL, 
	"SCHEDULED_SATURDAY" CHAR(1 BYTE) DEFAULT 0 NOT NULL, 
	"SCHEDULED_SUNDAY" CHAR(1 BYTE) DEFAULT 0 NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("USER_ID", "SEQ_NO")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TIME_LIMIT_USER" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_TODO
--------------------------------------------------------

  CREATE TABLE "MNU_TODO" 
   (	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"SEQ_NO" NUMBER(6,0) NOT NULL, 
	"ITEM_NAME" VARCHAR2(80 BYTE) NOT NULL, 
	"ITEM_DESC" CLOB, 
	"DUE_DATE" DATE DEFAULT '2000-01-01' NOT NULL, 
	"VISIBILITY" NUMBER(3,0) DEFAULT '0' NOT NULL, 
	"IS_COMPLETE" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"REPEAT_INTERVAL" NUMBER(3,0), 
	"REPEAT_UNIT" CHAR(1 BYTE), 
	"TASK_ID" VARCHAR2(80 BYTE), 
	"TASK_CONTEXT" VARCHAR2(255 BYTE), 
	"OBJECT_ID" VARCHAR2(255 BYTE), 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("USER_ID", "SEQ_NO")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_TODO" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_USER
--------------------------------------------------------

  CREATE TABLE "MNU_USER" 
   (	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"USER_NAME" VARCHAR2(40 BYTE) NOT NULL, 
	"USER_PASSWORD" VARCHAR2(40 BYTE) NOT NULL, 
	"RDCACCOUNT_ID" NUMBER(10,0), 
	"PSWD_CHANGE_DATETIME" TIMESTAMP (0),
	"PSWD_COUNT" NUMBER(6,0), 
	"FORCE_PSWD_CHG" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"IN_USE" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"IS_DISABLED" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"LOGON_DATETIME" TIMESTAMP (0),
	"LANGUAGE_ID" VARCHAR2(6 BYTE), 
	"START_DATE" DATE DEFAULT '2000-01-01' NOT NULL, 
	"END_DATE" DATE, 
	"IP_ADDRESS" VARCHAR2(40 BYTE), 
	"EMAIL_ADDR" VARCHAR2(50 BYTE) NOT NULL, 
	"EXTERNAL_ID" VARCHAR2(255 BYTE), 
	"IS_EXTERNAL_AUTH_OFF" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"PARTY_ID" NUMBER(10,0), 
	"USER_TIMEZONE" VARCHAR2(40 BYTE), 
	"ALLOW_RESPONSIVE_GUI" CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("USER_ID")
   ) ;
  CREATE UNIQUE INDEX "MNU_USER_UQ1" ON "MNU_USER" ("EMAIL_ADDR");
  CREATE INDEX "MNU_USER_IDX1" ON "MNU_USER" ("RDCACCOUNT_ID");
  CREATE INDEX "MNU_USER_IDX2" ON "MNU_USER" ("PARTY_ID");
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_USER" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_USER_ALT
--------------------------------------------------------

  CREATE TABLE "MNU_USER_ALT" 
   (	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"LANGUAGE_ID" VARCHAR2(5 BYTE) NOT NULL, 
	"USER_NAME" VARCHAR2(40 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("USER_ID", "LANGUAGE_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_USER_ALT" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_USER_IP_ADDRESS
--------------------------------------------------------

  CREATE TABLE "MNU_USER_IP_ADDRESS" 
   (	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"IP_ADDRESS" VARCHAR2(40 BYTE) NOT NULL, 
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("USER_ID", "IP_ADDRESS")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_USER_IP_ADDRESS" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table MNU_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "MNU_USER_ROLE" 
   (	"USER_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"ROLE_ID" VARCHAR2(16 BYTE) NOT NULL, 
	"SORT_SEQ" NUMBER(6,0),
	"START_DATE" DATE DEFAULT '2000-01-01' NOT NULL, 
	"END_DATE" DATE DEFAULT '9999-12-31',
	"CREATED_DATE" TIMESTAMP (0) DEFAULT '2000-01-01 00:00:00' NOT NULL, 
	"CREATED_USER" VARCHAR2(16 BYTE) DEFAULT 'UNKNOWN' NOT NULL, 
	"REVISED_DATE" TIMESTAMP (0), 
	"REVISED_USER" VARCHAR2(16 BYTE),
	PRIMARY KEY ("USER_ID", "ROLE_ID")
   ) ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "MNU_USER_ROLE" TO PUBLIC;

-- finished