-- file created on October 26, 2017, 3:38 pm

-- SET search_path = dict;

INSERT INTO dict_database (database_id, database_name, database_desc, subsys_id, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit', 'Author: A J Marston
Date: August, 2004

This is the database for the Audit Logging system. It also holds the data for PHP sessions and logon errors.', 'AUDIT', '2005-03-27 15:45:30', 'AJM', '2006-08-17 20:25:00', 'AJM');

INSERT INTO dict_table (database_id, table_id, table_name, table_desc, audit_logging, default_orderby, alt_language_table, alt_language_cols, nameof_start_date, nameof_end_date, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'Audit Field', 'This records each field (column) which has been updated durng a user''s session.', 'N', 'session_id, tran_seq_no, table_seq_no, field_id', NULL, NULL, NULL, NULL, '2005-12-30 09:54:51', 'AJM', '2007-02-24 15:36:56', 'AJM');

INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'field_id', 'field_id', '1', 'N', '0', '2008-07-26 10:20:39', 'AJM', '2017-09-26 14:31:00', 'AJM');
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'PRIMARY', 'field_id', '4', 'Y', '4', '2005-12-30 11:44:10', 'AJM', '2017-09-26 14:31:01', 'AJM');
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'PRIMARY', 'session_id', '1', 'Y', '1', '2005-12-30 11:44:10', 'AJM', '2017-09-26 14:31:00', 'AJM');
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'PRIMARY', 'table_seq_no', '3', 'Y', '3', '2005-12-30 11:44:10', 'AJM', '2017-09-26 14:31:00', 'AJM');
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'PRIMARY', 'tran_seq_no', '2', 'Y', '2', '2005-12-30 11:44:10', 'AJM', '2017-09-26 14:31:00', 'AJM');

INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'field_id', '4', 'Field Id', 'Ths identifies a field (column) on the current database table which was affected by this database transaction.', 'varchar', 'varchar', NULL, NULL, '255', '255', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2006-10-06 19:09:24', 'batch');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'new_value', '6', 'New Value', 'This was the contents of the field AFTER the database update.', 'text', 'text', NULL, NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2006-10-06 19:09:24', 'batch');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'old_value', '5', 'Old Value', 'This was the contents of the field BEFORE the database update.', 'text', 'text', NULL, NULL, '65535', '65535', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2006-10-06 19:09:24', 'batch');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'session_id', '1', 'Session Id', 'This points to an entry on the AUDIT_TBL table.', 'bigint', 'bigint,boolean', NULL, NULL, '20', '21', 'N', 'Y', 'PRI', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '1.84467440737096e19', '0', '1.84467440737096e19', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2017-09-26 14:30:58', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'table_seq_no', '3', 'Table Sequence Number', 'This points to an entry on the AUDIT_TBL table.', 'smallint', 'smallint,boolean', NULL, NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2017-09-26 14:32:27', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_fld', 'tran_seq_no', '2', 'Transaction Sequence Number', 'This points to an entry on the AUDIT_TBL table.', 'smallint', 'smallint,boolean', NULL, NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:10', 'AJM', '2017-09-26 14:32:12', 'AJM');

INSERT INTO dict_table (database_id, table_id, table_name, table_desc, audit_logging, default_orderby, alt_language_table, alt_language_cols, nameof_start_date, nameof_end_date, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_logon_errors', 'Audit Logon Errors', 'This holds the details of any logon attempt which failed.', 'Y', 'err_timestamp desc', NULL, NULL, NULL, NULL, '2006-03-07 11:06:19', 'AJM', '2007-02-24 15:37:10', 'AJM');

INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_logon_errors', 'PRIMARY', 'id', '1', 'Y', '0', '2006-03-07 11:41:11', 'AJM', NULL, NULL);

INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_logon_errors', 'email_addr', '6', 'Email Address', NULL, 'varchar', 'varchar', NULL, NULL, '50', '50', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2009-09-29 14:07:45', 'AJM', '2009-09-29 14:21:16', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_logon_errors', 'err_timestamp', '2', 'Error Timestamp', 'This is the date and time on which the faled logn attempt occurred.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2006-12-12 17:58:52', 'AJM', '2017-09-18 13:10:51', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_logon_errors', 'id', '1', 'Id', 'This is a unique identity which is generated by the system.', 'int', 'int,boolean', NULL, NULL, '11', '11', 'N', 'Y', 'PRI', NULL, 'Y', 'Y', NULL, NULL, NULL, '0', '4294967295', '0', '2147483647', NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2006-03-07 11:06:59', 'AJM', '2017-09-18 13:15:32', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_logon_errors', 'ip_address', '3', 'Ip Address', 'This is the IP address from which the failed logon attempt was initiated.', 'varchar', 'varchar', NULL, NULL, '40', '40', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2006-03-07 11:18:34', 'AJM', '2017-09-18 13:10:52', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_logon_errors', 'user_id', '4', 'User Id', 'This is the user_id that was used in this failed logon attempt.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2006-03-07 11:18:38', 'AJM', '2009-09-29 14:18:41', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_logon_errors', 'user_password', '5', 'User Password', 'This is the user_password that was used in this failed logon attempt.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2006-03-07 11:18:43', 'AJM', '2017-09-18 13:10:53', 'AJM');

INSERT INTO dict_table (database_id, table_id, table_name, table_desc, audit_logging, default_orderby, alt_language_table, alt_language_cols, nameof_start_date, nameof_end_date, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_ssn', 'Audit Session', 'This records the start of each user session for logging purposes.', 'N', 'ssn_datetime', NULL, NULL, NULL, NULL, '2005-12-30 09:54:51', 'AJM', '2017-09-25 13:22:04', 'AJM');

INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_ssn', 'PRIMARY', 'session_id', '1', 'Y', '0', '2005-12-30 11:44:22', 'AJM', NULL, NULL);
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_ssn', 'SSN_DATETIME', 'ssn_datetime', '1', 'N', '1', '2017-09-26 14:25:21', 'AJM', NULL, NULL);

INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_ssn', 'session_id', '1', 'Session Id', 'This is the unique identity for each session. It is not related to PHP''s session_id.', 'bigint', 'bigint,boolean', NULL, NULL, '20', '21', 'N', 'Y', 'PRI', NULL, 'Y', 'Y', NULL, NULL, NULL, '0', '1.84467440737096e19', '0', '1.84467440737096e19', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:21', 'AJM', '2017-09-26 14:25:21', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_ssn', 'ssn_datetime', '3', 'Session Datetime', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-09-26 14:25:14', 'AJM', '2017-09-26 14:27:51', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_ssn', 'user_id', '2', 'User Id', 'This points to an entry on the MNU_USER table of the MENU database.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'N', 'Y', NULL, 'UNKNOWN', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:21', 'AJM', '2006-10-07 11:10:18', 'AJM');

INSERT INTO dict_relationship (database_id_snr, table_id_snr, database_id_jnr, table_id_jnr, seq_no, table_alias_snr, table_alias_jnr, relation_name, relation_desc, relation_type, orderby, parent_field, calc_field, key_name, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_ssn', 'audit', 'audit_trn', '0', NULL, NULL, 'Links AUDIT_SSN to AUDIT_TRN', NULL, 'RES', NULL, NULL, NULL, 'PRIMARY', '2005-12-30 12:23:21', 'AJM', '2006-07-23 19:02:41', 'AJM');

INSERT INTO dict_related_column (database_id_snr, table_id_snr, column_id_snr, database_id_jnr, table_id_jnr, seq_no, column_id_jnr, seq_in_index, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_ssn', 'session_id', 'audit', 'audit_trn', '0', 'session_id', '1', '2005-12-30 12:23:21', 'AJM', '2005-12-30 12:23:30', 'AJM');

INSERT INTO dict_table (database_id, table_id, table_name, table_desc, audit_logging, default_orderby, alt_language_table, alt_language_cols, nameof_start_date, nameof_end_date, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'Audit Table', 'This records each database table which is updated within a transaction within a user''s session.', 'N', 'session_id, tran_seq_no, table_seq_no', NULL, NULL, NULL, NULL, '2005-12-30 09:54:51', 'AJM', '2007-02-24 15:37:37', 'AJM');

INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'pkey', 'pkey', '1', 'N', '0', '2005-12-30 11:44:30', 'AJM', '2017-09-26 14:30:22', 'AJM');
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'PRIMARY', 'session_id', '1', 'Y', '1', '2005-12-30 11:44:30', 'AJM', '2017-09-26 14:30:22', 'AJM');
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'PRIMARY', 'table_seq_no', '3', 'Y', '3', '2005-12-30 11:44:30', 'AJM', '2017-09-26 14:30:23', 'AJM');
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'PRIMARY', 'tran_seq_no', '2', 'Y', '2', '2005-12-30 11:44:30', 'AJM', '2017-09-26 14:30:23', 'AJM');

INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'base_name', '4', 'Base Name', 'This identifies the database (schema) in which this table belongs.', 'varchar', 'varchar', NULL, NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:30', 'AJM', '2017-09-26 14:30:21', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'pkey', '6', 'Pkey', 'This is the primary key of the record which was affected by this database transaction. It is in the format of the WHERE clause in an SQL query.', 'varchar', 'varchar', NULL, NULL, '255', '255', 'Y', 'N', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:30', 'AJM', '2017-09-26 14:30:22', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'session_id', '1', 'Session Id', 'This points to an entry on the AUDIT_TRN table.', 'bigint', 'bigint,boolean', NULL, NULL, '20', '21', 'N', 'Y', 'PRI', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '1.84467440737096e19', '0', '1.84467440737096e19', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:29', 'AJM', '2017-09-26 14:30:19', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'table_name', '5', 'Table Name', 'This is the name of the database table which was affected by this database transaction.', 'varchar', 'varchar', NULL, NULL, '64', '64', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:30', 'AJM', '2017-09-26 14:30:21', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'table_seq_no', '3', 'Table Seq No', 'This is incremented by 1 for each database table which is affected by this database transaction.', 'smallint', 'smallint,boolean', NULL, NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:29', 'AJM', '2017-09-26 14:30:20', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'tran_seq_no', '2', 'Tran Seq No', 'This points to an entry on the AUDIT_TRN table.', 'smallint', 'smallint,boolean', NULL, NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:29', 'AJM', '2017-09-26 14:30:20', 'AJM');

INSERT INTO dict_relationship (database_id_snr, table_id_snr, database_id_jnr, table_id_jnr, seq_no, table_alias_snr, table_alias_jnr, relation_name, relation_desc, relation_type, orderby, parent_field, calc_field, key_name, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'audit', 'audit_fld', '0', NULL, NULL, 'Links AUDIT_TBL to AUDIT_FLD', NULL, 'DEL', NULL, NULL, NULL, 'PRIMARY', '2005-12-30 12:24:29', 'AJM', '2006-07-23 19:02:47', 'AJM');

INSERT INTO dict_related_column (database_id_snr, table_id_snr, column_id_snr, database_id_jnr, table_id_jnr, seq_no, column_id_jnr, seq_in_index, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'session_id', 'audit', 'audit_fld', '0', 'session_id', '1', '2005-12-30 12:24:29', 'AJM', '2005-12-30 12:24:40', 'AJM');
INSERT INTO dict_related_column (database_id_snr, table_id_snr, column_id_snr, database_id_jnr, table_id_jnr, seq_no, column_id_jnr, seq_in_index, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'table_seq_no', 'audit', 'audit_fld', '0', 'table_seq_no', '3', '2005-12-30 12:24:29', 'AJM', '2005-12-30 12:24:40', 'AJM');
INSERT INTO dict_related_column (database_id_snr, table_id_snr, column_id_snr, database_id_jnr, table_id_jnr, seq_no, column_id_jnr, seq_in_index, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_tbl', 'tran_seq_no', 'audit', 'audit_fld', '0', 'tran_seq_no', '2', '2005-12-30 12:24:29', 'AJM', '2005-12-30 12:24:40', 'AJM');

INSERT INTO dict_table (database_id, table_id, table_name, table_desc, audit_logging, default_orderby, alt_language_table, alt_language_cols, nameof_start_date, nameof_end_date, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'Audit Transaction', 'This records each database transaction within a user''s session.', 'N', 'session_id, tran_seq_no', NULL, NULL, NULL, NULL, '2005-12-30 09:54:51', 'AJM', '2007-02-24 15:37:52', 'AJM');

INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'PRIMARY', 'session_id', '1', 'Y', '0', '2005-12-30 11:44:38', 'AJM', NULL, NULL);
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'PRIMARY', 'tran_seq_no', '2', 'Y', '1', '2005-12-30 11:44:38', 'AJM', NULL, NULL);
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'TRN_DATETIME', 'trn_datetime', '1', 'N', '2', '2017-09-26 14:28:34', 'AJM', NULL, NULL);

INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'session_id', '1', 'Session Id', 'This points to an entry on the AUDIT_SSN table.', 'bigint', 'bigint,boolean', NULL, NULL, '20', '21', 'N', 'Y', 'PRI', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '1.84467440737096e19', '0', '1.84467440737096e19', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:37', 'AJM', '2017-09-26 14:28:33', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'task_id', '4', 'Task Id', 'This is the identity of the task which created this database transaction.', 'varchar', 'varchar', NULL, NULL, '80', '80', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NED', NULL, NULL, 'LOWER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:38', 'AJM', '2017-09-26 14:28:34', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'tran_seq_no', '2', 'Transaction Sequence Number', 'This identifies each transaction within this session. It is incremented each time a new database transaction is started.', 'smallint', 'smallint,boolean', NULL, NULL, '6', '6', 'N', 'Y', 'PRI', NULL, 'N', 'Y', NULL, NULL, NULL, '0', '65535', '0', '65535', 'NED', NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-12-30 11:44:37', 'AJM', '2017-09-26 14:29:15', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'trn_datetime', '3', 'Transaction Datetime', NULL, 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', 'MUL', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'Y', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-09-26 14:28:28', 'AJM', '2017-09-26 14:29:43', 'AJM');

INSERT INTO dict_relationship (database_id_snr, table_id_snr, database_id_jnr, table_id_jnr, seq_no, table_alias_snr, table_alias_jnr, relation_name, relation_desc, relation_type, orderby, parent_field, calc_field, key_name, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'audit', 'audit_tbl', '0', NULL, NULL, 'Links AUDIT_TRN to AUDIT_TBL', NULL, 'DEL', NULL, NULL, NULL, 'PRIMARY', '2005-12-30 12:23:54', 'AJM', '2006-07-23 19:02:53', 'AJM');

INSERT INTO dict_related_column (database_id_snr, table_id_snr, column_id_snr, database_id_jnr, table_id_jnr, seq_no, column_id_jnr, seq_in_index, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'session_id', 'audit', 'audit_tbl', '0', 'session_id', '1', '2005-12-30 12:23:54', 'AJM', '2005-12-30 12:24:04', 'AJM');
INSERT INTO dict_related_column (database_id_snr, table_id_snr, column_id_snr, database_id_jnr, table_id_jnr, seq_no, column_id_jnr, seq_in_index, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'audit_trn', 'tran_seq_no', 'audit', 'audit_tbl', '0', 'tran_seq_no', '2', '2005-12-30 12:23:54', 'AJM', '2005-12-30 12:24:05', 'AJM');

INSERT INTO dict_table (database_id, table_id, table_name, table_desc, audit_logging, default_orderby, alt_language_table, alt_language_cols, nameof_start_date, nameof_end_date, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'php_session', 'PHP Session', 'This holds the data for each PHP session.', 'N', NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:14', 'AJM', '2007-02-24 15:38:03', 'AJM');

INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'php_session', 'last_updated', 'last_updated', '1', 'N', '0', '2005-04-09 16:08:54', 'AJM', '2017-10-26 15:36:58', 'AJM');
INSERT INTO dict_table_key (database_id, table_id, key_name, column_id, seq_in_index, is_unique, column_seq, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'php_session', 'PRIMARY', 'session_id', '1', 'Y', '1', '2005-04-09 16:08:54', 'AJM', '2017-09-18 13:06:59', 'AJM');

INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'php_session', 'date_created', '3', 'Date Created', 'This is the date and time on which this session was created.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', NULL, '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:54', 'AJM', '2006-10-06 19:09:30', 'batch');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'php_session', 'last_updated', '4', 'Last Updated', 'This is the date and time on which this session was updated.', 'datetime', 'datetime', NULL, NULL, '20', '20', 'N', 'Y', 'MUL', '2000-01-01 00:00:00', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:54', 'AJM', '2006-10-06 19:09:30', 'batch');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'php_session', 'session_data', '5', 'Session Data', 'This is the data that is taken from/to the $_SESSION array.', 'longblob', 'longblob', NULL, NULL, '4294967295', '4294967295', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 18:10:58', 'AJM', '2017-10-26 15:36:57', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'php_session', 'session_id', '1', 'Session Id', 'This is the session identity as created by PHP.', 'varchar', 'varchar', NULL, NULL, '256', '256', 'N', 'Y', 'PRI', NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:53', 'AJM', '2017-09-22 13:25:25', 'AJM');
INSERT INTO dict_column (database_id, table_id, column_id, column_seq, column_name, column_desc, col_type, col_type_native, col_array_type, col_values, user_size, col_maxsize, col_null, is_required, col_key, col_default, col_auto_increment, col_unsigned, col_zerofill_bwz, col_precision, col_scale, col_minvalue, col_maxvalue, user_minvalue, user_maxvalue, noedit_nodisplay, no_search, no_audit, upper_lowercase, is_password, auto_insert, auto_update, infinityisnull, col_subtype, image_width, image_height, is_boolean, boolean_true, boolean_false, control, optionlist, checkbox_label, task_id, foreign_field, align_hv, align_lr, multi_cols, multi_rows, custom_validation, created_date, created_user, revised_date, revised_user) VALUES ('audit', 'php_session', 'user_id', '2', 'User Id', 'This identfies the user, from the logon screen, who created this session.', 'varchar', 'varchar', NULL, NULL, '16', '16', 'Y', 'N', NULL, NULL, 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UPPER', 'N', 'N', 'N', 'N', NULL, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2005-04-09 16:08:53', 'AJM', '2017-09-18 13:06:56', 'AJM');

-- finished
